/* Generated by tools/vfpu_overlap_fuzz_gen.py --fixture-header.
 * Do not edit: keep in sync with the host selftest table. */

#ifndef NAKAGAWA_VFPU_OVERLAP_PROBE_CASES_H
#define NAKAGAWA_VFPU_OVERLAP_PROBE_CASES_H

#define VFPU_OVERLAP_PROBE_CASE_COUNT 91

#define OVERLAP_KLASS_DISJOINT 0
#define OVERLAP_KLASS_VD_EQ_VS 1
#define OVERLAP_KLASS_VD_EQ_VT 2
#define OVERLAP_KLASS_PARTIAL 3
#define OVERLAP_KLASS_TRANSPOSE 4
#define OVERLAP_KLASS_SRC_SRC 5
#define OVERLAP_KLASS_ALL_IDENT 6
#define OVERLAP_KLASS_SCALAR_IN_DEST 7
#define OVERLAP_CONTRACT_ALLOWED 0
#define OVERLAP_CONTRACT_NO_OVERLAP 1
#define OVERLAP_CONTRACT_UNESTABLED 2

typedef struct {
    const char *id;    /* stable case id */
    unsigned int w;    /* raw instruction word */
    unsigned klass;    /* alias class */
    unsigned family;  /* op family (see FAMILY_NAMES in generator) */
    unsigned contract; /* ALLOWED / NO_OVERLAP / UNESTABLED */
} VfpuOverlapProbeCase;

static const VfpuOverlapProbeCase VFPU_OVERLAP_PROBE_CASES[VFPU_OVERLAP_PROBE_CASE_COUNT] = {
    {"vmmul-k0-ct0-00", 0xf0080084u, 0u, 0u, 0u},
    {"vmmul-k1-ct1-01", 0xf0080080u, 1u, 0u, 1u},
    {"vmmul-k2-ct1-02", 0xf0080088u, 2u, 0u, 1u},
    {"vmmul-k3-ct1-03", 0xf0080081u, 3u, 0u, 1u},
    {"vmmul-k4-ct1-04", 0xf0082180u, 4u, 0u, 1u},
    {"vmmul-k5-ct2-05", 0xf0000084u, 5u, 0u, 2u},
    {"vmmul-k6-ct1-06", 0xf0000080u, 6u, 0u, 1u},
    {"vmmul-k0-ct0-07", 0xf008c004u, 0u, 0u, 0u},
    {"vmmul-k1-ct1-08", 0xf008c040u, 1u, 0u, 1u},
    {"vmmul-k2-ct1-09", 0xf008c008u, 2u, 0u, 1u},
    {"vmmul-k3-ct1-10", 0xf008c000u, 3u, 0u, 1u},
    {"vmmul-k4-ct1-11", 0xf008a100u, 4u, 0u, 1u},
    {"vmmul-k5-ct2-12", 0xf040c004u, 5u, 0u, 2u},
    {"vmmul-k6-ct1-13", 0xf040c040u, 6u, 0u, 1u},
    {"vmmul-k0-ct0-14", 0xf008c084u, 0u, 0u, 0u},
    {"vmmul-k1-ct1-15", 0xf008c0c0u, 1u, 0u, 1u},
    {"vmmul-k2-ct1-16", 0xf008c088u, 2u, 0u, 1u},
    {"vmmul-k5-ct2-17", 0xf040c084u, 5u, 0u, 2u},
    {"vmmul-k6-ct1-18", 0xf040c0c0u, 6u, 0u, 1u},
    {"vtfm-k0-ct0-19", 0xf0880084u, 0u, 1u, 0u},
    {"vtfm-k1-ct1-20", 0xf0880080u, 1u, 1u, 1u},
    {"vtfm-k2-ct1-21", 0xf0880088u, 2u, 1u, 1u},
    {"vtfm-k3-ct1-22", 0xf08000a0u, 3u, 1u, 1u},
    {"vtfm-k4-ct1-23", 0xf0882584u, 4u, 1u, 1u},
    {"vtfm-k5-ct2-24", 0xf0800084u, 5u, 1u, 2u},
    {"vtfm-k6-ct1-25", 0xf0800080u, 6u, 1u, 1u},
    {"vtfm-k0-ct0-26", 0xf108c004u, 0u, 1u, 0u},
    {"vtfm-k1-ct1-27", 0xf108c040u, 1u, 1u, 1u},
    {"vtfm-k2-ct1-28", 0xf108c008u, 2u, 1u, 1u},
    {"vtfm-k3-ct1-29", 0xf108c000u, 3u, 1u, 1u},
    {"vtfm-k3-ct1-30", 0xf100c020u, 3u, 1u, 1u},
    {"vtfm-k4-ct1-31", 0xf108a504u, 4u, 1u, 1u},
    {"vtfm-k5-ct2-32", 0xf100c004u, 5u, 1u, 2u},
    {"vtfm-k6-ct1-33", 0xf140c040u, 6u, 1u, 1u},
    {"vtfm-k0-ct0-34", 0xf188c084u, 0u, 1u, 0u},
    {"vtfm-k1-ct1-35", 0xf188c0c0u, 1u, 1u, 1u},
    {"vtfm-k2-ct1-36", 0xf188c088u, 2u, 1u, 1u},
    {"vtfm-k3-ct1-37", 0xf188c080u, 3u, 1u, 1u},
    {"vtfm-k3-ct1-38", 0xf180c0a0u, 3u, 1u, 1u},
    {"vtfm-k4-ct1-39", 0xf188a584u, 4u, 1u, 1u},
    {"vtfm-k5-ct2-40", 0xf180c084u, 5u, 1u, 2u},
    {"vtfm-k6-ct1-41", 0xf1c0c0c0u, 6u, 1u, 1u},
    {"vmscl-k0-ct0-42", 0xf2080084u, 0u, 2u, 0u},
    {"vmscl-k1-ct0-43", 0xf2040080u, 1u, 2u, 0u},
    {"vmscl-k7-ct2-44", 0xf2000080u, 7u, 2u, 2u},
    {"vmscl-k7-ct2-45", 0xf2040084u, 7u, 2u, 2u},
    {"vmscl-k3-ct1-46", 0xf2040081u, 3u, 2u, 1u},
    {"vmscl-k0-ct0-47", 0xf200c004u, 0u, 2u, 0u},
    {"vmscl-k1-ct0-48", 0xf200c040u, 1u, 2u, 0u},
    {"vmscl-k7-ct2-49", 0xf220c040u, 7u, 2u, 2u},
    {"vmscl-k7-ct2-50", 0xf204c004u, 7u, 2u, 2u},
    {"vmscl-k3-ct1-51", 0xf200c001u, 3u, 2u, 1u},
    {"vmscl-k0-ct0-52", 0xf208c084u, 0u, 2u, 0u},
    {"vmscl-k1-ct0-53", 0xf204c0c0u, 1u, 2u, 0u},
    {"vmscl-k7-ct2-54", 0xf200c0c0u, 7u, 2u, 2u},
    {"vmscl-k7-ct2-55", 0xf204c084u, 7u, 2u, 2u},
    {"vmmov-k0-ct0-56", 0xf3800084u, 0u, 3u, 0u},
    {"vmmov-k1-ct0-57", 0xf3800080u, 1u, 3u, 0u},
    {"vmmov-k3-ct1-58", 0xf3800081u, 3u, 3u, 1u},
    {"vmmov-k0-ct0-59", 0xf380c004u, 0u, 3u, 0u},
    {"vmmov-k1-ct0-60", 0xf380c040u, 1u, 3u, 0u},
    {"vmmov-k3-ct1-61", 0xf380c000u, 3u, 3u, 1u},
    {"vmmov-k0-ct0-62", 0xf380c084u, 0u, 3u, 0u},
    {"vmmov-k1-ct0-63", 0xf380c0c0u, 1u, 3u, 0u},
    {"vdot-k0-ct0-64", 0x64800081u, 0u, 4u, 0u},
    {"vdot-k3-ct2-65", 0x64800080u, 3u, 4u, 2u},
    {"vdot-k0-ct0-66", 0x64808001u, 0u, 4u, 0u},
    {"vdot-k3-ct2-67", 0x64808000u, 3u, 4u, 2u},
    {"vdot-k0-ct0-68", 0x64808081u, 0u, 4u, 0u},
    {"vdot-k3-ct2-69", 0x64808080u, 3u, 4u, 2u},
    {"vhdp-k0-ct0-70", 0x66000081u, 0u, 5u, 0u},
    {"vhdp-k3-ct2-71", 0x66000080u, 3u, 5u, 2u},
    {"vhdp-k0-ct0-72", 0x66008001u, 0u, 5u, 0u},
    {"vhdp-k3-ct2-73", 0x66008000u, 3u, 5u, 2u},
    {"vhdp-k0-ct0-74", 0x66008081u, 0u, 5u, 0u},
    {"vhdp-k3-ct2-75", 0x66008080u, 3u, 5u, 2u},
    {"vscl-k0-ct0-76", 0x65000081u, 0u, 7u, 0u},
    {"vscl-k1-ct2-77", 0x65000080u, 1u, 7u, 2u},
    {"vscl-k0-ct0-78", 0x65008001u, 0u, 7u, 0u},
    {"vscl-k1-ct2-79", 0x65008000u, 1u, 7u, 2u},
    {"vscl-k0-ct0-80", 0x65008081u, 0u, 7u, 0u},
    {"vscl-k1-ct2-81", 0x65008080u, 1u, 7u, 2u},
    {"vcrsp-k0-ct0-82", 0xf2848001u, 0u, 9u, 0u},
    {"vcrsp-k1-ct1-83", 0xf2848000u, 1u, 9u, 1u},
    {"vcrsp-k2-ct1-84", 0xf2848004u, 2u, 9u, 1u},
    {"vqmul-k0-ct0-85", 0xf2848081u, 0u, 8u, 0u},
    {"vqmul-k1-ct1-86", 0xf2848080u, 1u, 8u, 1u},
    {"vqmul-k2-ct1-87", 0xf2848084u, 2u, 8u, 1u},
    {"vcrs-k0-ct0-88", 0x66848001u, 0u, 6u, 0u},
    {"vcrs-k1-ct2-89", 0x66848000u, 1u, 6u, 2u},
    {"vcrs-k2-ct2-90", 0x66848004u, 2u, 6u, 2u},
};

#endif /* NAKAGAWA_VFPU_OVERLAP_PROBE_CASES_H */
