// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 the Nakagawa Recomp authors

/* Source-owned media selftest: synthetic PSMF -> bounded producer -> PES/access units ->
 * real H.264 backend -> guest-visible picture.
 *
 * Everything here is generated by this file, byte for byte.  The elementary stream is a
 * baseline-profile H.264 stream whose every macroblock is I_PCM, so the decoder's output is
 * exactly the luma/chroma values chosen in this file and the RGBA conversion can be checked
 * against known pixel values instead of a subjective picture comparison.  No retail media, no
 * extracted capture, no third-party bitstream is involved.
 *
 * The producer/demux assertions run on every platform.  The decode assertions run wherever a
 * real H.264 backend exists (the Windows Media Foundation backend, src/rt/h264_mf.c); on a
 * build without one they report SKIP, and the demux half still runs, so the fixture itself
 * always stays covered.
 *
 * Coverage that matters most:
 *   - AU formation across PES boundaries, with fragmented source reads;
 *   - timestamp normalization against the PSMF presentation base, including an AU whose PES
 *     carried no PTS (reported as "unknown", never invented);
 *   - a real decoded picture in the guest display buffer, checked pixel by pixel;
 *   - the end-of-stream contract: the last picture of the stream is released and decoded
 *     (regression: before sr_h264_frame() closed the trailing chunk at EOS the final picture
 *     of every stream was silently dropped), exactly once, and a fresh decoder instance never
 *     exposes a previous stream's trailing picture;
 *   - the legacy mpeg.c consumption path (sr_h264_feed + sr_h264_au_take + sr_h264_frame) is
 *     unchanged by that EOS release.
 */

#include "psmf_producer.h"
#include "sr_h264.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int checks, failures;
#define CHECK(x, text) do { checks++; if (!(x)) { failures++; fprintf(stderr, "FAIL: %s\n", text); } } while (0)
/* Bounded diagnostics for the acceptance runs: SR_PSMF_MEDIA_DEBUG=1 prints the counters that
 * say where a media chain stopped, without making the normal run noisy. */
#define MEDIA_DEBUG(...) do { if (getenv("SR_PSMF_MEDIA_DEBUG")) fprintf(stderr, __VA_ARGS__); } while (0)

/* ---- guest arena ------------------------------------------------------------------------ */
/* sr_h264_frame() writes into guest memory through SR_HOST(), so the selftest owns a flat
 * arena and a no-op VRAM-dirty sink, exactly as the runtime stubs them. */
uint8_t *g_mem = NULL;
void sr_gpu_vram_dirty(uint32_t addr, uint32_t bytes) { (void)addr; (void)bytes; }

#define ARENA_BYTES (8u * 1024u * 1024u)
#define GUEST_BUF   (0x08000000u + 0x00400000u)   /* 4 MiB into guest RAM */

/* ---- source-authored H.264 elementary stream -------------------------------------------- */

typedef struct {
    uint8_t *d; uint32_t cap, n;
    uint32_t acc; int bits;
    int overflow;
} BitW;

static void bw_byte(BitW *w, uint8_t b) {
    if (w->n >= w->cap) { w->overflow = 1; return; }
    w->d[w->n++] = b;
}
static void bw_bit(BitW *w, int b) {
    w->acc = (w->acc << 1) | (uint32_t)(b & 1);
    if (++w->bits == 8) { bw_byte(w, (uint8_t)w->acc); w->acc = 0; w->bits = 0; }
}
static void bw_u(BitW *w, uint32_t v, int n) {
    for (int i = n - 1; i >= 0; i--) bw_bit(w, (int)((v >> (unsigned)i) & 1u));
}
static void bw_ue(BitW *w, uint32_t v) {
    uint32_t x = v + 1u;
    int n = 0;
    for (uint32_t t = x; t; t >>= 1) n++;
    for (int i = 0; i < n - 1; i++) bw_bit(w, 0);
    bw_u(w, x, n);
}
static void bw_pad(BitW *w) { while (w->bits) bw_bit(w, 0); }
static void bw_trailing(BitW *w) { bw_bit(w, 1); bw_pad(w); }
/* Byte run inside a bit stream (I_PCM macroblock payload); pads partial bits with zeros,
 * which is exactly the pcm_alignment_zero_bit the syntax defines. */
static void bw_raw(BitW *w, const uint8_t *p, uint32_t n) {
    bw_pad(w);
    if (w->n + n > w->cap) { w->overflow = 1; return; }
    memcpy(w->d + w->n, p, n);
    w->n += n;
}

typedef struct { uint8_t *d; uint32_t cap, n; int overflow; } ByteOut;
static void bo_raw(ByteOut *o, const uint8_t *p, uint32_t n) {
    if (o->n + n > o->cap) { o->overflow = 1; return; }
    memcpy(o->d + o->n, p, n);
    o->n += n;
}
static void bo_byte(ByteOut *o, uint8_t b) { bo_raw(o, &b, 1); }
/* Annex-B NAL unit: start code, header, then the RBSP with emulation prevention. */
static void emit_nal(ByteOut *o, uint8_t hdr, const BitW *rbsp) {
    static const uint8_t start_code[3] = { 0, 0, 1 };
    bo_raw(o, start_code, 3u);
    bo_byte(o, hdr);
    int zeros = 0;
    for (uint32_t i = 0; i < rbsp->n; i++) {
        uint8_t b = rbsp->d[i];
        if (zeros >= 2 && b <= 3u) { bo_byte(o, 3u); zeros = 0; }
        bo_byte(o, b);
        zeros = (b == 0) ? zeros + 1 : 0;
    }
}

#define FIX_W_MBS 4
#define FIX_H_MBS 4
#define FIX_PICTURES 3

static void write_sps(BitW *w) {
    bw_u(w, 66u, 8);          /* profile_idc: baseline */
    bw_u(w, 0u, 8);           /* constraint set flags  */
    bw_u(w, 30u, 8);          /* level_idc 3.0         */
    bw_ue(w, 0u);             /* seq_parameter_set_id */
    bw_ue(w, 0u);             /* log2_max_frame_num_minus4 */
    bw_ue(w, 0u);             /* pic_order_cnt_type */
    bw_ue(w, 0u);             /* log2_max_pic_order_cnt_lsb_minus4 */
    bw_ue(w, 1u);             /* max_num_ref_frames */
    bw_bit(w, 0);             /* gaps_in_frame_num_value_allowed_flag */
    bw_ue(w, FIX_W_MBS - 1);  /* pic_width_in_mbs_minus1 */
    bw_ue(w, FIX_H_MBS - 1);  /* pic_height_in_map_units_minus1 */
    bw_bit(w, 1);             /* frame_mbs_only_flag */
    bw_bit(w, 1);             /* direct_8x8_inference_flag */
    bw_bit(w, 0);             /* frame_cropping_flag */
    bw_bit(w, 0);             /* vui_parameters_present_flag */
    bw_trailing(w);
}

static void write_pps(BitW *w) {
    bw_ue(w, 0u);             /* pic_parameter_set_id */
    bw_ue(w, 0u);             /* seq_parameter_set_id */
    bw_bit(w, 0);             /* entropy_coding_mode_flag: CAVLC */
    bw_bit(w, 0);             /* bottom_field_pic_order_in_frame_present_flag */
    bw_ue(w, 0u);             /* num_slice_groups_minus1 */
    bw_ue(w, 0u);             /* num_ref_idx_l0_default_active_minus1 */
    bw_ue(w, 0u);             /* num_ref_idx_l1_default_active_minus1 */
    bw_bit(w, 0);             /* weighted_pred_flag */
    bw_u(w, 0u, 2);           /* weighted_bipred_idc */
    bw_ue(w, 0u);             /* pic_init_qp_minus26 (se(0)) */
    bw_ue(w, 0u);             /* pic_init_qs_minus26 (se(0)) */
    bw_ue(w, 0u);             /* chroma_qp_index_offset (se(0)) */
    bw_bit(w, 0);             /* deblocking_filter_control_present_flag */
    bw_bit(w, 0);             /* constrained_intra_pred_flag */
    bw_bit(w, 0);             /* redundant_pic_cnt_present_flag */
    bw_trailing(w);
}

/* One IDR picture, every macroblock I_PCM, so luma and chroma are exactly (y, cb, cr). */
static void write_idr(BitW *w, int picture, uint8_t y, uint8_t cb, uint8_t cr) {
    uint8_t pcm[256 + 64 + 64];
    memset(pcm, y, 256u);
    memset(pcm + 256, cb, 64u);
    memset(pcm + 320, cr, 64u);
    bw_ue(w, 0u);                       /* first_mb_in_slice */
    bw_ue(w, 2u);                       /* slice_type: I */
    bw_ue(w, 0u);                       /* pic_parameter_set_id */
    bw_u(w, (uint32_t)(picture % 16), 4);   /* frame_num */
    bw_ue(w, (uint32_t)(picture % 2));      /* idr_pic_id */
    bw_u(w, 0u, 4);                     /* pic_order_cnt_lsb */
    bw_bit(w, 0);                       /* dec_ref_pic_marking.no_output_of_prior_pics_flag */
    bw_bit(w, 0);                       /* dec_ref_pic_marking.long_term_reference_flag */
    bw_ue(w, 0u);                       /* slice_qp_delta (se(0)) */
    for (int mb = 0; mb < FIX_W_MBS * FIX_H_MBS; mb++) {
        bw_ue(w, 25u);                  /* mb_type: I_PCM */
        bw_raw(w, pcm, (uint32_t)sizeof(pcm));
    }
    bw_trailing(w);
}

/* Decoded plane values per picture.  Chosen so the BT.601 limited-range conversion lands on
 * values that are stable, non-clipping, and easy to state as a literal expectation. */
static const uint8_t k_y[FIX_PICTURES]  = { 200u, 128u, 128u };
static const uint8_t k_cb[FIX_PICTURES] = {  90u, 128u, 160u };
static const uint8_t k_cr[FIX_PICTURES] = { 160u, 128u,  96u };

/* One access unit = access-unit delimiter + (on the first picture) parameter sets + IDR. */
static void build_au(int picture, ByteOut *out) {
    static const uint8_t aud[5] = { 0, 0, 1, 0x09, 0x10 };
    BitW w;
    uint8_t scratch[8192];
    bo_raw(out, aud, sizeof(aud));
    if (picture == 0) {
        w.d = scratch; w.cap = sizeof(scratch); w.n = 0; w.acc = 0; w.bits = 0; w.overflow = 0;
        write_sps(&w);
        CHECK(!w.overflow, "SPS fits the scratch buffer");
        emit_nal(out, 0x67, &w);
        w.n = 0; w.acc = 0; w.bits = 0; w.overflow = 0;
        write_pps(&w);
        CHECK(!w.overflow, "PPS fits the scratch buffer");
        emit_nal(out, 0x68, &w);
    }
    w.d = scratch; w.cap = sizeof(scratch); w.n = 0; w.acc = 0; w.bits = 0; w.overflow = 0;
    write_idr(&w, picture, k_y[picture], k_cb[picture], k_cr[picture]);
    CHECK(!w.overflow, "IDR picture fits the scratch buffer");
    emit_nal(out, 0x65, &w);
}

/* Build the annex-B elementary stream and report each access unit's byte range, which is what
 * the producer must reproduce exactly. */
static int build_stream(uint8_t *dst, uint32_t cap, uint32_t au_off[FIX_PICTURES],
                        uint32_t au_len[FIX_PICTURES], uint32_t *total) {
    ByteOut o;
    o.d = dst; o.cap = cap; o.n = 0; o.overflow = 0;
    for (int i = 0; i < FIX_PICTURES; i++) {
        au_off[i] = o.n;
        build_au(i, &o);
        au_len[i] = o.n - au_off[i];
    }
    *total = o.n;
    return !o.overflow;
}

/* ---- synthetic PSMF container ------------------------------------------------------------ */

typedef struct { uint8_t *data; uint32_t size; uint32_t max_chunk; int fail; } MemSource;

static int mem_read(void *opaque, uint64_t off, void *dst, uint32_t cap, uint32_t *got) {
    MemSource *m = (MemSource *)opaque;
    if (!m || !dst || !got || off > m->size) { if (got) *got = 0; return SR_PSMF_SOURCE_ERROR; }
    if (m->fail) { *got = 0; return SR_PSMF_SOURCE_ERROR; }
    if (off == m->size) { *got = 0; return SR_PSMF_SOURCE_EOF; }
    uint32_t n = m->size - (uint32_t)off;
    if (n > cap) n = cap;
    if (m->max_chunk && n > m->max_chunk) n = m->max_chunk;
    memcpy(dst, m->data + (uint32_t)off, n);
    *got = n;
    return SR_PSMF_SOURCE_DATA;
}

typedef struct { uint8_t *d; uint32_t at, cap; int overflow; } Buf;
static void put(Buf *b, const uint8_t *p, uint32_t n) {
    if (b->at + n > b->cap) { b->overflow = 1; return; }
    memcpy(b->d + b->at, p, n);
    b->at += n;
}
static void be32_at(uint8_t *p, uint32_t v) {
    p[0] = (uint8_t)(v >> 24); p[1] = (uint8_t)(v >> 16); p[2] = (uint8_t)(v >> 8); p[3] = (uint8_t)v;
}
static void put_pts(uint8_t *p, int64_t v) {
    uint64_t x = (uint64_t)v;
    p[0] = (uint8_t)(0x21u | (((x >> 30) & 7u) << 1) | 1u);
    p[1] = (uint8_t)(x >> 22);
    p[2] = (uint8_t)((((x >> 15) & 0x7fu) << 1) | 1u);
    p[3] = (uint8_t)(x >> 7);
    p[4] = (uint8_t)(((x & 0x7fu) << 1) | 1u);
}
/* One MPEG-PS packet: pack header, then a PES packet with a single video payload slice.
 * The '10' marker in the first flags byte is mandatory even on a packet that carries no
 * presentation time, and the optional-header length is what says whether one follows. */
static void add_video_pes(Buf *b, int has_pts, int64_t pts, const uint8_t *payload, uint32_t len) {
    static const uint8_t pack[14] = { 0,0,1,0xba, 0x44,0,4,0,4,1,0,0,1,0 };
    uint32_t opt = has_pts ? 5u : 0u;
    uint32_t total = 3u + opt + len;
    uint8_t hdr[9];
    put(b, pack, sizeof(pack));
    hdr[0]=0; hdr[1]=0; hdr[2]=1; hdr[3]=0xe0;
    hdr[4]=(uint8_t)(total >> 8); hdr[5]=(uint8_t)total;
    hdr[6]=0x80u; hdr[7]=0; hdr[8]=(uint8_t)opt;
    put(b, hdr, sizeof(hdr));
    if (has_pts) { uint8_t p[5]; put_pts(p, pts); put(b, p, sizeof(p)); }
    put(b, payload, len);
}
/* Audio access unit: private-stream-1 sub-header + one self-delimiting ATRAC frame. */
static void add_audio_pes(Buf *b, const uint8_t *frame, uint32_t len) {
    static const uint8_t pack[14] = { 0,0,1,0xba, 0x44,0,4,0,4,1,0,0,1,0 };
    uint8_t prefix[4] = { 0x00, 0x00, 0x00, 0x00 };
    uint32_t total = 3u + 4u + len;
    uint8_t hdr[9];
    put(b, pack, sizeof(pack));
    hdr[0]=0; hdr[1]=0; hdr[2]=1; hdr[3]=0xbd;
    hdr[4]=(uint8_t)(total >> 8); hdr[5]=(uint8_t)total;
    hdr[6]=0x80u; hdr[7]=0; hdr[8]=0;
    put(b, hdr, sizeof(hdr));
    put(b, prefix, sizeof(prefix));
    put(b, frame, len);
}
/* One self-delimiting ATRAC frame (8-byte header + data); the size field is
 * ((code1 & 3) << 8 | code2 * 8) + 0x10 total bytes. */
static uint32_t make_audio_frame(uint8_t *dst, uint32_t cap, uint8_t code1, uint8_t code2,
                                 uint8_t fill) {
    uint32_t total = (uint32_t)(((code1 & 0x03u) << 8) | ((uint32_t)code2 * 8u)) + 0x10u;
    if (total > cap) return 0;
    memset(dst, fill, total);
    dst[0] = 0x0f; dst[1] = 0xd0; dst[2] = code1; dst[3] = code2;
    dst[4] = dst[5] = dst[6] = dst[7] = 0;
    return total;
}

/* PSMF presentation base and per-picture PES times.  Picture 2 deliberately carries no PTS,
 * which is the normal case in a PSP movie and the case a consumer must extrapolate rather
 * than invent. */
#define FIX_BASE      90000
#define FIX_PTS_STEP  3003
static const int k_has_pts[FIX_PICTURES] = { 1, 1, 0 };

/* ---- fixture self-validation ------------------------------------------------------------ */
/* Building this fixture wrongly has twice produced a failure that looked like a demux or
 * decoder defect: a NAL emitted without its start code, and a PES header written without the
 * mandatory '10' marker bits.  Both are structural, so the fixture now checks its own output
 * before any test reads it -- a malformed fixture fails here, as a fixture problem, instead of
 * being diagnosed from the pipeline's behaviour. */
static void mp4_picture_marks(const uint8_t *au, uint32_t n, int picture);

static uint32_t pes_count(const uint8_t *s, uint32_t n) {
    uint32_t at = 2048u;              /* the stream begins after the PSMF header */
    uint32_t packets = 0;
    while (at + 6u <= n) {
        CHECK(memcmp(s + at, "\0\0\1\xba", 4u) == 0, "every packet is preceded by a pack header");
        at += 14u;
        if (at + 6u > n) break;
        CHECK(s[at] == 0u && s[at + 1] == 0u && s[at + 2] == 1u, "PES start-code prefix is 00 00 01");
        uint8_t id = s[at + 3];
        CHECK(id == 0xbdu || (id & 0xe0u) == 0xe0u, "PES stream id is a video or private stream");
        CHECK((s[at + 6] & 0xc0u) == 0x80u, "PES flags byte carries the mandatory '10' marker bits");
        uint32_t opt = s[at + 8];
        CHECK(opt == 0u || opt == 5u, "optional PES header is absent or exactly one PTS field");
        if (opt == 5u) {
            CHECK((s[at + 9] & 0xf0u) == 0x20u, "PTS field carries the '0010' prefix");
            CHECK((s[at + 9] & 1u) != 0u && (s[at + 11] & 1u) != 0u && (s[at + 13] & 1u) != 0u,
                  "PTS field carries all three marker bits");
        }
        uint32_t declared = ((uint32_t)s[at + 4] << 8) | s[at + 5];
        CHECK(declared >= 3u + opt, "declared PES length covers its own header fields");
        uint32_t span = 6u + declared;      /* start code + id + length, then the declared body */
        CHECK(at + span <= n, "declared PES length stays inside the container");
        at += span;
        packets++;
    }
    CHECK(at == n, "the packet walk consumes the container exactly, with no trailing bytes");
    return packets;
}

/* Every picture's elementary bytes must be a real Annex-B access unit: a leading access-unit
 * delimiter, and inside the stream the parameter sets before the first slice.  The scan is
 * safe as a literal search because emit_nal() escapes emulation sequences, so a NAL never
 * contains a byte pattern that could be mistaken for a start code. */
static void check_es_wellformed(const uint8_t *es, uint32_t n, const uint32_t *au_off,
                               const uint32_t *au_len) {
    int sps = 0, pps = 0, idr = 0, aud = 0, slices_before_pps = 0;
    for (uint32_t i = 0; i + 3u < n; i++) {
        if (es[i] != 0u || es[i + 1] != 0u || es[i + 2] != 1u) continue;
        uint8_t hdr = es[i + 3];
        CHECK((hdr & 0x80u) == 0u, "every start code is followed by a NAL header, not payload");
        switch (hdr & 0x1fu) {
            case 9:  aud++; break;
            case 7:  sps++; break;
            case 8:  pps++; break;
            case 5:  if (!pps) slices_before_pps++; idr++; break;
            default: break;
        }
    }
    CHECK(sps == 1, "the elementary stream carries exactly one SPS");
    CHECK(pps == 1, "the elementary stream carries exactly one PPS");
    CHECK(aud == FIX_PICTURES, "one access-unit delimiter per picture");
    CHECK(idr == FIX_PICTURES, "one IDR slice per picture");
    CHECK(slices_before_pps == 0, "the parameter sets precede the first slice");
    for (int i = 0; i < FIX_PICTURES; i++) {
        CHECK(au_len[i] > 8u, "a picture access unit is longer than its header");
        CHECK(au_off[i] + au_len[i] <= n, "a picture access unit stays inside the stream");
        mp4_picture_marks(es + au_off[i], au_len[i], i);
    }
}

/* Each picture must start with its delimiter and contain an IDR slice carrying the picture's
 * own marker, so a fixture that silently emitted the wrong picture cannot pass a test that
 * only counts bytes. */
static void mp4_picture_marks(const uint8_t *au, uint32_t n, int picture) {
    CHECK(n >= 5u && au[0] == 0u && au[1] == 0u && au[2] == 1u && (au[3] & 0x1fu) == 9u,
          "a picture access unit begins with an access-unit delimiter");
    int idr = 0;
    for (uint32_t i = 0; i + 4u < n; i++) {
        if (au[i] == 0u && au[i + 1] == 0u && au[i + 2] == 1u && (au[i + 3] & 0x1fu) == 5u) idr++;
    }
    CHECK(idr == 1, "a picture access unit carries exactly one IDR slice");
    (void)picture;
}

/* Assemble the whole container: a validated PSMF header, then the video elementary stream cut
 * into two PES packets per picture (so access units always straddle packet boundaries) with an
 * audio track interleaved between them. */
static uint8_t *build_psmf(uint32_t *size_out, uint32_t au_off[FIX_PICTURES],
                           uint32_t au_len[FIX_PICTURES]) {
    uint8_t es[65536];
    uint32_t es_len = 0;
    CHECK(build_stream(es, sizeof(es), au_off, au_len, &es_len), "generated H.264 stream fits");
    Buf b;
    (void)es_len;
    b.cap = 2048u + es_len * 2u + 4096u;
    b.d = (uint8_t *)calloc(1, b.cap);
    b.at = 2048u;
    b.overflow = 0;
    if (!b.d) return NULL;
    b.d[0] = 'P'; b.d[1] = 'S'; b.d[2] = 'M'; b.d[3] = 'F';
    be32_at(b.d + 8, 2048u);
    uint8_t aframe[128];
    for (int i = 0; i < FIX_PICTURES; i++) {
        uint32_t half = au_len[i] / 2u;
        add_video_pes(&b, k_has_pts[i], FIX_BASE + (int64_t)i * FIX_PTS_STEP, es + au_off[i], half);
        add_video_pes(&b, 0, 0, es + au_off[i] + half, au_len[i] - half);
        if (i == 0) {
            uint32_t n = make_audio_frame(aframe, sizeof(aframe), 0x28, 6, 0xa5);
            add_audio_pes(&b, aframe, n);
        }
        if (i == 1) {
            uint8_t junk[24];
            memset(junk, 0xb7, sizeof(junk));       /* no frame header: the producer resyncs */
            add_audio_pes(&b, junk, sizeof(junk));
        }
    }
    /* Trailing audio frame, so the last thing in the stream is not part of the video track. */
    {
        uint32_t n = make_audio_frame(aframe, sizeof(aframe), 0x28, 7, 0x5a);
        add_audio_pes(&b, aframe, n);
    }
    be32_at(b.d + 12, b.at - 2048u);
    CHECK(!b.overflow, "synthetic PSMF container fits its buffer");
    /* The fixture proves its own structure before any test reads it. */
    CHECK(pes_count(b.d, b.at) >= (uint32_t)(FIX_PICTURES * 2 + 2),
          "the container holds every packet the builder wrote");
    check_es_wellformed(es, es_len, au_off, au_len);
    *size_out = b.at;
    return b.d;
}

/* ---- tests ------------------------------------------------------------------------------ */

static SrPsmfProducer *open_fixture(uint8_t *data, uint32_t size, MemSource *mem,
                                    uint32_t chunk) {
    mem->data = data; mem->size = size; mem->max_chunk = chunk; mem->fail = 0;
    SrPsmfSource source;
    source.read = mem_read;
    source.opaque = mem;
    source.size = size;
    return sr_psmf_producer_open(&source, FIX_BASE);
}

/* The producer must reproduce, byte for byte, the access units the fixture generator wrote,
 * while reading the container in fragments that never align with a packet boundary. */
static void test_demux_and_au_contract(void) {
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    CHECK(bytes != NULL, "fixture allocated");
    if (!bytes) return;
    /* The generator is deterministic, so the expected elementary stream can be rebuilt here
     * and compared against what the producer hands back. */
    static uint8_t es[65536];
    uint32_t es_total = 0;
    CHECK(build_stream(es, sizeof(es), au_off, au_len, &es_total), "expected stream rebuilds");

    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 7u);   /* 7-byte reads */
    CHECK(p != NULL, "producer opens the synthetic PSMF");
    if (!p) { free(bytes); return; }

    uint32_t got_sizes[FIX_PICTURES + 2];
    uint32_t got_pts[FIX_PICTURES + 2];
    int got_has_pts[FIX_PICTURES + 2];
    uint8_t *got_bytes[FIX_PICTURES + 2];
    int n = 0;
    for (int guard = 0; guard < 4096 && !sr_psmf_producer_eof(p); guard++) {
        sr_psmf_producer_pump(p, 1);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            CHECK(n < FIX_PICTURES + 2, "no more video access units than pictures were written");
            if (n < FIX_PICTURES + 2) {
                got_sizes[n] = au.size;
                got_pts[n] = (uint32_t)au.pts;
                got_has_pts[n] = au.has_pts != 0;
                got_bytes[n] = au.data;
                au.data = NULL;
            }
            sr_psmf_au_release(&au);
            n++;
        }
    }
    CHECK(n == FIX_PICTURES, "one video access unit per authored picture");
    for (int i = 0; i < FIX_PICTURES && i < n; i++) {
        CHECK(got_sizes[i] == au_len[i], "access unit size matches the authored picture");
        if (got_sizes[i] == au_len[i])
            CHECK(memcmp(got_bytes[i], es + au_off[i], au_len[i]) == 0,
                  "access unit bytes match the authored elementary stream");
        CHECK(got_has_pts[i] == k_has_pts[i],
              "PES presentation-time presence survives AU formation");
        if (k_has_pts[i])
            CHECK(got_pts[i] == (uint32_t)(i * FIX_PTS_STEP),
                  "timestamp normalized against the PSMF presentation base");
        if (!k_has_pts[i])
            CHECK(!got_has_pts[i], "a packet with no PTS is reported as unknown, not invented");
        free(got_bytes[i]);
    }

    SrPsmfProducerStats st;
    sr_psmf_producer_stats(p, &st);
    MEDIA_DEBUG("demux: bytes=%llu packs=%llu pes=%llu vpes=%llu apes=%llu vau=%llu aau=%llu"
                " pf=%llu sf=%llu fail_at=%llu failed=%d eof=%d first=%lld last=%lld\n",
                (unsigned long long)st.bytes_read, (unsigned long long)st.packs,
                (unsigned long long)st.pes_packets, (unsigned long long)st.video_pes,
                (unsigned long long)st.audio_pes, (unsigned long long)st.video_aus,
                (unsigned long long)st.audio_aus, (unsigned long long)st.parser_failures,
                (unsigned long long)st.source_failures, (unsigned long long)st.fail_offset,
                st.failed, st.eof, (long long)st.first_pts, (long long)st.last_pts);
    CHECK(st.video_aus == FIX_PICTURES, "producer counts every picture");
    CHECK(st.audio_aus >= 1, "the interleaved audio track is demuxed independently");
    CHECK(st.source_failures == 0, "fragmented reads never report a source failure");
    CHECK(st.failed == 0, "no parser failure on well-formed input");
    CHECK(st.eof, "the producer reaches end of file");
    sr_psmf_producer_close(p);
    free(bytes);
}

/* One decoder, the producer's own access units, the guest display buffer. */
static void test_real_decode_into_guest_buffer(void) {
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    if (!bytes) { CHECK(0, "fixture allocated"); return; }
    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 512u);
    CHECK(p != NULL, "producer opens for the decode test");

    int dec = sr_h264_create();
    if (dec < 0 || !p) {
        fprintf(stderr, "SKIP: no H.264 backend on this build (demux contract still verified)\n");
        sr_psmf_producer_close(p);
        free(bytes);
        return;
    }

    /* Feed exactly like the guest player: every produced access unit goes to the decoder, and
     * frames are pulled while the stream is still being fed (eos = 0). */
    int frames_before_eos = 0, frames_after_eos = 0, aus = 0;
    for (int guard = 0; guard < 65536; guard++) {
        sr_psmf_producer_pump(p, 4);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            sr_h264_submit_au(dec, au.data, au.size);
            sr_psmf_au_release(&au);
            aus++;
        }
        int r = sr_h264_frame(dec, 0, GUEST_BUF, 64, 3);
        CHECK(r >= 0, "decoding a fed access unit never fails");
        if (r > 0) frames_before_eos++;
        if (sr_psmf_producer_eof(p) && r == 0) break;
    }
    MEDIA_DEBUG("decode: aus=%d before_eos=%d after_eos=%d\n", aus, frames_before_eos, frames_after_eos);
    CHECK(aus == FIX_PICTURES, "every picture reached the decoder");
    CHECK(frames_before_eos >= 1, "a real decoder produced a picture before end of stream");

    /* Drain: the last picture has no following delimiter to close it, so only end-of-stream
     * can release it.  Before that release existed this loop produced nothing. */
    for (int i = 0; i < 16; i++) {
        int r = sr_h264_frame(dec, 1, GUEST_BUF, 64, 3);
        CHECK(r >= 0, "end-of-stream drain never fails");
        if (r <= 0) break;
        frames_after_eos++;
    }
    CHECK(frames_before_eos + frames_after_eos == FIX_PICTURES,
          "the stream yields exactly one picture per authored picture (final picture released at EOS)");
    CHECK(frames_after_eos >= 1, "the trailing picture is released by the end-of-stream drain");

    /* Repeated end-of-stream must not duplicate output. */
    int extra = 0;
    for (int i = 0; i < 8; i++) if (sr_h264_frame(dec, 1, GUEST_BUF, 64, 3) > 0) extra++;
    CHECK(extra == 0, "a drained decoder produces no further pictures");
    sr_h264_destroy(dec);
    sr_psmf_producer_close(p);
    free(bytes);
}

/* Decoded pixels are exactly the authored YCbCr, converted with BT.601 limited range. */
static void test_decoded_pixels(void) {
    static const uint8_t expect[FIX_PICTURES][3] = {
        { 255u, 203u, 138u },     /* (200,  90, 160) */
        { 130u, 130u, 130u },     /* (128, 128, 128) */
        {  79u, 144u, 195u },     /* (128, 160,  96) */
    };
    int dec = sr_h264_create();
    if (dec < 0) {
        fprintf(stderr, "SKIP: pixel assertions need a real H.264 backend\n");
        return;
    }
    uint8_t host[64 * 272 * 4];
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    if (!bytes) { CHECK(0, "fixture allocated"); sr_h264_destroy(dec); return; }
    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 2048u);
    if (!p) { CHECK(0, "producer opens"); free(bytes); sr_h264_destroy(dec); return; }

    int seen = 0;
    for (int guard = 0; guard < 65536 && seen < FIX_PICTURES; guard++) {
        SrPsmfAu au;
        sr_psmf_producer_pump(p, 2);
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            sr_h264_submit_au(dec, au.data, au.size);
            sr_psmf_au_release(&au);
        }
        int eos = sr_psmf_producer_eof(p);
        while (seen < FIX_PICTURES) {
            int r = sr_h264_frame_host(dec, eos, host, 64, 64 * 4);
            if (r < 0) { CHECK(0, "host decode failed"); break; }
            if (r == 0) break;
            const uint8_t *want = expect[seen];
            int bad = 0;
            for (int y = 0; y < 64 && !bad; y++)
                for (int x = 0; x < 64; x++) {
                    const uint8_t *px = host + ((size_t)y * 64u + (size_t)x) * 4u;
                    if (px[0] != want[0] || px[1] != want[1] || px[2] != want[2] || px[3] != 0xFFu) {
                        bad = 1; break;
                    }
                }
            CHECK(!bad, "every decoded pixel matches the authored picture");
            seen++;
        }
    }
    CHECK(seen == FIX_PICTURES, "the decoder delivered every authored picture");
    sr_psmf_producer_close(p);
    free(bytes);
    sr_h264_destroy(dec);
}

/* A fresh decoder instance must never expose the previous stream's trailing picture. */
static void test_instance_isolation(void) {
    int dec = sr_h264_create();
    if (dec < 0) { fprintf(stderr, "SKIP: instance isolation needs a real H.264 backend\n"); return; }
    /* Nothing was ever fed: end of stream on an empty instance reports "no picture". */
    CHECK(sr_h264_frame(dec, 1, GUEST_BUF, 64, 3) == 0, "an unfed decoder produces no picture");
    sr_h264_destroy(dec);

    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint8_t es[65536];
    uint32_t es_len = 0;
    if (!build_stream(es, sizeof(es), au_off, au_len, &es_len)) { CHECK(0, "stream builds"); return; }

    int first = sr_h264_create();
    CHECK(first >= 0, "decoder instance for the isolation test");
    if (first < 0) return;
    for (int i = 0; i < FIX_PICTURES; i++) sr_h264_submit_au(first, es + au_off[i], au_len[i]);
    int got = 0;
    for (int i = 0; i < 16; i++) {
        int r = sr_h264_frame(first, 1, GUEST_BUF, 64, 3);
        if (r <= 0) break;
        got++;
    }
    MEDIA_DEBUG("isolation: first instance pictures=%d\n", got);
    CHECK(got >= 1, "the first instance decodes");
    sr_h264_destroy(first);

    int second = sr_h264_create();
    CHECK(second >= 0, "decoder instance after destroy");
    if (second < 0) return;
    int stale = 0;
    for (int i = 0; i < 8; i++) if (sr_h264_frame(second, 1, GUEST_BUF, 64, 3) > 0) stale++;
    CHECK(stale == 0, "a restarted decoder exposes no picture from the previous stream");
    sr_h264_destroy(second);
}

/* An unusable destination must not be reported as a produced frame, and must not poison the
 * decoder for the pictures that follow. */
static void test_destination_refusal(void) {
    int dec = sr_h264_create();
    if (dec < 0) { fprintf(stderr, "SKIP: destination checks need a real H.264 backend\n"); return; }
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint8_t es[65536];
    uint32_t es_len = 0;
    if (!build_stream(es, sizeof(es), au_off, au_len, &es_len)) { CHECK(0, "stream builds"); return; }

    /* Out-of-range guest buffer: the picture exists but cannot be delivered. */
    sr_h264_submit_au(dec, es + au_off[0], au_len[0]);
    sr_h264_submit_au(dec, es + au_off[1], au_len[1]);
    int r = sr_h264_frame(dec, 0, 0x0FFFFFF0u, 64, 3);
    CHECK(r <= 0, "an unusable destination is not reported as a produced frame");

    /* The decoder is still usable for the next picture. */
    int ok = 0;
    for (int i = 0; i < 8; i++) if (sr_h264_frame(dec, 1, GUEST_BUF, 64, 3) > 0) { ok = 1; break; }
    CHECK(ok, "a refused destination does not poison the decoder");
    sr_h264_destroy(dec);
}

/* The sceMpeg consumption path (feed -> au_take -> frame) must be unchanged by the EOS
 * release: each taken access unit still yields exactly one picture, including the last. */
static void test_legacy_feed_take_path(void) {
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    if (!bytes) { CHECK(0, "fixture allocated"); return; }
    int dec = sr_h264_create();
    if (dec < 0) {
        fprintf(stderr, "SKIP: the mpeg.c consumption path needs a real H.264 backend\n");
        free(bytes);
        return;
    }
    sr_h264_feed(dec, bytes + 2048u, size - 2048u);
    int frames = 0, taken = 0;
    for (int guard = 0; guard < 64; guard++) {
        uint64_t consumed = 0;
        int64_t pts = 0;
        int took = sr_h264_au_take(dec, 0, &consumed, &pts);
        if (took > 0) taken++;
        for (int i = 0; i < 8; i++) {
            int r = sr_h264_frame(dec, 0, GUEST_BUF, 64, 3);
            if (r < 0) { CHECK(0, "legacy path decode failed"); break; }
            if (r == 0) break;
            frames++;
        }
        if (took <= 0) break;
    }
    uint64_t consumed = 0;
    if (sr_h264_au_take(dec, 1, &consumed, NULL) > 0) taken++;
    for (int i = 0; i < 16; i++) {
        int r = sr_h264_frame(dec, 1, GUEST_BUF, 64, 3);
        if (r < 0) { CHECK(0, "legacy path end-of-stream decode failed"); break; }
        if (r == 0) break;
        frames++;
    }
    MEDIA_DEBUG("legacy path: taken=%d frames=%d\n", taken, frames);
    CHECK(taken == FIX_PICTURES, "the demuxed stream hands out one access unit per picture");
    CHECK(frames == FIX_PICTURES, "each access unit yields exactly one decoded picture");
    sr_h264_destroy(dec);
    free(bytes);
}

/* A malformed audio track must leave the video track alone. */
static void test_track_independence(void) {
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    if (!bytes) { CHECK(0, "fixture allocated"); return; }
    /* Corrupt the audio payload bytes in place: the video elementary stream is untouched. */
    for (uint32_t i = 2048u; i + 6u < size; i++) {
        if (bytes[i] != 0 || bytes[i + 1] != 0 || bytes[i + 2] != 1 || bytes[i + 3] != 0xbd) continue;
        uint32_t len = ((uint32_t)bytes[i + 4] << 8) | bytes[i + 5];
        uint32_t payload = i + 9u + 4u;
        if (payload + 8u > size) break;
        memset(bytes + payload, 0xb7, 8u);      /* destroy the audio frame header */
        i += 9u + len;
    }
    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 1024u);
    CHECK(p != NULL, "producer opens a PSMF with a corrupt audio track");
    if (!p) { free(bytes); return; }
    int video = 0;
    for (int guard = 0; guard < 4096 && !sr_psmf_producer_eof(p); guard++) {
        sr_psmf_producer_pump(p, 2);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) { video++; sr_psmf_au_release(&au); }
    }
    CHECK(video == FIX_PICTURES, "a corrupt audio track cannot cost the video track its pictures");
    SrPsmfProducerStats st;
    sr_psmf_producer_stats(p, &st);
    CHECK(st.audio_resync_bytes > 0, "the corrupt audio bytes are counted, not silently trusted");
    sr_psmf_producer_close(p);
    free(bytes);
}

int main(void) {
    static uint8_t arena[ARENA_BYTES];
    g_mem = arena;
    memset(arena, 0, sizeof(arena));

    test_demux_and_au_contract();
    test_track_independence();
    test_real_decode_into_guest_buffer();
    test_decoded_pixels();
    test_instance_isolation();
    test_destination_refusal();
    test_legacy_feed_take_path();

    if (failures) {
        fprintf(stderr, "psmf_media_selftest: %d checks, %d FAILURES\n", checks, failures);
        return 1;
    }
    printf("psmf_media_selftest: %d checks, 0 failures\n", checks);
    return 0;
}
