// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 the Nakagawa Recomp authors

/* Source-owned media selftest: synthetic PSMF -> bounded producer -> PES/access units ->
 * real H.264 backend -> guest-visible picture.
 *
 * Everything here is generated by this file, byte for byte.  The elementary stream is a
 * baseline-profile H.264 stream whose every macroblock is I_PCM, so the decoder's output is
 * exactly the luma/chroma values chosen in this file and the RGBA conversion can be checked
 * against known pixel values instead of a subjective picture comparison.  No retail media, no
 * extracted capture, no third-party bitstream is involved.
 *
 * The producer/demux assertions run on every platform.  The decode assertions run wherever a
 * real H.264 backend exists (the Windows Media Foundation backend, src/rt/h264_mf.c); on a
 * build without one they report SKIP, and the demux half still runs, so the fixture itself
 * always stays covered.
 *
 * Coverage that matters most:
 *   - AU formation across PES boundaries, with fragmented source reads;
 *   - timestamp normalization against the PSMF presentation base, including an AU whose PES
 *     carried no PTS (reported as "unknown", never invented);
 *   - a real decoded picture in the guest display buffer, checked pixel by pixel;
 *   - the end-of-stream contract: the last picture of the stream is released and decoded
 *     (regression: before sr_h264_frame() closed the trailing chunk at EOS the final picture
 *     of every stream was silently dropped), exactly once, and a fresh decoder instance never
 *     exposes a previous stream's trailing picture;
 *   - the legacy mpeg.c consumption path (sr_h264_feed + sr_h264_au_take + sr_h264_frame) is
 *     unchanged by that EOS release.
 */

#include "psmf_producer.h"
#include "sr_h264.h"
#include "mpeg.c"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int checks, failures;
#define CHECK(x, text) do { checks++; if (!(x)) { failures++; fprintf(stderr, "FAIL: %s\n", text); } } while (0)
/* Bounded diagnostics for the acceptance runs: SR_PSMF_MEDIA_DEBUG=1 prints the counters that
 * say where a media chain stopped, without making the normal run noisy. */
#define MEDIA_DEBUG(...) do { if (getenv("SR_PSMF_MEDIA_DEBUG")) fprintf(stderr, __VA_ARGS__); } while (0)

/* ---- guest arena ------------------------------------------------------------------------ */
/* sr_h264_frame() writes into guest memory through SR_HOST(), so the selftest owns a flat
 * arena and a no-op VRAM-dirty sink, exactly as the runtime stubs them. */
uint8_t *g_mem = NULL;
CpuState *s_cpu;
int g_sr_heap_watch;
int g_sr_metadata_watch;
int g_hle_depth;
int g_sr_last_writer_enabled;
uint32_t g_sr_store_context_pc;
unsigned g_sr_store_context_limit;
unsigned g_sr_store_context_count;
int g_sr_store_context_mem_gpr;
uint32_t g_sr_store_context_mem_offset;
unsigned g_sr_store_context_mem_words;
uint32_t g_sr_mem_watch_context_pc;
unsigned g_sr_mem_watch_context_limit;
unsigned g_sr_mem_watch_context_count;
int g_sr_mem_watch_context_fpr;
uint32_t g_sr_mem_watch_context_fpr_value;
SrMemWatch g_sr_mem_watches[SR_MAX_MEM_WATCHES];
int g_sr_mem_watch_count;
atomic_int_least32_t sr_timeslice;
void sr_oor(uint32_t addr, uint32_t value, int store) { (void)addr; (void)value; (void)store; }
uint32_t sr_get_ge_status(void) { return 0; }
void sr_note_mem_write(uint32_t addr, uint32_t width, uint32_t value, uint32_t pc) { (void)addr; (void)width; (void)value; (void)pc; }
void sr_heap_note_write(uint32_t addr, uint32_t width, uint32_t value, uint32_t pc) { (void)addr; (void)width; (void)value; (void)pc; }
uint32_t sched_current_uid(void) { return 0; }
int sr_nested_frame_acquire(uint32_t owner, uint32_t *sp, int *handle) { (void)owner; (void)sp; (void)handle; return 0; }
int sr_nested_frame_release(int handle) { (void)handle; return 0; }
void dispatch(CpuState *s, uint32_t target) { (void)s; (void)target; }
RecompFn sr_lookup(uint32_t addr) { (void)addr; return NULL; }
void sr_gpu_vram_dirty(uint32_t addr, uint32_t bytes) { (void)addr; (void)bytes; }

#define ARENA_BYTES (8u * 1024u * 1024u)
#define GUEST_BUF   (0x08000000u + 0x00400000u)   /* 4 MiB into guest RAM */

/* ---- source-authored H.264 elementary stream -------------------------------------------- */

typedef struct {
    uint8_t *d; uint32_t cap, n;
    uint32_t acc; int bits;
    int overflow;
} BitW;

static void bw_byte(BitW *w, uint8_t b) {
    if (w->n >= w->cap) { w->overflow = 1; return; }
    w->d[w->n++] = b;
}
static void bw_bit(BitW *w, int b) {
    w->acc = (w->acc << 1) | (uint32_t)(b & 1);
    if (++w->bits == 8) { bw_byte(w, (uint8_t)w->acc); w->acc = 0; w->bits = 0; }
}
static void bw_u(BitW *w, uint32_t v, int n) {
    for (int i = n - 1; i >= 0; i--) bw_bit(w, (int)((v >> (unsigned)i) & 1u));
}
static void bw_ue(BitW *w, uint32_t v) {
    uint32_t x = v + 1u;
    int n = 0;
    for (uint32_t t = x; t; t >>= 1) n++;
    for (int i = 0; i < n - 1; i++) bw_bit(w, 0);
    bw_u(w, x, n);
}
static void bw_pad(BitW *w) { while (w->bits) bw_bit(w, 0); }
static void bw_trailing(BitW *w) { bw_bit(w, 1); bw_pad(w); }
/* Byte run inside a bit stream (I_PCM macroblock payload); pads partial bits with zeros,
 * which is exactly the pcm_alignment_zero_bit the syntax defines. */
static void bw_raw(BitW *w, const uint8_t *p, uint32_t n) {
    bw_pad(w);
    if (w->n + n > w->cap) { w->overflow = 1; return; }
    memcpy(w->d + w->n, p, n);
    w->n += n;
}

typedef struct { uint8_t *d; uint32_t cap, n; int overflow; } ByteOut;
static void bo_raw(ByteOut *o, const uint8_t *p, uint32_t n) {
    if (o->n + n > o->cap) { o->overflow = 1; return; }
    memcpy(o->d + o->n, p, n);
    o->n += n;
}
static void bo_byte(ByteOut *o, uint8_t b) { bo_raw(o, &b, 1); }
/* Annex-B NAL unit: start code, header, then the RBSP with emulation prevention. */
static void emit_nal(ByteOut *o, uint8_t hdr, const BitW *rbsp) {
    static const uint8_t start_code[3] = { 0, 0, 1 };
    bo_raw(o, start_code, 3u);
    bo_byte(o, hdr);
    int zeros = 0;
    for (uint32_t i = 0; i < rbsp->n; i++) {
        uint8_t b = rbsp->d[i];
        if (zeros >= 2 && b <= 3u) { bo_byte(o, 3u); zeros = 0; }
        bo_byte(o, b);
        zeros = (b == 0) ? zeros + 1 : 0;
    }
}

#define FIX_W_MBS 4
#define FIX_H_MBS 4
#define FIX_PICTURES 3

static void write_sps_ex(BitW *w, uint32_t w_mbs, uint32_t h_mbs) {
    bw_u(w, 66u, 8);          /* profile_idc: baseline */
    bw_u(w, 0u, 8);           /* constraint set flags  */
    bw_u(w, 30u, 8);          /* level_idc 3.0         */
    bw_ue(w, 0u);             /* seq_parameter_set_id */
    bw_ue(w, 0u);             /* log2_max_frame_num_minus4 */
    bw_ue(w, 0u);             /* pic_order_cnt_type */
    bw_ue(w, 0u);             /* log2_max_pic_order_cnt_lsb_minus4 */
    bw_ue(w, 1u);             /* max_num_ref_frames */
    bw_bit(w, 0);             /* gaps_in_frame_num_value_allowed_flag */
    bw_ue(w, w_mbs - 1u);     /* pic_width_in_mbs_minus1 */
    bw_ue(w, h_mbs - 1u);     /* pic_height_in_map_units_minus1 */
    bw_bit(w, 1);             /* frame_mbs_only_flag */
    bw_bit(w, 1);             /* direct_8x8_inference_flag */
    bw_bit(w, 0);             /* frame_cropping_flag */
    bw_bit(w, 0);             /* vui_parameters_present_flag */
    bw_trailing(w);
}

static void write_pps(BitW *w) {
    bw_ue(w, 0u);             /* pic_parameter_set_id */
    bw_ue(w, 0u);             /* seq_parameter_set_id */
    bw_bit(w, 0);             /* entropy_coding_mode_flag: CAVLC */
    bw_bit(w, 0);             /* bottom_field_pic_order_in_frame_present_flag */
    bw_ue(w, 0u);             /* num_slice_groups_minus1 */
    bw_ue(w, 0u);             /* num_ref_idx_l0_default_active_minus1 */
    bw_ue(w, 0u);             /* num_ref_idx_l1_default_active_minus1 */
    bw_bit(w, 0);             /* weighted_pred_flag */
    bw_u(w, 0u, 2);           /* weighted_bipred_idc */
    bw_ue(w, 0u);             /* pic_init_qp_minus26 (se(0)) */
    bw_ue(w, 0u);             /* pic_init_qs_minus26 (se(0)) */
    bw_ue(w, 0u);             /* chroma_qp_index_offset (se(0)) */
    bw_bit(w, 0);             /* deblocking_filter_control_present_flag */
    bw_bit(w, 0);             /* constrained_intra_pred_flag */
    bw_bit(w, 0);             /* redundant_pic_cnt_present_flag */
    bw_trailing(w);
}

/* One IDR picture, every macroblock I_PCM, so luma and chroma are exactly (y, cb, cr). */
static void write_idr_ex(BitW *w, int picture, uint32_t w_mbs, uint32_t h_mbs, uint8_t y, uint8_t cb, uint8_t cr) {
    uint8_t pcm[256 + 64 + 64];
    memset(pcm, y, 256u);
    memset(pcm + 256, cb, 64u);
    memset(pcm + 320, cr, 64u);
    bw_ue(w, 0u);                       /* first_mb_in_slice */
    bw_ue(w, 2u);                       /* slice_type: I */
    bw_ue(w, 0u);                       /* pic_parameter_set_id */
    bw_u(w, (uint32_t)(picture % 16), 4);   /* frame_num */
    bw_ue(w, (uint32_t)(picture % 2));      /* idr_pic_id */
    bw_u(w, 0u, 4);                     /* pic_order_cnt_lsb */
    bw_bit(w, 0);                       /* dec_ref_pic_marking.no_output_of_prior_pics_flag */
    bw_bit(w, 0);                       /* dec_ref_pic_marking.long_term_reference_flag */
    bw_ue(w, 0u);                       /* slice_qp_delta (se(0)) */
    for (uint32_t mb = 0; mb < w_mbs * h_mbs; mb++) {
        bw_ue(w, 25u);                  /* mb_type: I_PCM */
        bw_raw(w, pcm, (uint32_t)sizeof(pcm));
    }
    bw_trailing(w);
}

/* Decoded plane values per picture.  Chosen so the BT.601 limited-range conversion lands on
 * values that are stable, non-clipping, and easy to state as a literal expectation. */
static const uint8_t k_y[FIX_PICTURES]  = { 200u, 128u, 128u };
static const uint8_t k_cb[FIX_PICTURES] = {  90u, 128u, 160u };
static const uint8_t k_cr[FIX_PICTURES] = { 160u, 128u,  96u };

/* One access unit = access-unit delimiter + (on the first picture) parameter sets + IDR. */
static void build_au_ex(int picture, uint32_t w_mbs, uint32_t h_mbs,
                        uint8_t y, uint8_t cb, uint8_t cr, ByteOut *out) {
    static const uint8_t aud[5] = { 0, 0, 1, 0x09, 0x10 };
    BitW w;
    uint8_t scratch[8192];
    bo_raw(out, aud, sizeof(aud));
    if (picture == 0) {
        w.d = scratch; w.cap = sizeof(scratch); w.n = 0; w.acc = 0; w.bits = 0; w.overflow = 0;
        write_sps_ex(&w, w_mbs, h_mbs);
        CHECK(!w.overflow, "SPS fits the scratch buffer");
        emit_nal(out, 0x67, &w);
        w.n = 0; w.acc = 0; w.bits = 0; w.overflow = 0;
        write_pps(&w);
        CHECK(!w.overflow, "PPS fits the scratch buffer");
        emit_nal(out, 0x68, &w);
    }
    w.d = scratch; w.cap = sizeof(scratch); w.n = 0; w.acc = 0; w.bits = 0; w.overflow = 0;
    write_idr_ex(&w, picture, w_mbs, h_mbs, y, cb, cr);
    CHECK(!w.overflow, "IDR picture fits the scratch buffer");
    emit_nal(out, 0x65, &w);
}

/* Build the annex-B elementary stream and report each access unit's byte range, which is what
 * the producer must reproduce exactly. */
static int build_stream_ex(uint8_t *dst, uint32_t cap, uint32_t w_mbs, uint32_t h_mbs,
                           const uint8_t y[FIX_PICTURES], const uint8_t cb[FIX_PICTURES],
                           const uint8_t cr[FIX_PICTURES],
                           uint32_t au_off[FIX_PICTURES], uint32_t au_len[FIX_PICTURES],
                           uint32_t *total) {
    ByteOut o;
    o.d = dst; o.cap = cap; o.n = 0; o.overflow = 0;
    for (int i = 0; i < FIX_PICTURES; i++) {
        au_off[i] = o.n;
        build_au_ex(i, w_mbs, h_mbs, y[i], cb[i], cr[i], &o);
        au_len[i] = o.n - au_off[i];
    }
    *total = o.n;
    return !o.overflow;
}

static int build_stream(uint8_t *dst, uint32_t cap, uint32_t au_off[FIX_PICTURES],
                        uint32_t au_len[FIX_PICTURES], uint32_t *total) {
    return build_stream_ex(dst, cap, FIX_W_MBS, FIX_H_MBS, k_y, k_cb, k_cr, au_off, au_len, total);
}

/* ---- synthetic PSMF container ------------------------------------------------------------ */

typedef struct { uint8_t *data; uint32_t size; uint32_t max_chunk; int fail; } MemSource;

static int mem_read(void *opaque, uint64_t off, void *dst, uint32_t cap, uint32_t *got) {
    MemSource *m = (MemSource *)opaque;
    if (!m || !dst || !got || off > m->size) { if (got) *got = 0; return SR_PSMF_SOURCE_ERROR; }
    if (m->fail) { *got = 0; return SR_PSMF_SOURCE_ERROR; }
    if (off == m->size) { *got = 0; return SR_PSMF_SOURCE_EOF; }
    uint32_t n = m->size - (uint32_t)off;
    if (n > cap) n = cap;
    if (m->max_chunk && n > m->max_chunk) n = m->max_chunk;
    memcpy(dst, m->data + (uint32_t)off, n);
    *got = n;
    return SR_PSMF_SOURCE_DATA;
}

typedef struct { uint8_t *d; uint32_t at, cap; int overflow; } Buf;
static void put(Buf *b, const uint8_t *p, uint32_t n) {
    if (b->at + n > b->cap) { b->overflow = 1; return; }
    memcpy(b->d + b->at, p, n);
    b->at += n;
}
static void be32_at(uint8_t *p, uint32_t v) {
    p[0] = (uint8_t)(v >> 24); p[1] = (uint8_t)(v >> 16); p[2] = (uint8_t)(v >> 8); p[3] = (uint8_t)v;
}
static void put_pts(uint8_t *p, int64_t v) {
    uint64_t x = (uint64_t)v;
    p[0] = (uint8_t)(0x21u | (((x >> 30) & 7u) << 1) | 1u);
    p[1] = (uint8_t)(x >> 22);
    p[2] = (uint8_t)((((x >> 15) & 0x7fu) << 1) | 1u);
    p[3] = (uint8_t)(x >> 7);
    p[4] = (uint8_t)(((x & 0x7fu) << 1) | 1u);
}
/* One MPEG-PS packet: pack header, then a PES packet with a single video payload slice.
 * The '10' marker in the first flags byte is mandatory even on a packet that carries no
 * presentation time; the second flags byte states which timestamps follow, and the
 * optional-header length is what bounds them.  All three are written from `has_pts` here,
 * so a packet that claims a time is one whose declared header actually holds it. */
static void add_video_pes_sid(Buf *b, uint8_t sid, int has_pts, int64_t pts, const uint8_t *payload, uint32_t len) {
    static const uint8_t pack[14] = { 0,0,1,0xba, 0x44,0,4,0,4,1,0,0,1,0 };
    uint32_t opt = has_pts ? 5u : 0u;
    uint32_t total = 3u + opt + len;
    uint8_t hdr[9];
    put(b, pack, sizeof(pack));
    hdr[0]=0; hdr[1]=0; hdr[2]=1; hdr[3]=sid;
    hdr[4]=(uint8_t)(total >> 8); hdr[5]=(uint8_t)total;
    hdr[6]=0x80u; hdr[7]=(uint8_t)(has_pts ? 0x80u : 0x00u); hdr[8]=(uint8_t)opt;
    put(b, hdr, sizeof(hdr));
    if (has_pts) { uint8_t p[5]; put_pts(p, pts); put(b, p, sizeof(p)); }
    put(b, payload, len);
}

static void add_video_pes(Buf *b, int has_pts, int64_t pts, const uint8_t *payload, uint32_t len) {
    add_video_pes_sid(b, 0xe0u, has_pts, pts, payload, len);
}

/* Audio access unit: private-stream-1 sub-header + one self-delimiting ATRAC frame. */
static void add_audio_pes_sub(Buf *b, uint8_t sub_id, int has_pts, int64_t pts, const uint8_t *frame, uint32_t len) {
    static const uint8_t pack[14] = { 0,0,1,0xba, 0x44,0,4,0,4,1,0,0,1,0 };
    uint32_t opt = has_pts ? 5u : 0u;
    uint8_t prefix[4] = { sub_id, 0x00, 0x00, 0x00 };
    uint32_t total = 3u + opt + 4u + len;
    uint8_t hdr[9];
    put(b, pack, sizeof(pack));
    hdr[0]=0; hdr[1]=0; hdr[2]=1; hdr[3]=0xbd;
    hdr[4]=(uint8_t)(total >> 8); hdr[5]=(uint8_t)total;
    hdr[6]=0x80u; hdr[7]=(uint8_t)(has_pts ? 0x80u : 0x00u); hdr[8]=(uint8_t)opt;
    put(b, hdr, sizeof(hdr));
    if (has_pts) { uint8_t p[5]; put_pts(p, pts); put(b, p, sizeof(p)); }
    put(b, prefix, sizeof(prefix));
    put(b, frame, len);
}

static void add_audio_pes(Buf *b, const uint8_t *frame, uint32_t len) {
    add_audio_pes_sub(b, 0x00u, 0, 0, frame, len);
}
/* One self-delimiting ATRAC frame (8-byte header + data); the size field is
 * ((code1 & 3) << 8 | code2 * 8) + 0x10 total bytes. */
static uint32_t make_audio_frame(uint8_t *dst, uint32_t cap, uint8_t code1, uint8_t code2,
                                 uint8_t fill) {
    uint32_t total = (uint32_t)(((code1 & 0x03u) << 8) | ((uint32_t)code2 * 8u)) + 0x10u;
    if (total > cap) return 0;
    memset(dst, fill, total);
    dst[0] = 0x0f; dst[1] = 0xd0; dst[2] = code1; dst[3] = code2;
    dst[4] = dst[5] = dst[6] = dst[7] = 0;
    return total;
}

/* PSMF presentation base and per-picture PES times.  Picture 2 deliberately carries no PTS,
 * which is the normal case in a PSP movie and the case a consumer must extrapolate rather
 * than invent. */
#define FIX_BASE      90000
#define FIX_PTS_STEP  3003
static const int k_has_pts[FIX_PICTURES] = { 1, 1, 0 };

/* ---- fixture self-validation ------------------------------------------------------------ */
/* Building this fixture wrongly has twice produced a failure that looked like a demux or
 * decoder defect: a NAL emitted without its start code, and a PES header written without the
 * mandatory '10' marker bits.  Both are structural, so the fixture now checks its own output
 * before any test reads it -- a malformed fixture fails here, as a fixture problem, instead of
 * being diagnosed from the pipeline's behaviour. */
static void mp4_picture_marks(const uint8_t *au, uint32_t n, int picture);

static uint32_t pes_count(const uint8_t *s, uint32_t n) {
    uint32_t at = 2048u;              /* the stream begins after the PSMF header */
    uint32_t packets = 0;
    while (at + 6u <= n) {
        CHECK(memcmp(s + at, "\0\0\1\xba", 4u) == 0, "every packet is preceded by a pack header");
        at += 14u;
        if (at + 6u > n) break;
        CHECK(s[at] == 0u && s[at + 1] == 0u && s[at + 2] == 1u, "PES start-code prefix is 00 00 01");
        uint8_t id = s[at + 3];
        CHECK(id == 0xbdu || (id & 0xe0u) == 0xe0u, "PES stream id is a video or private stream");
        CHECK((s[at + 6] & 0xc0u) == 0x80u, "PES marker byte carries the mandatory '10' bits");
        uint32_t ts_flags = ((uint32_t)s[at + 7] >> 6) & 0x3u;
        uint32_t opt = s[at + 8];
        CHECK(opt == 0u || opt == 5u, "optional PES header is absent or exactly one PTS field");
        CHECK(ts_flags == (opt ? 2u : 0u),
              "PTS/DTS flags state exactly the timestamp fields the declared header holds");
        if (opt == 5u) {
            CHECK((s[at + 9] & 0xf0u) == 0x20u, "PTS field carries the '0010' prefix");
            CHECK((s[at + 9] & 1u) != 0u && (s[at + 11] & 1u) != 0u && (s[at + 13] & 1u) != 0u,
                  "PTS field carries all three marker bits");
        }
        uint32_t declared = ((uint32_t)s[at + 4] << 8) | s[at + 5];
        CHECK(declared >= 3u + opt, "declared PES length covers its own header fields");
        uint32_t span = 6u + declared;      /* start code + id + length, then the declared body */
        CHECK(at + span <= n, "declared PES length stays inside the container");
        at += span;
        packets++;
    }
    CHECK(at == n, "the packet walk consumes the container exactly, with no trailing bytes");
    return packets;
}

/* Every picture's elementary bytes must be a real Annex-B access unit: a leading access-unit
 * delimiter, and inside the stream the parameter sets before the first slice.  The scan is
 * safe as a literal search because emit_nal() escapes emulation sequences, so a NAL never
 * contains a byte pattern that could be mistaken for a start code. */
static void check_es_wellformed(const uint8_t *es, uint32_t n, const uint32_t *au_off,
                               const uint32_t *au_len) {
    int sps = 0, pps = 0, idr = 0, aud = 0, slices_before_pps = 0;
    for (uint32_t i = 0; i + 3u < n; i++) {
        if (es[i] != 0u || es[i + 1] != 0u || es[i + 2] != 1u) continue;
        uint8_t hdr = es[i + 3];
        CHECK((hdr & 0x80u) == 0u, "every start code is followed by a NAL header, not payload");
        switch (hdr & 0x1fu) {
            case 9:  aud++; break;
            case 7:  sps++; break;
            case 8:  pps++; break;
            case 5:  if (!pps) slices_before_pps++; idr++; break;
            default: break;
        }
    }
    CHECK(sps == 1, "the elementary stream carries exactly one SPS");
    CHECK(pps == 1, "the elementary stream carries exactly one PPS");
    CHECK(aud == FIX_PICTURES, "one access-unit delimiter per picture");
    CHECK(idr == FIX_PICTURES, "one IDR slice per picture");
    CHECK(slices_before_pps == 0, "the parameter sets precede the first slice");
    for (int i = 0; i < FIX_PICTURES; i++) {
        CHECK(au_len[i] > 8u, "a picture access unit is longer than its header");
        CHECK(au_off[i] + au_len[i] <= n, "a picture access unit stays inside the stream");
        mp4_picture_marks(es + au_off[i], au_len[i], i);
    }
}

/* Each picture must start with its delimiter and contain an IDR slice carrying the picture's
 * own marker, so a fixture that silently emitted the wrong picture cannot pass a test that
 * only counts bytes. */
static void mp4_picture_marks(const uint8_t *au, uint32_t n, int picture) {
    CHECK(n >= 5u && au[0] == 0u && au[1] == 0u && au[2] == 1u && (au[3] & 0x1fu) == 9u,
          "a picture access unit begins with an access-unit delimiter");
    int idr = 0;
    for (uint32_t i = 0; i + 4u < n; i++) {
        if (au[i] == 0u && au[i + 1] == 0u && au[i + 2] == 1u && (au[i + 3] & 0x1fu) == 5u) idr++;
    }
    CHECK(idr == 1, "a picture access unit carries exactly one IDR slice");
    (void)picture;
}

/* Assemble the whole container: a validated PSMF header, then the video elementary stream cut
 * into two PES packets per picture (so access units always straddle packet boundaries) with an
 * audio track interleaved between them. */
static uint8_t *build_psmf(uint32_t *size_out, uint32_t au_off[FIX_PICTURES],
                           uint32_t au_len[FIX_PICTURES]) {
    uint8_t es[65536];
    uint32_t es_len = 0;
    CHECK(build_stream(es, sizeof(es), au_off, au_len, &es_len), "generated H.264 stream fits");
    Buf b;
    (void)es_len;
    b.cap = 2048u + es_len * 2u + 4096u;
    b.d = (uint8_t *)calloc(1, b.cap);
    b.at = 2048u;
    b.overflow = 0;
    if (!b.d) return NULL;
    b.d[0] = 'P'; b.d[1] = 'S'; b.d[2] = 'M'; b.d[3] = 'F';
    be32_at(b.d + 8, 2048u);
    uint8_t aframe[128];
    for (int i = 0; i < FIX_PICTURES; i++) {
        uint32_t half = au_len[i] / 2u;
        add_video_pes(&b, k_has_pts[i], FIX_BASE + (int64_t)i * FIX_PTS_STEP, es + au_off[i], half);
        add_video_pes(&b, 0, 0, es + au_off[i] + half, au_len[i] - half);
        if (i == 0) {
            uint32_t n = make_audio_frame(aframe, sizeof(aframe), 0x28, 6, 0xa5);
            add_audio_pes(&b, aframe, n);
        }
        if (i == 1) {
            uint8_t junk[24];
            memset(junk, 0xb7, sizeof(junk));       /* no frame header: the producer resyncs */
            add_audio_pes(&b, junk, sizeof(junk));
        }
    }
    /* Trailing audio frame, so the last thing in the stream is not part of the video track. */
    {
        uint32_t n = make_audio_frame(aframe, sizeof(aframe), 0x28, 7, 0x5a);
        add_audio_pes(&b, aframe, n);
    }
    be32_at(b.d + 12, b.at - 2048u);
    CHECK(!b.overflow, "synthetic PSMF container fits its buffer");
    /* The fixture proves its own structure before any test reads it. */
    CHECK(pes_count(b.d, b.at) >= (uint32_t)(FIX_PICTURES * 2 + 2),
          "the container holds every packet the builder wrote");
    check_es_wellformed(es, es_len, au_off, au_len);
    *size_out = b.at;
    return b.d;
}

/* ---- tests ------------------------------------------------------------------------------ */

static SrPsmfProducer *open_fixture(uint8_t *data, uint32_t size, MemSource *mem,
                                    uint32_t chunk) {
    mem->data = data; mem->size = size; mem->max_chunk = chunk; mem->fail = 0;
    SrPsmfSource source;
    source.read = mem_read;
    source.opaque = mem;
    source.size = size;
    return sr_psmf_producer_open(&source, FIX_BASE);
}

/* The producer must reproduce, byte for byte, the access units the fixture generator wrote,
 * while reading the container in fragments that never align with a packet boundary. */
static void test_demux_and_au_contract(void) {
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    CHECK(bytes != NULL, "fixture allocated");
    if (!bytes) return;
    /* The generator is deterministic, so the expected elementary stream can be rebuilt here
     * and compared against what the producer hands back. */
    static uint8_t es[65536];
    uint32_t es_total = 0;
    CHECK(build_stream(es, sizeof(es), au_off, au_len, &es_total), "expected stream rebuilds");

    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 7u);   /* 7-byte reads */
    CHECK(p != NULL, "producer opens the synthetic PSMF");
    if (!p) { free(bytes); return; }

    uint32_t got_sizes[FIX_PICTURES + 2];
    uint32_t got_pts[FIX_PICTURES + 2];
    int got_has_pts[FIX_PICTURES + 2];
    uint8_t *got_bytes[FIX_PICTURES + 2];
    int n = 0;
    for (int guard = 0; guard < 4096 && !sr_psmf_producer_eof(p); guard++) {
        sr_psmf_producer_pump(p, 1);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            CHECK(n < FIX_PICTURES + 2, "no more video access units than pictures were written");
            if (n < FIX_PICTURES + 2) {
                got_sizes[n] = au.size;
                got_pts[n] = (uint32_t)au.pts;
                got_has_pts[n] = au.has_pts != 0;
                got_bytes[n] = au.data;
                au.data = NULL;
            }
            sr_psmf_au_release(&au);
            n++;
        }
    }
    CHECK(n == FIX_PICTURES, "one video access unit per authored picture");
    for (int i = 0; i < FIX_PICTURES && i < n; i++) {
        CHECK(got_sizes[i] == au_len[i], "access unit size matches the authored picture");
        if (got_sizes[i] == au_len[i])
            CHECK(memcmp(got_bytes[i], es + au_off[i], au_len[i]) == 0,
                  "access unit bytes match the authored elementary stream");
        CHECK(got_has_pts[i] == k_has_pts[i],
              "PES presentation-time presence survives AU formation");
        if (k_has_pts[i])
            CHECK(got_pts[i] == (uint32_t)(i * FIX_PTS_STEP),
                  "timestamp normalized against the PSMF presentation base");
        if (!k_has_pts[i])
            CHECK(!got_has_pts[i], "a packet with no PTS is reported as unknown, not invented");
        free(got_bytes[i]);
    }

    SrPsmfProducerStats st;
    sr_psmf_producer_stats(p, &st);
    MEDIA_DEBUG("demux: bytes=%llu packs=%llu pes=%llu vpes=%llu apes=%llu vau=%llu aau=%llu"
                " pf=%llu sf=%llu fail_at=%llu failed=%d eof=%d first=%lld last=%lld\n",
                (unsigned long long)st.bytes_read, (unsigned long long)st.packs,
                (unsigned long long)st.pes_packets, (unsigned long long)st.video_pes,
                (unsigned long long)st.audio_pes, (unsigned long long)st.video_aus,
                (unsigned long long)st.audio_aus, (unsigned long long)st.parser_failures,
                (unsigned long long)st.source_failures, (unsigned long long)st.fail_offset,
                st.failed, st.eof, (long long)st.first_pts, (long long)st.last_pts);
    CHECK(st.video_aus == FIX_PICTURES, "producer counts every picture");
    CHECK(st.audio_aus >= 1, "the interleaved audio track is demuxed independently");
    CHECK(st.source_failures == 0, "fragmented reads never report a source failure");
    CHECK(st.failed == 0, "no parser failure on well-formed input");
    CHECK(st.eof, "the producer reaches end of file");
    sr_psmf_producer_close(p);
    free(bytes);
}

/* One decoder, the producer's own access units, the guest display buffer. */
static void test_real_decode_into_guest_buffer(void) {
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    if (!bytes) { CHECK(0, "fixture allocated"); return; }
    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 512u);
    CHECK(p != NULL, "producer opens for the decode test");

    int dec = sr_h264_create();
    if (dec < 0 || !p) {
        fprintf(stderr, "SKIP: no H.264 backend on this build (demux contract still verified)\n");
        sr_psmf_producer_close(p);
        free(bytes);
        return;
    }

    /* Feed exactly like the guest player: every produced access unit goes to the decoder, and
     * frames are pulled while the stream is still being fed (eos = 0). */
    int frames_before_eos = 0, frames_after_eos = 0, aus = 0;
    for (int guard = 0; guard < 65536; guard++) {
        sr_psmf_producer_pump(p, 4);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            sr_h264_submit_au(dec, au.data, au.size);
            sr_psmf_au_release(&au);
            aus++;
        }
        int r = sr_h264_frame(dec, 0, GUEST_BUF, 64, 3);
        CHECK(r >= 0, "decoding a fed access unit never fails");
        if (r > 0) frames_before_eos++;
        if (sr_psmf_producer_eof(p) && r == 0) break;
    }
    MEDIA_DEBUG("decode: aus=%d before_eos=%d after_eos=%d\n", aus, frames_before_eos, frames_after_eos);
    CHECK(aus == FIX_PICTURES, "every picture reached the decoder");
    CHECK(frames_before_eos >= 1, "a real decoder produced a picture before end of stream");

    /* Drain: the last picture has no following delimiter to close it, so only end-of-stream
     * can release it.  Before that release existed this loop produced nothing. */
    for (int i = 0; i < 16; i++) {
        int r = sr_h264_frame(dec, 1, GUEST_BUF, 64, 3);
        CHECK(r >= 0, "end-of-stream drain never fails");
        if (r <= 0) break;
        frames_after_eos++;
    }
    CHECK(frames_before_eos + frames_after_eos == FIX_PICTURES,
          "the stream yields exactly one picture per authored picture (final picture released at EOS)");
    CHECK(frames_after_eos >= 1, "the trailing picture is released by the end-of-stream drain");

    /* Repeated end-of-stream must not duplicate output. */
    int extra = 0;
    for (int i = 0; i < 8; i++) if (sr_h264_frame(dec, 1, GUEST_BUF, 64, 3) > 0) extra++;
    CHECK(extra == 0, "a drained decoder produces no further pictures");
    sr_h264_destroy(dec);
    sr_psmf_producer_close(p);
    free(bytes);
}

/* Decoded pixels are exactly the authored YCbCr, converted with BT.601 limited range. */
static void test_decoded_pixels(void) {
    static const uint8_t expect[FIX_PICTURES][3] = {
        { 255u, 203u, 138u },     /* (200,  90, 160) */
        { 130u, 130u, 130u },     /* (128, 128, 128) */
        {  79u, 144u, 195u },     /* (128, 160,  96) */
    };
    int dec = sr_h264_create();
    if (dec < 0) {
        fprintf(stderr, "SKIP: pixel assertions need a real H.264 backend\n");
        return;
    }
    uint8_t host[64 * 272 * 4];
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    if (!bytes) { CHECK(0, "fixture allocated"); sr_h264_destroy(dec); return; }
    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 2048u);
    if (!p) { CHECK(0, "producer opens"); free(bytes); sr_h264_destroy(dec); return; }

    int seen = 0;
    for (int guard = 0; guard < 65536 && seen < FIX_PICTURES; guard++) {
        SrPsmfAu au;
        sr_psmf_producer_pump(p, 2);
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            sr_h264_submit_au(dec, au.data, au.size);
            sr_psmf_au_release(&au);
        }
        int eos = sr_psmf_producer_eof(p);
        while (seen < FIX_PICTURES) {
            int r = sr_h264_frame_host(dec, eos, host, 64, 64 * 4);
            if (r < 0) { CHECK(0, "host decode failed"); break; }
            if (r == 0) break;
            const uint8_t *want = expect[seen];
            int bad = 0;
            for (int y = 0; y < 64 && !bad; y++)
                for (int x = 0; x < 64; x++) {
                    const uint8_t *px = host + ((size_t)y * 64u + (size_t)x) * 4u;
                    if (px[0] != want[0] || px[1] != want[1] || px[2] != want[2] || px[3] != 0xFFu) {
                        bad = 1; break;
                    }
                }
            CHECK(!bad, "every decoded pixel matches the authored picture");
            seen++;
        }
    }
    CHECK(seen == FIX_PICTURES, "the decoder delivered every authored picture");
    sr_psmf_producer_close(p);
    free(bytes);
    sr_h264_destroy(dec);
}

/* A fresh decoder instance must never expose the previous stream's trailing picture. */
static void test_instance_isolation(void) {
    int dec = sr_h264_create();
    if (dec < 0) { fprintf(stderr, "SKIP: instance isolation needs a real H.264 backend\n"); return; }
    /* Nothing was ever fed: end of stream on an empty instance reports "no picture". */
    CHECK(sr_h264_frame(dec, 1, GUEST_BUF, 64, 3) == 0, "an unfed decoder produces no picture");
    sr_h264_destroy(dec);

    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint8_t es[65536];
    uint32_t es_len = 0;
    if (!build_stream(es, sizeof(es), au_off, au_len, &es_len)) { CHECK(0, "stream builds"); return; }

    int first = sr_h264_create();
    CHECK(first >= 0, "decoder instance for the isolation test");
    if (first < 0) return;
    for (int i = 0; i < FIX_PICTURES; i++) sr_h264_submit_au(first, es + au_off[i], au_len[i]);
    int got = 0;
    for (int i = 0; i < 16; i++) {
        int r = sr_h264_frame(first, 1, GUEST_BUF, 64, 3);
        if (r <= 0) break;
        got++;
    }
    MEDIA_DEBUG("isolation: first instance pictures=%d\n", got);
    CHECK(got >= 1, "the first instance decodes");
    sr_h264_destroy(first);

    int second = sr_h264_create();
    CHECK(second >= 0, "decoder instance after destroy");
    if (second < 0) return;
    int stale = 0;
    for (int i = 0; i < 8; i++) if (sr_h264_frame(second, 1, GUEST_BUF, 64, 3) > 0) stale++;
    CHECK(stale == 0, "a restarted decoder exposes no picture from the previous stream");
    sr_h264_destroy(second);
}

/* An unusable destination must not be reported as a produced frame, and must not poison the
 * decoder for the pictures that follow. */
static void test_destination_refusal(void) {
    int dec = sr_h264_create();
    if (dec < 0) { fprintf(stderr, "SKIP: destination checks need a real H.264 backend\n"); return; }
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint8_t es[65536];
    uint32_t es_len = 0;
    if (!build_stream(es, sizeof(es), au_off, au_len, &es_len)) { CHECK(0, "stream builds"); return; }

    /* Out-of-range guest buffer: the picture exists but cannot be delivered. */
    sr_h264_submit_au(dec, es + au_off[0], au_len[0]);
    sr_h264_submit_au(dec, es + au_off[1], au_len[1]);
    int r = sr_h264_frame(dec, 0, 0x0FFFFFF0u, 64, 3);
    CHECK(r <= 0, "an unusable destination is not reported as a produced frame");

    /* The decoder is still usable for the next picture. */
    int ok = 0;
    for (int i = 0; i < 8; i++) if (sr_h264_frame(dec, 1, GUEST_BUF, 64, 3) > 0) { ok = 1; break; }
    CHECK(ok, "a refused destination does not poison the decoder");
    sr_h264_destroy(dec);
}

/* The sceMpeg consumption path (feed -> au_take -> frame) must be unchanged by the EOS
 * release: each taken access unit still yields exactly one picture, including the last. */
static void test_legacy_feed_take_path(void) {
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    if (!bytes) { CHECK(0, "fixture allocated"); return; }
    int dec = sr_h264_create();
    if (dec < 0) {
        fprintf(stderr, "SKIP: the mpeg.c consumption path needs a real H.264 backend\n");
        free(bytes);
        return;
    }
    sr_h264_feed(dec, bytes + 2048u, size - 2048u);
    int frames = 0, taken = 0;
    for (int guard = 0; guard < 64; guard++) {
        uint64_t consumed = 0;
        int64_t pts = 0;
        int took = sr_h264_au_take(dec, 0, &consumed, &pts);
        if (took > 0) taken++;
        for (int i = 0; i < 8; i++) {
            int r = sr_h264_frame(dec, 0, GUEST_BUF, 64, 3);
            if (r < 0) { CHECK(0, "legacy path decode failed"); break; }
            if (r == 0) break;
            frames++;
        }
        if (took <= 0) break;
    }
    uint64_t consumed = 0;
    if (sr_h264_au_take(dec, 1, &consumed, NULL) > 0) taken++;
    for (int i = 0; i < 16; i++) {
        int r = sr_h264_frame(dec, 1, GUEST_BUF, 64, 3);
        if (r < 0) { CHECK(0, "legacy path end-of-stream decode failed"); break; }
        if (r == 0) break;
        frames++;
    }
    MEDIA_DEBUG("legacy path: taken=%d frames=%d\n", taken, frames);
    CHECK(taken == FIX_PICTURES, "the demuxed stream hands out one access unit per picture");
    CHECK(frames == FIX_PICTURES, "each access unit yields exactly one decoded picture");
    sr_h264_destroy(dec);
    free(bytes);
}

static uint64_t demux_fuzz_state = 0x3194844345584D58ULL;

static uint64_t demux_fuzz_rand64(void) {
    uint64_t z = (demux_fuzz_state += 0x9E3779B97F4A7C15ULL);
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    return z ^ (z >> 31);
}

static void demux_fuzz_mutate(uint8_t *data, size_t size) {
    static const uint32_t values[] = {
        0, 1, 2, 3, 4, 8, 14, 16, 0x40, 0x80, 0xBD, 0xE0, 0xEF,
        0x7FFFu, 0x8000u, 0xFFFFu, 0x7FFFFFFFu, 0x80000000u, 0xFFFFFFFFu
    };
    unsigned operations = (unsigned)(demux_fuzz_rand64() % 8u) + 1u;
    for (unsigned op = 0; op < operations; op++) {
        unsigned kind = (unsigned)(demux_fuzz_rand64() % 5u);
        size_t index = (size_t)(demux_fuzz_rand64() % size);
        if (kind == 0) {
            data[index] ^= (uint8_t)(1u << (demux_fuzz_rand64() % 8u));
        } else if (kind == 1) {
            data[index] = (uint8_t)demux_fuzz_rand64();
        } else if (kind == 2 && index + 2u <= size) {
            uint16_t value = values[demux_fuzz_rand64() %
                                    (sizeof(values) / sizeof(values[0]))];
            data[index] = (uint8_t)value;
            data[index + 1] = (uint8_t)(value >> 8);
        } else if (kind == 3 && index + 4u <= size) {
            uint32_t value = values[demux_fuzz_rand64() %
                                    (sizeof(values) / sizeof(values[0]))];
            data[index] = (uint8_t)value;
            data[index + 1] = (uint8_t)(value >> 8);
            data[index + 2] = (uint8_t)(value >> 16);
            data[index + 3] = (uint8_t)(value >> 24);
        } else {
            size_t run = (size_t)(demux_fuzz_rand64() % 16u) + 1u;
            if (run > size - index) run = size - index;
            memset(data + index, (demux_fuzz_rand64() & 1u) ? 0u : 0xFFu, run);
        }
    }
}

static void test_legacy_demux_mutations(unsigned iterations) {
    if (iterations > 128u) iterations = 128u;
    demux_fuzz_state = 0x3194844345584D58ULL;
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    CHECK(bytes != NULL, "demux mutation fixture allocated");
    if (!bytes) return;
    uint8_t *mutated = (uint8_t *)malloc(size - 2048u);
    CHECK(mutated != NULL, "demux mutation buffer allocated");
    if (!mutated) { free(bytes); return; }
    unsigned attempted = 0;
    for (unsigned i = 0; i < iterations; i++) {
        memcpy(mutated, bytes + 2048u, size - 2048u);
        demux_fuzz_mutate(mutated, size - 2048u);
        int decoder = sr_h264_create();
        if (decoder < 0) {
            if (attempted == 0) fprintf(stderr, "SKIP: hostile legacy demux needs Media Foundation\n");
            break;
        }
        attempted++;
        sr_h264_feed(decoder, mutated, size - 2048u);
        for (unsigned take = 0; take < 32u; take++) {
            uint64_t consumed = 0;
            int64_t pts = 0;
            int rc = sr_h264_au_take(decoder, 0, &consumed, &pts);
            if (rc <= 0) break;
        }
        {
            uint64_t consumed = 0;
            int64_t pts = 0;
            (void)sr_h264_au_take(decoder, 1, &consumed, &pts);
        }
        (void)sr_h264_frame(decoder, 1, GUEST_BUF, 64, 3);
        sr_h264_destroy(decoder);
    }
    free(mutated);
    free(bytes);
    printf("Legacy MPEG-PS/H.264 mutation: %u iterations, %u executed, 0 crashes\n",
           iterations, attempted);
}

/* A malformed audio track must leave the video track alone. */
static void test_track_independence(void) {
    uint32_t au_off[FIX_PICTURES], au_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_psmf(&size, au_off, au_len);
    if (!bytes) { CHECK(0, "fixture allocated"); return; }
    /* Corrupt the audio payload bytes in place: the video elementary stream is untouched. */
    for (uint32_t i = 2048u; i + 6u < size; i++) {
        if (bytes[i] != 0 || bytes[i + 1] != 0 || bytes[i + 2] != 1 || bytes[i + 3] != 0xbd) continue;
        uint32_t len = ((uint32_t)bytes[i + 4] << 8) | bytes[i + 5];
        uint32_t payload = i + 9u + 4u;
        if (payload + 8u > size) break;
        memset(bytes + payload, 0xb7, 8u);      /* destroy the audio frame header */
        i += 9u + len;
    }
    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 1024u);
    CHECK(p != NULL, "producer opens a PSMF with a corrupt audio track");
    if (!p) { free(bytes); return; }
    int video = 0;
    for (int guard = 0; guard < 4096 && !sr_psmf_producer_eof(p); guard++) {
        sr_psmf_producer_pump(p, 2);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) { video++; sr_psmf_au_release(&au); }
    }
    CHECK(video == FIX_PICTURES, "a corrupt audio track cannot cost the video track its pictures");
    SrPsmfProducerStats st;
    sr_psmf_producer_stats(p, &st);
    CHECK(st.audio_resync_bytes > 0, "the corrupt audio bytes are counted, not silently trusted");
    sr_psmf_producer_close(p);
    free(bytes);
}

static uint8_t *build_multistream_psmf(uint32_t *size_out,
                                       uint32_t au0_off[FIX_PICTURES], uint32_t au0_len[FIX_PICTURES],
                                       uint32_t au1_off[FIX_PICTURES], uint32_t au1_len[FIX_PICTURES]) {
    uint8_t es0[65536], es1[65536];
    uint32_t es0_len = 0, es1_len = 0;
    CHECK(build_stream_ex(es0, sizeof(es0), 4, 4, k_y, k_cb, k_cr, au0_off, au0_len, &es0_len), "stream 0 builds");
    static const uint8_t k_y2[FIX_PICTURES]  = {  80u, 160u, 240u };
    static const uint8_t k_cb2[FIX_PICTURES] = { 100u, 128u, 140u };
    static const uint8_t k_cr2[FIX_PICTURES] = { 150u, 128u, 110u };
    CHECK(build_stream_ex(es1, sizeof(es1), 2, 2, k_y2, k_cb2, k_cr2, au1_off, au1_len, &es1_len), "stream 1 builds");

    Buf b;
    b.cap = 2048u + (es0_len + es1_len) * 2u + 8192u;
    b.d = (uint8_t *)calloc(1, b.cap);
    b.at = 2048u;
    b.overflow = 0;
    if (!b.d) return NULL;
    b.d[0] = 'P'; b.d[1] = 'S'; b.d[2] = 'M'; b.d[3] = 'F';
    be32_at(b.d + 8, 2048u);
    /* Stream table at 0x80 */
    b.d[0x80] = 0; b.d[0x81] = 4; /* 4 stream entries */
    /* Entry 0: Video 0 (0xE0) */
    b.d[0x82] = 0xE0; b.d[0x83] = 0x00;
    be32_at(b.d + 0x86, 1); be32_at(b.d + 0x8A, 1);
    b.d[0x8E] = 4; b.d[0x8F] = 4; /* 64x64 */
    /* Entry 1: Video 1 (0xE1) */
    b.d[0x92] = 0xE1; b.d[0x93] = 0x01;
    be32_at(b.d + 0x96, 1); be32_at(b.d + 0x9A, 1);
    b.d[0x9E] = 2; b.d[0x9F] = 2; /* 32x32 */
    /* Entry 2: Audio 0 (0xB0, sub 0x00) */
    b.d[0xA2] = 0xB0; b.d[0xA3] = 0x00;
    b.d[0xB0] = 2; /* 2 channels */
    /* Entry 3: Audio 1 (0xB1, sub 0x01) */
    b.d[0xB2] = 0xB1; b.d[0xB3] = 0x01;
    b.d[0xC0] = 1; /* 1 channel */

    uint8_t aframe[128];
    for (int i = 0; i < FIX_PICTURES; i++) {
        /* Video 0 PES 1 */
        uint32_t half0 = au0_len[i] / 2u;
        add_video_pes_sid(&b, 0xE0, k_has_pts[i], FIX_BASE + (int64_t)i * FIX_PTS_STEP, es0 + au0_off[i], half0);
        /* Video 1 PES 1 */
        uint32_t half1 = au1_len[i] / 2u;
        int v1_has_pts = (i != 0);
        int64_t v1_pts = FIX_BASE + (int64_t)(i + 1) * 3000;
        add_video_pes_sid(&b, 0xE1, v1_has_pts, v1_pts, es1 + au1_off[i], half1);

        if (i == 0) {
            uint32_t n = make_audio_frame(aframe, sizeof(aframe), 0x28, 6, 0x11);
            add_audio_pes_sub(&b, 0x00, 1, FIX_BASE, aframe, n);
            n = make_audio_frame(aframe, sizeof(aframe), 0x28, 6, 0x33);
            add_audio_pes_sub(&b, 0x01, 0, 0, aframe, n);
        } else if (i == 1) {
            uint32_t n = make_audio_frame(aframe, sizeof(aframe), 0x28, 6, 0x22);
            add_audio_pes_sub(&b, 0x00, 0, 0, aframe, n);
            n = make_audio_frame(aframe, sizeof(aframe), 0x28, 6, 0x44);
            add_audio_pes_sub(&b, 0x01, 1, FIX_BASE + 5000, aframe, n);
        }

        /* Video 0 PES 2 */
        add_video_pes_sid(&b, 0xE0, 0, 0, es0 + au0_off[i] + half0, au0_len[i] - half0);
        /* Video 1 PES 2 */
        add_video_pes_sid(&b, 0xE1, 0, 0, es1 + au1_off[i] + half1, au1_len[i] - half1);
    }
    be32_at(b.d + 12, b.at - 2048u);
    CHECK(!b.overflow, "multistream synthetic PSMF container fits");
    *size_out = b.at;
    return b.d;
}

static void test_multistream_selection(void) {
    uint32_t au0_off[FIX_PICTURES], au0_len[FIX_PICTURES];
    uint32_t au1_off[FIX_PICTURES], au1_len[FIX_PICTURES];
    uint32_t size = 0;
    uint8_t *bytes = build_multistream_psmf(&size, au0_off, au0_len, au1_off, au1_len);
    CHECK(bytes != NULL, "multistream fixture allocated");
    if (!bytes) return;

    uint8_t es0[65536], es1[65536];
    uint32_t es0_len = 0, es1_len = 0;
    static const uint8_t k_y2[FIX_PICTURES]  = {  80u, 160u, 240u };
    static const uint8_t k_cb2[FIX_PICTURES] = { 100u, 128u, 140u };
    static const uint8_t k_cr2[FIX_PICTURES] = { 150u, 128u, 110u };
    build_stream_ex(es0, sizeof(es0), 4, 4, k_y, k_cb, k_cr, au0_off, au0_len, &es0_len);
    build_stream_ex(es1, sizeof(es1), 2, 2, k_y2, k_cb2, k_cr2, au1_off, au1_len, &es1_len);

    MemSource mem;
    SrPsmfProducer *p = open_fixture(bytes, size, &mem, 1024u);
    CHECK(p != NULL, "producer opens multistream PSMF");
    if (!p) { free(bytes); return; }

    CHECK(sr_psmf_producer_video_streams(p) == 2, "producer identifies 2 video streams");
    CHECK(sr_psmf_producer_audio_streams(p) == 2, "producer identifies 2 audio streams");

    /* Out-of-range selection checks */
    CHECK(!sr_psmf_producer_select_streams(p, 2, 0), "selecting video stream 2 refuses out-of-range");
    CHECK(!sr_psmf_producer_select_streams(p, 0, 2), "selecting audio stream 2 refuses out-of-range");
    CHECK(!sr_psmf_producer_select_streams(p, 5, 5), "selecting out-of-range streams refuses");

    /* Test Track 0: Video 0, Audio 0 */
    CHECK(sr_psmf_producer_select_streams(p, 0, 0), "select video 0, audio 0");
    CHECK(sr_psmf_producer_selected_video_stream(p) == 0, "selected video is 0");
    CHECK(sr_psmf_producer_selected_audio_stream(p) == 0, "selected audio is 0");

    int n_v0 = 0, n_a0 = 0;
    for (int guard = 0; guard < 4096 && !sr_psmf_producer_eof(p); guard++) {
        sr_psmf_producer_pump(p, 2);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            CHECK(n_v0 < FIX_PICTURES, "no extra video AUs for stream 0");
            if (n_v0 < FIX_PICTURES) {
                CHECK(au.stream_id == 0xE0, "video AU has stream ID 0xE0");
                CHECK(au.size == au0_len[n_v0], "video 0 AU size matches authored picture");
                if (au.size == au0_len[n_v0])
                    CHECK(memcmp(au.data, es0 + au0_off[n_v0], au.size) == 0, "video 0 AU bytes match stream 0 exactly");
                CHECK(au.has_pts == k_has_pts[n_v0], "video 0 PTS presence preserved");
                if (k_has_pts[n_v0])
                    CHECK(au.pts == (int64_t)n_v0 * FIX_PTS_STEP, "video 0 PTS timestamp normalized");
            }
            sr_psmf_au_release(&au);
            n_v0++;
        }
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_AUDIO, &au)) {
            CHECK(n_a0 < 2, "no extra audio frames for stream 0");
            if (n_a0 < 2) {
                CHECK(au.stream_id == 0x00, "audio AU has substream ID 0x00");
                uint8_t want_fill = (n_a0 == 0) ? 0x11 : 0x22;
                CHECK(au.data && au.size > 8 && au.data[8] == want_fill, "audio 0 frame has stream 0 payload");
                if (n_a0 == 0) {
                    CHECK(au.has_pts == 1, "audio 0 frame 0 has PTS");
                    CHECK(au.pts == 0, "audio 0 frame 0 timestamp normalized");
                } else {
                    CHECK(au.has_pts == 0, "audio 0 frame 1 has no PTS");
                }
            }
            sr_psmf_au_release(&au);
            n_a0++;
        }
    }
    CHECK(n_v0 == FIX_PICTURES, "got exactly 3 video AUs for stream 0");
    CHECK(n_a0 == 2, "got exactly 2 audio frames for stream 0");

    /* Test Track 1: Video 1, Audio 1 */
    CHECK(sr_psmf_producer_select_streams(p, 1, 1), "select video 1, audio 1");
    CHECK(sr_psmf_producer_selected_video_stream(p) == 1, "selected video is 1");
    CHECK(sr_psmf_producer_selected_audio_stream(p) == 1, "selected audio is 1");

    int n_v1 = 0, n_a1 = 0;
    for (int guard = 0; guard < 4096 && !sr_psmf_producer_eof(p); guard++) {
        sr_psmf_producer_pump(p, 2);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            CHECK(n_v1 < FIX_PICTURES, "no extra video AUs for stream 1");
            if (n_v1 < FIX_PICTURES) {
                CHECK(au.stream_id == 0xE1, "video AU has stream ID 0xE1");
                CHECK(au.size == au1_len[n_v1], "video 1 AU size matches authored picture");
                if (au.size == au1_len[n_v1])
                    CHECK(memcmp(au.data, es1 + au1_off[n_v1], au.size) == 0, "video 1 AU bytes match stream 1 exactly");
                int want_pts = (n_v1 != 0);
                CHECK(au.has_pts == want_pts, "video 1 PTS presence preserved");
                if (want_pts)
                    CHECK(au.pts == (int64_t)(n_v1 + 1) * 3000, "video 1 PTS timestamp normalized");
            }
            sr_psmf_au_release(&au);
            n_v1++;
        }
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_AUDIO, &au)) {
            CHECK(n_a1 < 2, "no extra audio frames for stream 1");
            if (n_a1 < 2) {
                CHECK(au.stream_id == 0x01, "audio AU has substream ID 0x01");
                uint8_t want_fill = (n_a1 == 0) ? 0x33 : 0x44;
                CHECK(au.data && au.size > 8 && au.data[8] == want_fill, "audio 1 frame has stream 1 payload");
                if (n_a1 == 0) {
                    CHECK(au.has_pts == 0, "audio 1 frame 0 has no PTS");
                } else {
                    CHECK(au.has_pts == 1, "audio 1 frame 1 has PTS");
                    CHECK(au.pts == 5000, "audio 1 frame 1 timestamp normalized");
                }
            }
            sr_psmf_au_release(&au);
            n_a1++;
        }
    }
    CHECK(n_v1 == FIX_PICTURES, "got exactly 3 video AUs for stream 1");
    CHECK(n_a1 == 2, "got exactly 2 audio frames for stream 1");

    /* Test Track with Video 0 and NO Audio */
    CHECK(sr_psmf_producer_select_streams(p, 0, SR_PSMF_STREAM_NONE), "select video 0, no audio");
    int n_v_noaudio = 0, n_a_noaudio = 0;
    for (int guard = 0; guard < 4096 && !sr_psmf_producer_eof(p); guard++) {
        sr_psmf_producer_pump(p, 2);
        SrPsmfAu au;
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_VIDEO, &au)) {
            sr_psmf_au_release(&au);
            n_v_noaudio++;
        }
        while (sr_psmf_producer_pop(p, SR_PSMF_AU_AUDIO, &au)) {
            sr_psmf_au_release(&au);
            n_a_noaudio++;
        }
    }
    CHECK(n_v_noaudio == FIX_PICTURES, "got exactly 3 video AUs when audio is disabled");
    CHECK(n_a_noaudio == 0, "got 0 audio frames when audio is disabled");

    sr_psmf_producer_close(p);
    free(bytes);
}

<<<<<<< HEAD
static void test_mpeg_ycbcr_guest_contract(void) {
    enum {
        TD_MPEG_DESC = 0x08100000u,
        TD_MPEG_DATA = 0x08110000u,
        TD_MPEG_SIZE = 0x08120000u,
        TD_MPEG_YCBCR = 0x08130000u,
        TD_MPEG_RANGE = 0x08140000u,
        TD_MPEG_DEST = 0x08150000u,
        TD_MPEG_PTR = 0x08160000u,
        TD_MPEG_INIT = 0x08170000u,
        TD_MPEG_AU = 0x08180000u,
    };
    MEM_W32(TD_MPEG_DESC, 0u);
    CHECK(mpeg_create(TD_MPEG_DESC, TD_MPEG_DATA, 0x10000u, 0, 64u, 0, 0) == 0,
          "MPEG YCbCr fixture creates a context");
    CHECK(mpeg_avc_query_ycbcr_size(TD_MPEG_DESC, UINT32_MAX, 64u, 32u, TD_MPEG_SIZE) == 0,
          "MPEG YCbCr fixture queries guest geometry");
    CHECK(MEM_R32(TD_MPEG_SIZE) == 3200u, "MPEG YCbCr fixture uses the checked planar size");
    CHECK(mpeg_avc_query_ycbcr_size(TD_MPEG_DESC, UINT32_MAX, 17u, 32u, TD_MPEG_SIZE) ==
              SCE_MPEG_ERROR_INVALID_VALUE,
          "MPEG YCbCr query rejects unsupported geometry");
    CHECK(mpeg_avc_query_ycbcr_size(TD_MPEG_DESC, UINT32_MAX, 64u, 32u, TD_MPEG_SIZE + 1u) ==
              SCE_MPEG_ERROR_INVALID_VALUE,
          "MPEG YCbCr query rejects an unaligned result pointer");
    CHECK(mpeg_avc_init_ycbcr(TD_MPEG_DESC, UINT32_MAX, 64u, 32u, TD_MPEG_YCBCR) == 0,
          "MPEG YCbCr fixture initializes guest storage");
    CHECK(mpeg_avc_init_ycbcr(TD_MPEG_DESC, UINT32_MAX, 64u, 32u, TD_MPEG_YCBCR + 1u) ==
              SCE_MPEG_ERROR_INVALID_VALUE,
          "MPEG YCbCr init rejects an unaligned allocation");
    YcbcrBuf *state = ycbcr_find(TD_MPEG_DESC, TD_MPEG_YCBCR);
    CHECK(state != NULL && state->rgba != NULL, "MPEG YCbCr fixture retains host state");
    if (state) {
        memset(state->rgba, 0x40, (size_t)state->width * state->height * 4u);
        state->valid = 1;
    }
    MEM_W32(TD_MPEG_PTR, TD_MPEG_YCBCR);
    MEM_W32(TD_MPEG_RANGE, 0u);
    MEM_W32(TD_MPEG_RANGE + 4u, 0u);
    MEM_W32(TD_MPEG_RANGE + 8u, 64u);
    MEM_W32(TD_MPEG_RANGE + 12u, 32u);
    CHECK(mpeg_avc_csc(TD_MPEG_DESC, TD_MPEG_YCBCR, 0u, 64u, TD_MPEG_DEST) ==
              SCE_MPEG_ERROR_INVALID_VALUE,
          "MPEG CSC rejects an invalid range pointer");
    CHECK(mpeg_avc_csc(TD_MPEG_DESC, TD_MPEG_YCBCR, TD_MPEG_RANGE, 64u, TD_MPEG_DEST) == 0,
          "MPEG YCbCr fixture converts an untouched allocation");
    CHECK(MEM_R8(TD_MPEG_DEST) == 0x40u, "MPEG CSC writes the host picture deterministically");
    CHECK(mpeg_avc_copy_ycbcr(TD_MPEG_DESC, TD_MPEG_YCBCR, TD_MPEG_YCBCR + 0x10000u) ==
              SCE_MPEG_ERROR_INVALID_VALUE,
          "MPEG Copy rejects an uninitialized source");
    CHECK(mpeg_avc_decode_ycbcr(TD_MPEG_DESC, TD_MPEG_AU, TD_MPEG_PTR, TD_MPEG_INIT) ==
              SCE_MPEG_ERROR_NO_DATA && MEM_R32(TD_MPEG_INIT) == 0u,
          "MPEG Decode reports no picture without a decoder");
    state = ycbcr_find(TD_MPEG_DESC, TD_MPEG_YCBCR);
    if (state) state->valid = 1;
    MEM_W32(TD_MPEG_RANGE + 8u, 80u);
    MEM_W32(TD_MPEG_RANGE + 12u, 40u);
    CHECK(mpeg_avc_csc(TD_MPEG_DESC, TD_MPEG_YCBCR, TD_MPEG_RANGE, 64u, TD_MPEG_DEST) == 0,
          "MPEG CSC clips a partial source range");
    CHECK(mpeg_avc_decode_stop_ycbcr(TD_MPEG_DESC, TD_MPEG_YCBCR, TD_MPEG_INIT) == 0 &&
              MEM_R32(TD_MPEG_INIT) == 0u,
          "MPEG Stop clears the tracked picture state");
    CHECK(mpeg_avc_init_ycbcr(TD_MPEG_DESC, UINT32_MAX, 64u, 32u, TD_MPEG_YCBCR) == 0,
          "MPEG YCbCr reinitialization resets the allocation");
    state = ycbcr_find(TD_MPEG_DESC, TD_MPEG_YCBCR);
    if (state) {
        memset(state->rgba, 0x40, (size_t)state->width * state->height * 4u);
        state->valid = 1;
    }
    MEM_W32(TD_MPEG_RANGE + 8u, 64u);
    MEM_W32(TD_MPEG_RANGE + 12u, 32u);
    MEM_W8(TD_MPEG_YCBCR, 0xa5u);
    CHECK(mpeg_avc_csc(TD_MPEG_DESC, TD_MPEG_YCBCR, TD_MPEG_RANGE, 64u, TD_MPEG_DEST) ==
              SCE_MPEG_ERROR_INVALID_VALUE,
          "guest mutation cannot reuse hidden RGBA state");
    CHECK(mpeg_query_pcm_es_size(TD_MPEG_DESC, TD_MPEG_SIZE + 0x20u, TD_MPEG_SIZE + 0x24u) == 0 &&
              MEM_R32(TD_MPEG_SIZE + 0x20u) == 320u && MEM_R32(TD_MPEG_SIZE + 0x24u) == 320u,
          "MPEG PCM size query returns the documented fixed sizes");
    uint32_t pcm_sid = mpeg_regist_stream(TD_MPEG_DESC, MPEG_PCM_STREAM, 0u);
    CHECK(pcm_sid != 0u &&
              mpeg_get_pcm_au(TD_MPEG_DESC, pcm_sid, TD_MPEG_SIZE + 0x28u, TD_MPEG_SIZE + 0x40u) ==
                  SCE_MPEG_ERROR_NO_DATA,
          "MPEG PCM AU remains an explicit no-data refusal");
    CHECK(mpeg_change_get_au_mode(TD_MPEG_DESC, pcm_sid, MPEG_AU_MODE_SKIP) != 0u,
          "MPEG AU skip mode fails closed without a queue contract");
    mpeg_finish();
    CHECK(ycbcr_find(TD_MPEG_DESC, TD_MPEG_YCBCR) == NULL,
          "MPEG teardown frees guest YCbCr state");
}

int main(void) {
=======
int main(int argc, char **argv) {
    unsigned fuzz_iterations = 0;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--fuzz-iters") == 0 && i + 1 < argc) {
            char *end = NULL;
            unsigned long value = strtoul(argv[++i], &end, 10);
            if (end && *end == '\0' && value > 0 && value <= 100000ul) {
                fuzz_iterations = (unsigned)value;
            }
        }
    }
>>>>>>> 2a1eb6d2689575eb6771c78b76c621f60b8e35f9
    static uint8_t arena[ARENA_BYTES];
    g_mem = arena;
    memset(arena, 0, sizeof(arena));

    test_demux_and_au_contract();
    test_multistream_selection();
    test_track_independence();
    test_real_decode_into_guest_buffer();
    test_decoded_pixels();
    test_instance_isolation();
    test_destination_refusal();
    test_legacy_feed_take_path();
<<<<<<< HEAD
    test_mpeg_ycbcr_guest_contract();
=======
    if (fuzz_iterations) test_legacy_demux_mutations(fuzz_iterations);
>>>>>>> 2a1eb6d2689575eb6771c78b76c621f60b8e35f9

    if (failures) {
        fprintf(stderr, "psmf_media_selftest: %d checks, %d FAILURES\n", checks, failures);
        return 1;
    }
    printf("psmf_media_selftest: %d checks, 0 failures\n", checks);
    return 0;
}
