# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025-2026 the psp-recomp authors

"""Synthetic PGD constants so the PGD tests run without real console keys.

These values are **invented** -- arithmetic patterns, not PSP KIRK/amctrl keys.
They decrypt nothing. They exist because every PGD test builds its own fixture
with the reference implementation and then round-trips it, or compares the C
port against the Python reference. Both only require the two sides to agree on
*some* constant set, never the real one. Tests that touch real encrypted data
gate separately on the private input and `HST_PGD_VKEY_HEX` being present.

Importing this module writes a key file to a temporary directory and points
`SR_PGD_KEYS` at it. Because that lands in `os.environ`, subprocess-based tests
(the C harness in `tools/pgd_e2e_harness.c`, the `pgd_decrypt.py` CLI) inherit it
with no extra wiring. A real `keys/pgd_keys.txt` is left untouched and unread.

Import this before anything that resolves constants:

    import pgd_test_keys  # noqa: F401  (sets SR_PGD_KEYS)

See docs/PGD_KEYS.md for the real schema.
"""

from __future__ import annotations

import atexit
import os
import shutil
import tempfile

# Deterministic and obviously synthetic: each entry is a distinct affine pattern
# over the byte index, so a value cannot be mistaken for key material.
SYNTHETIC_KEYS: dict[str, str] = {
    "kirk_keyseed_38": bytes(((i * 11) + 0x03) & 0xFF for i in range(16)).hex(),
    "kirk_keyseed_39": bytes(((i * 13) + 0x05) & 0xFF for i in range(16)).hex(),
    "kirk_keyseed_63": bytes(((i * 17) + 0x07) & 0xFF for i in range(16)).hex(),
    "amctrl_loc_1cd4": bytes(((i * 19) + 0x0B) & 0xFF for i in range(16)).hex(),
    "amctrl_loc_1ce4": bytes(((i * 23) + 0x0D) & 0xFF for i in range(16)).hex(),
    "amctrl_loc_1cf4": bytes(((i * 29) + 0x11) & 0xFF for i in range(16)).hex(),
    "dnas_1a90": bytes(((i * 31) + 0x13) & 0xFF for i in range(16)).hex(),
    "dnas_1aa0": bytes(((i * 37) + 0x17) & 0xFF for i in range(16)).hex(),
}

KEY_FILE_HEADER = (
    "# Synthetic constants generated by tools/pgd_test_keys.py for the test\n"
    "# suite. These are NOT PSP console keys and decrypt nothing real.\n"
)


def render() -> str:
    """The key file body, in the format docs/PGD_KEYS.md specifies."""
    lines = [KEY_FILE_HEADER]
    lines += [f"{name} = {value}\n" for name, value in SYNTHETIC_KEYS.items()]
    return "".join(lines)


def install() -> str:
    """Write the synthetic key file and point SR_PGD_KEYS at it. Idempotent."""
    existing = os.environ.get("SR_PGD_KEYS")
    if existing and os.path.isfile(existing) and os.path.basename(existing) == _BASENAME:
        return existing

    tmpdir = tempfile.mkdtemp(prefix="pgd-test-keys-")
    atexit.register(shutil.rmtree, tmpdir, True)
    path = os.path.join(tmpdir, _BASENAME)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render())
    os.environ["SR_PGD_KEYS"] = path
    return path


_BASENAME = "pgd_keys_synthetic.txt"

KEY_FILE_PATH = install()
