# SPDX-License-Identifier: GPL-3.0-or-later
"""LLE Phase 1 (PR 2) gates: COP0, exceptions, eret, and interpreter support.

Failing-before evidence (spec section 11, PR 2): on the base tree generated
syscalls use sr_raw_syscall, generated breaks use sr_break, effect() raises
Unsupported for every COP0 word, is_control() misses eret, function_flow()
falls through eret, delay_slot_lines/LLE_CPU do not exist, src/rt/cpu_lle.*
do not exist, the interpreter answers UNSUPPORTED for syscall/break with no
eret path, and the Makefile has no cpu-lle-selftest target. Every LLE test
below fails there and passes here; the HLE-default tests pin the behavior
that must not move.
"""

import re
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

import codegen


CPU_LLE_H = ROOT / "src" / "rt" / "cpu_lle.h"
CPU_LLE_C = ROOT / "src" / "rt" / "cpu_lle.c"
GUEST_INTERP_H = ROOT / "src" / "rt" / "guest_interp.h"
MAKEFILE = (ROOT / "Makefile").read_text(encoding="utf-8")


class FakeElf:
    def __init__(self, words):
        self.words = words

    def read_at_vaddr(self, addr, size):
        if size != 4 or addr not in self.words:
            return None
        return self.words[addr].to_bytes(4, "little")


def mfc0(rt, rd, sel=0):
    return (0x10 << 26) | (rt << 16) | (rd << 11) | sel


def mtc0(rt, rd, sel=0):
    return (0x10 << 26) | (4 << 21) | (rt << 16) | (rd << 11) | sel


ERET = 0x42000018
SYSCALL = 0x0000000C
BREAK = 0x0000000D
JR_RA = 0x03E00008
NOP = 0x00000000
CC = shutil.which("gcc")

GENERATED_SYSCALL_ENTRY = 0x08810800
GENERATED_SYSCALL_CALLER = 0x08810820
GENERATED_BREAK_ENTRY = 0x08810840
GENERATED_BREAK_CALLER = 0x08810860


def _jal(target):
    return 0x0C000000 | ((target >> 2) & 0x03FFFFFF)


def _emit_generated_fatal_flow_fixture():
    """Emit real --lle-cpu bodies and callers for the native fatal-flow test."""
    previous_lle_cpu = codegen.LLE_CPU
    codegen.LLE_CPU = True  # same module switch set by the --lle-cpu CLI option
    try:
        generated = ['/* Generated by tools/test_cpu_lle.py; do not edit. */',
                     '#include "recomp.h"', ""]
        for entry, instruction in (
                (GENERATED_SYSCALL_ENTRY, SYSCALL),
                (GENERATED_BREAK_ENTRY, BREAK)):
            generated.extend(codegen.emit_function(
                FakeElf({entry: instruction}), entry, [(entry, entry + 4)], {entry}))

        for caller, target in (
                (GENERATED_SYSCALL_CALLER, GENERATED_SYSCALL_ENTRY),
                (GENERATED_BREAK_CALLER, GENERATED_BREAK_ENTRY)):
            # The call target is intentionally absent from `known`, forcing the
            # generated caller through production dispatch_call(). The addiu
            # immediately after its delay slot is the guest-visible sentinel.
            words = {
                caller: _jal(target),
                caller + 4: NOP,
                caller + 8: (0x09 << 26) | (8 << 16) | 1,  # addiu $t0,$zero,1
                caller + 12: JR_RA,
                caller + 16: NOP,
            }
            generated.extend(codegen.emit_function(
                FakeElf(words), caller, [(caller, caller + 20)], {caller}))
        return "\n".join(generated)
    finally:
        codegen.LLE_CPU = previous_lle_cpu


# LL/SC parity sequences (opcode 0x30/0x38). The same words are emitted as real
# generated C here and run through the production interpreter by
# src/rt/cpu_lle_selftest.c, which compares the two lanes and the expected values.
LLSC_DEFAULT_ENTRY = 0x08810900   # default-lane emission of LLSC_SEQUENCE
LLSC_LLE_ENTRY = 0x08810980       # --lle-cpu emission of LLSC_SEQUENCE
LLSC_LLE_MISALIGNED_SC_ENTRY = 0x08810A00
LLSC_LLE_MISALIGNED_LL_ENTRY = 0x08810A20
A0, T0, T1, T2, T3, T4 = 4, 8, 9, 10, 11, 12


def _ll(base, rt, offset):
    return (0x30 << 26) | (base << 21) | (rt << 16) | (offset & 0xFFFF)


def _sc(base, rt, offset):
    return (0x38 << 26) | (base << 21) | (rt << 16) | (offset & 0xFFFF)


def _addiu(rt, rs, immediate):
    return (0x09 << 26) | (rs << 21) | (rt << 16) | (immediate & 0xFFFF)


def _beq(rs, rt, offset_words):
    return (0x04 << 26) | (rs << 21) | (rt << 16) | (offset_words & 0xFFFF)


# Mirrored word-for-word by LLSC_SEQUENCE in src/rt/cpu_lle_selftest.c.
LLSC_SEQUENCE = (
    _sc(A0, T1, 0),          # 0x00 sc    t1, 0(a0)    link as seeded
    _ll(A0, T2, 4),          # 0x04 ll    t2, 4(a0)
    _addiu(T2, T2, 5),       # 0x08 addiu t2, t2, 5
    _sc(A0, T2, 4),          # 0x0c sc    t2, 4(a0)    linked: stores, t2 = 1
    _sc(A0, T3, 8),          # 0x10 sc    t3, 8(a0)    link left set: stores again
    _ll(A0, 0, 12),          # 0x14 ll    zero, 12(a0) links, no register write
    _ll(A0, T4, 20),         # 0x18 L: ll t4, 20(a0)
    _addiu(T4, T4, 1),       # 0x1c addiu t4, t4, 1
    _sc(A0, T4, 20),         # 0x20 sc    t4, 20(a0)
    _beq(T4, 0, -4),         # 0x24 beq   t4, zero, L  (retry loop)
    NOP,                     # 0x28
    _sc(A0, A0, 24),         # 0x2c sc    a0, 24(a0)   rt == base
    JR_RA,                   # 0x30
    NOP,                     # 0x34
)


def _emit_llsc_parity_fixture():
    """Emit the LL/SC sequences in both CPU lanes for the native parity test."""
    generated = []
    previous_lle_cpu = codegen.LLE_CPU
    try:
        for entry, words, lle in (
                (LLSC_DEFAULT_ENTRY, LLSC_SEQUENCE, False),
                (LLSC_LLE_ENTRY, LLSC_SEQUENCE, True),
                (LLSC_LLE_MISALIGNED_SC_ENTRY, (_sc(A0, T1, 2), JR_RA, NOP), True),
                (LLSC_LLE_MISALIGNED_LL_ENTRY, (_ll(A0, T1, 1), JR_RA, NOP), True)):
            codegen.LLE_CPU = lle
            image = {entry + 4 * i: word for i, word in enumerate(words)}
            generated.extend(codegen.emit_function(
                FakeElf(image), entry, [(entry, entry + 4 * len(words))], {entry},
                lle_cpu=lle))
    finally:
        codegen.LLE_CPU = previous_lle_cpu
    return "\n".join(generated)


class LlScLleCodegenTests(unittest.TestCase):
    """ll/sc under --lle-cpu carry the same width-4 address guard as lw/sw.

    Failing-before evidence: effect() raised Unsupported for opcodes 0x30 and
    0x38 in both lanes, so no guard (and no translation) existed."""

    def test_ll_guard_runs_before_the_load_and_the_link(self):
        stmt, saddr, _ = codegen.effect(0x1000, _ll(A0, T1, 8), lle_cpu=True)
        guard = stmt.index("sr_cpu_guard_access(s, _ea, 4u, 0, 0x00001000u, 0u, 0u)")
        self.assertLess(guard, stmt.index("MEM_R32(_ea)"))
        self.assertLess(guard, stmt.index("s->llbit = 1u;"))
        self.assertIsNone(saddr)

    def test_sc_guard_runs_before_the_link_is_consulted(self):
        stmt, saddr, _ = codegen.effect(0x1000, _sc(A0, T1, 8), lle_cpu=True)
        guard = stmt.index("sr_cpu_guard_access(s, _ea, 4u, 1, 0x00001000u, 0u, 0u)")
        self.assertLess(guard, stmt.index("s->llbit != 0u"))
        self.assertLess(guard, stmt.index("MEM_W32_PC(_ea,"))
        self.assertIs(saddr, codegen.SELF_TRACED)

    def test_delay_slot_ll_sc_carry_the_branch_pc(self):
        for word, is_store in ((_ll(A0, T1, 8), 0), (_sc(A0, T1, 8), 1)):
            with self.subTest(store=is_store):
                body = "\n".join(codegen.delay_slot_lines(0x1004, word, 0x1000, lle_cpu=True))
                self.assertIn(f"sr_cpu_guard_access(s, _ea, 4u, {is_store}, "
                              "0x00001004u, 0x00001000u, 1u)", body)

    def test_generated_parity_fixture_emits_both_lanes(self):
        source = _emit_llsc_parity_fixture()
        self.assertIn(f"void f_{LLSC_DEFAULT_ENTRY:08x}(CpuState *s)", source)
        self.assertIn(f"void f_{LLSC_LLE_ENTRY:08x}(CpuState *s)", source)
        self.assertNotIn("sr_unimplemented", source)
        default = source.split(f"void f_{LLSC_LLE_ENTRY:08x}")[0]
        self.assertNotIn("sr_cpu_guard_access", default)
        self.assertEqual(source.count("s->llbit = 1u;"), 2 * 3 + 1)


class HleDefaultPreservedTests(unittest.TestCase):

    """Default-profile codegen still routes through the HLE path."""

    def test_default_syscall_uses_raw_syscall(self):
        stmt, _, _ = codegen.effect(0x1000, SYSCALL)
        self.assertIn("sr_raw_syscall(s, 0u", stmt)
        self.assertNotIn("sr_cpu_raise_exception", stmt)

    def test_default_break_uses_sr_break(self):
        stmt, _, _ = codegen.effect(0x1000, BREAK)
        self.assertIn("sr_break(s, 0u", stmt)
        self.assertNotIn("sr_cpu_raise_exception", stmt)

    def test_default_syscall_codes_survive(self):
        stmt1, _, _ = codegen.effect(0, 0x48CC)
        stmt2, _, _ = codegen.effect(0, 0x1158C)
        self.assertIn("sr_raw_syscall(s, 291u", stmt1)
        self.assertIn("sr_raw_syscall(s, 1110u", stmt2)

    def test_emit_default_syscall_function(self):
        text = "\n".join(
            codegen.emit_function(
                FakeElf({0x1000: SYSCALL}),
                0x1000, [(0x1000, 0x1008)], {0x1000},
            )
        )
        self.assertIn("sr_raw_syscall", text)
        self.assertNotIn("sr_cpu_raise_exception", text)

    def test_production_fixture_recipes_do_not_opt_into_lle(self):
        for target in ("production-smoke:", "cosim-selftest:"):
            recipe = MAKEFILE.split(target, 1)[1].split("\n\n", 1)[0]
            self.assertNotIn("--lle-cpu", recipe)


class LleCodegenTests(unittest.TestCase):
    """LLE-mode codegen raises guest exceptions with flow propagation."""

    def test_lle_syscall_raises_sys(self):
        stmt, _, _ = codegen.effect(0x1000, SYSCALL, lle_cpu=True)
        self.assertIn("sr_cpu_raise_exception(s, 8u, 0x00001000u", stmt)
        self.assertIn("return;", stmt)
        self.assertNotIn("sr_raw_syscall", stmt)

    def test_lle_break_raises_bp(self):
        stmt, _, _ = codegen.effect(0x1000, BREAK, lle_cpu=True)
        self.assertIn("sr_cpu_raise_exception(s, 9u, 0x00001000u", stmt)
        self.assertNotIn("sr_break", stmt)

    def test_mfc0_emits_helper(self):
        stmt, _, _ = codegen.effect(0x1000, mfc0(8, 12))
        self.assertIn("sr_cp0_mfc0(s, 8u, 12u, 0u, 0x00001000u)", stmt)

    def test_mtc0_emits_helper(self):
        stmt, _, _ = codegen.effect(0x1000, mtc0(8, 12))
        self.assertIn("sr_cp0_mtc0(s, 8u, 12u, 0u, 0x00001000u)", stmt)

    def test_eret_emits_helper(self):
        stmt, _, _ = codegen.effect(0x1000, ERET)
        self.assertIn("sr_cpu_eret(s, 0x00001000u)", stmt)

    def test_cop0_reserved_bits_stay_untranslatable(self):
        with self.assertRaises(codegen.Unsupported):
            codegen.effect(0x1000, mfc0(8, 12) | 0x8)

    def test_unknown_cop0_rs_stays_untranslatable(self):
        with self.assertRaises(codegen.Unsupported):
            codegen.effect(0x1000, (0x10 << 26) | (0x08 << 21))

    def test_eret_is_control_and_exact(self):
        self.assertTrue(codegen.is_eret(ERET))
        self.assertFalse(codegen.is_eret(ERET | 0x1))
        self.assertTrue(codegen.is_control(ERET))

    def test_function_flow_terminates_at_eret(self):
        insns, _, _ = codegen.function_flow(
            FakeElf({0x1000: ERET, 0x1004: NOP}),
            0x1000, [(0x1000, 0x100C)], {0x1000},
        )
        self.assertIn(0x1000, insns)
        self.assertNotIn(0x1004, insns)

    def test_emit_lle_syscall_function(self):
        text = "\n".join(
            codegen.emit_function(
                FakeElf({0x1000: SYSCALL}),
                0x1000, [(0x1000, 0x1008)], {0x1000},
                lle_cpu=True,
            )
        )
        self.assertIn("sr_cpu_raise_exception(s, 8u", text)
        self.assertNotIn("sr_raw_syscall", text)

    def test_emit_mfc0_propagates_flow(self):
        text = "\n".join(
            codegen.emit_function(
                FakeElf({0x1000: mfc0(8, 12), 0x1004: JR_RA, 0x1008: NOP}),
                0x1000, [(0x1000, 0x100C)], {0x1000},
            )
        )
        self.assertIn("sr_cp0_mfc0(s, 8u, 12u, 0u", text)
        self.assertIn("if (s->flow_kind != 0u)", text)

    def test_emit_eret_terminates_function(self):
        text = "\n".join(
            codegen.emit_function(
                FakeElf({0x1000: ERET, 0x1004: NOP}),
                0x1000, [(0x1000, 0x100C)], {0x1000},
            )
        )
        self.assertIn("sr_cpu_eret(s, 0x00001000u)", text)
        self.assertIn("return;", text)

    def test_delay_slot_syscall_carries_branch_pc_in_lle(self):
        lines = codegen.delay_slot_lines(
            0x1004, SYSCALL, 0x1000, lle_cpu=True, resumable=False)
        text = "\n".join(lines)
        self.assertIn("0x00001004u, 0x00001000u, 0u, 1u, 0u", text)

    def test_delay_slot_hle_syscall_is_unchanged(self):
        lines = codegen.delay_slot_lines(0x1004, SYSCALL, 0x1000)
        self.assertEqual(len(lines), 1)
        self.assertIn("sr_raw_syscall", lines[0])

    def test_delay_slot_control_fails_closed(self):
        beq = 0x10000000 | (1 << 21) | (2 << 16) | 1
        with self.assertRaises(codegen.Unsupported):
            codegen.delay_slot_lines(0x1004, beq, 0x1000)

    def test_emit_eret_preserves_guest_sp(self):
        text = "\n".join(
            codegen.emit_function(
                FakeElf({0x1000: ERET, 0x1004: NOP}),
                0x1000, [(0x1000, 0x100C)], {0x1000},
                resumable=False,
            )
        )
        self.assertIn("sr_cpu_eret(s, 0x00001000u);", text)
        self.assertIn("sr_end(s, 0u, 0);\n    return;", text)
        self.assertNotIn("sr_end(s, 0u, 0);\n    s->r[29] = _sp_entry;", text)

    def test_delay_slot_exception_unwind_preserves_guest_sp(self):
        lines_sys = codegen.delay_slot_lines(
            0x1004, SYSCALL, 0x1000, lle_cpu=True, resumable=False)
        text_sys = "\n".join(lines_sys)
        self.assertNotIn("s->r[29] = _sp_entry", text_sys)
        self.assertIn("{ sr_end(s, 0u, 0); return; }", text_sys)

        lines_brk = codegen.delay_slot_lines(
            0x1004, BREAK, 0x1000, lle_cpu=True, resumable=False)
        text_brk = "\n".join(lines_brk)
        self.assertNotIn("s->r[29] = _sp_entry", text_brk)
        self.assertIn("{ sr_end(s, 0u, 0); return; }", text_brk)

        lines_mfc0 = codegen.delay_slot_lines(
            0x1004, mfc0(8, 12), 0x1000, lle_cpu=True, resumable=False)
        text_mfc0 = "\n".join(lines_mfc0)
        self.assertNotIn("s->r[29] = _sp_entry", text_mfc0)

    def test_delay_slot_cop0_saves_and_restores_context(self):
        lines = codegen.delay_slot_lines(
            0x1004, mfc0(8, 12), 0x1000, lle_cpu=True, resumable=False)
        text = "\n".join(lines)
        self.assertIn("_prev_npc = s->next_pc", text)
        self.assertIn("_prev_ids = s->in_delay_slot", text)
        self.assertIn("s->in_delay_slot = 1u; s->next_pc = 0x00001000u;", text)
        self.assertRegex(
            text,
            r"if \(sr_cp0_mfc0\(.*?\)\s*<\s*0\)\s*\{\s*s->in_delay_slot = _prev_ids;\s*s->next_pc = _prev_npc;\s*sr_end\(s, 0u, 0\);\s*return;\s*\}"
        )
        self.assertIn("s->in_delay_slot = _prev_ids; s->next_pc = _prev_npc; }", text)

    def test_direct_jal_caller_propagates_lle_flow(self):
        jal_target = 0x00001008
        jal_insn = 0x0C000000 | ((jal_target >> 2) & 0x03FFFFFF)
        text_lle = "\n".join(
            codegen.emit_function(
                FakeElf({0x1000: jal_insn, 0x1004: NOP, 0x1008: JR_RA, 0x100C: NOP}),
                0x1000, [(0x1000, 0x1008)], {0x1000, 0x1008},
                lle_cpu=True,
            )
        )
        self.assertIn("f_00001008(s);", text_lle)
        self.assertIn("if (s->flow_kind != 0u) { return; }", text_lle)

        text_default = "\n".join(
            codegen.emit_function(
                FakeElf({0x1000: jal_insn, 0x1004: NOP, 0x1008: JR_RA, 0x100C: NOP}),
                0x1000, [(0x1000, 0x1008)], {0x1000, 0x1008},
                lle_cpu=False,
            )
        )
        self.assertIn("f_00001008(s);", text_default)
        self.assertNotIn("flow_kind", text_default)

    def test_sr_register_all_enables_lle_runtime_when_lle_cpu(self):
        source = (ROOT / "tools" / "codegen.py").read_text(encoding="utf-8")
        self.assertIn("if LLE_CPU:", source)
        self.assertIn("sr_cpu_lle_set_enabled(1);", source)

    def test_lle_cli_flag_drives_the_module_default(self):
        source = (ROOT / "tools" / "codegen.py").read_text(encoding="utf-8")
        self.assertIn('"--lle-cpu"', source)
        previous = codegen.LLE_CPU
        try:
            codegen.LLE_CPU = True
            text = "\n".join(
                codegen.emit_function(
                    FakeElf({0x1000: SYSCALL}),
                    0x1000, [(0x1000, 0x1008)], {0x1000},
                )
            )
            self.assertIn("sr_cpu_raise_exception(s, 8u", text)
        finally:
            codegen.LLE_CPU = previous


class GeneratedLleFatalFlowTests(unittest.TestCase):
    """Generated --lle-cpu SYSCALL/BREAK bodies cross the real fatal boundary."""

    def test_generated_callers_dispatch_and_place_sentinel_after_the_call(self):
        source = _emit_generated_fatal_flow_fixture()
        self.assertEqual(source.count("sr_cpu_raise_exception(s, 8u"), 1)
        self.assertEqual(source.count("sr_cpu_raise_exception(s, 9u"), 1)
        self.assertIn(
            "dispatch_call(s, 0x08810800u, 0x08810828u);", source)
        self.assertIn(
            "dispatch_call(s, 0x08810840u, 0x08810868u);", source)
        self.assertEqual(source.count("s->r[8] = (0u + 0x00000001u);"), 2)

    def test_make_compiles_the_generated_fixture_into_the_runtime_selftest(self):
        self.assertIn("CPU_LLE_AOT_FIXTURE_C := $(BUILD_DIR)/cpu_lle_aot_flow_fixture.c", MAKEFILE)
        self.assertIn("--generate-lle-aot-flow-fixture", MAKEFILE)
        recipe = MAKEFILE.split("cpu-lle-selftest:", 1)[1].split("\n\n", 1)[0]
        self.assertIn("$(CPU_LLE_AOT_FIXTURE_C)", recipe)


# Test-only stand-in for the two SDL3 timer entry points src/rt/sched.c calls.
# It is used only when SDL3 development headers are absent, so the scheduler
# proof still runs on a host that cannot build the player.
SDL_TIMER_SHIM = """\
#ifndef NK_TEST_SDL_TIMER_SHIM_H
#define NK_TEST_SDL_TIMER_SHIM_H
#include <stdint.h>
#include <time.h>
static inline uint64_t SDL_GetTicksNS(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ull + (uint64_t)ts.tv_nsec;
}
static inline void SDL_DelayPrecise(uint64_t ns) {
    struct timespec ts;
    ts.tv_sec = (time_t)(ns / 1000000000ull);
    ts.tv_nsec = (long)(ns % 1000000000ull);
    nanosleep(&ts, NULL);
}
#endif
"""


@unittest.skipUnless(CC, "gcc is required for the generated scheduler ERET proof")
class LleSchedulerIntegrationTests(unittest.TestCase):
    """Run generated exception/ERET flow through real dispatch and scheduling."""

    def test_generated_tail_eret_and_scheduler_reuse(self):
        def addiu(rt, rs, immediate):
            return (0x09 << 26) | (rs << 21) | (rt << 16) | (immediate & 0xFFFF)

        def lw(rt, base, offset=0):
            return (0x23 << 26) | (base << 21) | (rt << 16) | (offset & 0xFFFF)

        def sw(rt, base, offset=0):
            return (0x2B << 26) | (base << 21) | (rt << 16) | (offset & 0xFFFF)

        def emit(entry, words, end):
            return "\n".join(codegen.emit_function(
                FakeElf(words), entry, [(entry, end)], {entry}, lle_cpu=True,
            ))

        outer = emit(0x1000, {
            0x1000: _jal(0x2000), 0x1004: NOP,
            0x1008: 0x3C080885,  # lui t0, 0x0885
            0x100C: 0x3508F000,  # ori t0, t0, 0xf000 (linked continuation count)
            0x1010: lw(9, 8),
            0x1014: addiu(9, 9, 1),
            0x1018: sw(9, 8),
            0x101C: JR_RA, 0x1020: NOP,
        }, 0x1024)
        middle = emit(0x2000, {
            0x2000: 0x24083000,  # addiu t0, zero, LEAF
            0x2004: (8 << 21) | 8,  # jr t0, non-linking tail
            0x2008: NOP,
            0x200C: 0x3C080885,  # post-tail sentinel: increment 0x0885f004
            0x2010: 0x3508F004,
            0x2014: lw(9, 8),
            0x2018: addiu(9, 9, 1),
            0x201C: sw(9, 8),
            0x2020: JR_RA, 0x2024: NOP,
        }, 0x2028)
        leaf = emit(0x3000, {0x3000: SYSCALL}, 0x3004)
        eret_vector = emit(0x4000, {
            0x4000: 0x3C080885,
            0x4004: 0x3508F008,  # vector ERET count
            0x4008: lw(9, 8),
            0x400C: addiu(9, 9, 1),
            0x4010: sw(9, 8),
            0x4014: ERET,
        }, 0x4018)
        recovery = emit(0x5000, {
            0x5000: 0x3C080885,
            0x5004: 0x3508F00C,  # authorized recovery count
            0x5008: lw(9, 8),
            0x500C: addiu(9, 9, 1),
            0x5010: sw(9, 8),
            0x5014: NOP,
        }, 0x5018)
        followup = emit(0x6000, {
            0x6000: addiu(2, 0, 0x321),
            0x6004: JR_RA, 0x6008: NOP,
        }, 0x600C)

        self.assertIn("dispatch(s, _t);", middle)
        tail_dispatch = middle.index("dispatch(s, _t);")
        self.assertIn("return;", middle[tail_dispatch:])
        self.assertNotIn("0x0000f004u", middle)
        self.assertIn("sr_cpu_raise_exception(s, 8u", leaf)
        self.assertIn("sr_cpu_eret(s, 0x00004014u)", eret_vector)

        prefix = r'''#include "recomp.h"
#include "cpu_lle.h"
#include "sr_coro.h"
#include "title_config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

uint64_t SDL_GetTicksNS(void) { return 0u; }
void SDL_DelayPrecise(uint64_t ns) { (void)ns; }
uint32_t g_sr_debug = 0;
SrMemWatch g_sr_mem_watches[SR_MAX_MEM_WATCHES];
int g_sr_mem_watch_count = 0;
int g_sr_metadata_watch = 0;
uint32_t g_sr_mem_watch_context_pc = 0;
unsigned g_sr_mem_watch_context_limit = 0;
unsigned g_sr_mem_watch_context_count = 0;
int g_sr_mem_watch_context_fpr = -1;
uint32_t g_sr_mem_watch_context_fpr_value = 0;
uint32_t g_sr_store_context_pc = 0;
unsigned g_sr_store_context_count = 0;
unsigned g_sr_store_context_limit = 0;
int g_sr_store_context_mem_gpr = -1;
uint32_t g_sr_store_context_mem_offset = 0;
unsigned g_sr_store_context_mem_words = 0;
int g_sr_last_writer_enabled = 0;
void sr_note_mem_write(uint32_t a, uint32_t w, uint32_t v, uint32_t pc) {
    (void)a; (void)w; (void)v; (void)pc;
}
uint32_t sr_get_ge_status(void) { return 0u; }
int sr_vfpu_interp(CpuState *s, uint32_t op) {
    (void)s; (void)op; return 0;
}
uint32_t sr_hle_resolve_late_import(uint32_t nid) { (void)nid; return 0u; }
uint32_t sr_syscall(CpuState *s, uint32_t nid) {
    (void)s; (void)nid; return 0u;
}
void sr_display_advance_vcount(uint32_t periods) { (void)periods; }
uint32_t sr_vblank_handler(void) { return 0u; }
uint32_t sr_vblank_arg(void) { return 0u; }
uint32_t sr_vblank_no(void) { return 0u; }
int sr_vblank_dispatch_registered(void) { return 0; }
void sr_vblank_tick(void) {}
void sr_callback_unregister_owner(uint32_t uid) { (void)uid; }
void sr_hle_release_thread_resources(uint32_t uid) { (void)uid; }
static uint32_t g_uid = 0x100u;
uint32_t sr_alloc_uid(void) { return g_uid++; }
int gui_on(void) { return 0; }
void gui_pump(void) {}
int sr_thread_has_pending_callbacks(void) { return 0; }
int sr_thread_dispatch_callbacks(void) { return 0; }
uint32_t g_frame_prims = 0;
int sr_title_config_vblank_counters(uint32_t *frame_addr, uint32_t *vsync_addr) {
    (void)frame_addr; (void)vsync_addr; return 0;
}
int sr_title_config_reent_bindings(SrTitleReentBindings *out) {
    (void)out; return 0;
}
int sr_title_config_is_worker_entry(uint32_t entry) { (void)entry; return 0; }
int sr_title_config_is_launcher_entry(uint32_t entry) { (void)entry; return 0; }
int sr_title_config_preserve_callee_saved_at_calls(void) { return 0; }
int sr_title_config_is_callback_terminator(uint32_t sentinel,
                                           uint32_t pc, uint32_t ra) {
    (void)sentinel; (void)pc; (void)ra; return 0;
}
int sr_title_config_dispatch_alias(uint32_t from, uint32_t *to_addr) {
    (void)from; (void)to_addr; return 0;
}

#define OUTER 0x00001000u
#define MIDDLE 0x00002000u
#define LEAF 0x00003000u
#define VECTOR 0x00004000u
#define RECOVERY 0x00005000u
#define FOLLOWUP 0x00006000u
#define OUTER_COUNT 0x0885f000u
#define TAIL_SENTINEL 0x0885f004u
#define VECTOR_COUNT 0x0885f008u
#define RECOVERY_COUNT 0x0885f00cu

void f_00004000(CpuState *s);
void f_00006000(CpuState *s);
static unsigned handler_calls;
static unsigned followup_calls;
static unsigned followup_saw_stale_flow;

static void integration_handler(CpuState *s) {
    handler_calls++;
    uint32_t uid = sched_create_thread(FOLLOWUP, 32, 0);
    if (uid == 0u || sched_start_thread(uid, 0u, 0u) != 0u) abort();
    /* Model the source-owned handler's EPC adjustment, then execute its generated
     * ERET body so production dispatch owns the transfer and recovery call. */
    s->cop0[SR_CP0_EPC] = RECOVERY;
    f_00004000(s);
    if (s->flow_kind != SR_FLOW_ERET) abort();
}

static void followup_entry(CpuState *s) {
    followup_calls++;
    if (s->flow_kind != SR_FLOW_NONE) followup_saw_stale_flow++;
    f_00006000(s);
}
'''
        suffix = r'''

int main(void) {
    CpuState seed;
    memset(&seed, 0, sizeof(seed));
    sr_cpu_lle_reset_config();
    sr_cpu_lle_set_enabled(1);
    sr_cpu_lle_set_vectors(VECTOR, VECTOR, VECTOR);
    sr_exec_span_reset();
    if (!sr_exec_span_register(0x1000u, 0x1024u) ||
        !sr_exec_span_register(0x2000u, 0x2028u) ||
        !sr_exec_span_register(0x3000u, 0x3004u) ||
        !sr_exec_span_register(0x4000u, 0x4018u) ||
        !sr_exec_span_register(0x5000u, 0x5018u) ||
        !sr_exec_span_register(0x6000u, 0x600cu)) return 2;
    sr_register(OUTER, f_00001000);
    sr_register(MIDDLE, f_00002000);
    sr_register(LEAF, f_00003000);
    sr_register(VECTOR, integration_handler);
    sr_register(RECOVERY, f_00005000);
    sr_register(FOLLOWUP, followup_entry);
    sr_mem_init();
    if (!sr_coro_main()) return 3;
    seed.pc = OUTER;
    seed.r[29] = 0x09000000u;
    MEM_W32(OUTER_COUNT, 0u);
    MEM_W32(TAIL_SENTINEL, 0u);
    MEM_W32(VECTOR_COUNT, 0u);
    MEM_W32(RECOVERY_COUNT, 0u);
    sched_init(&seed);
    sched_run(OUTER, 0u, 0u);
    if (handler_calls != 1u || followup_calls != 1u ||
        followup_saw_stale_flow != 0u ||
        MEM_R32(OUTER_COUNT) != 1u || MEM_R32(TAIL_SENTINEL) != 0u ||
        MEM_R32(VECTOR_COUNT) != 1u || MEM_R32(RECOVERY_COUNT) != 1u ||
        seed.r[2] != 0x321u || seed.flow_kind != SR_FLOW_NONE ||
        seed.flow_target != 0u) {
        fprintf(stderr,
                "FAIL handler=%u followup=%u stale=%u outer=%u tail=%u vector=%u "
                "recovery=%u v0=0x%08x flow=%u target=0x%08x\n",
                handler_calls, followup_calls, followup_saw_stale_flow,
                MEM_R32(OUTER_COUNT), MEM_R32(TAIL_SENTINEL),
                MEM_R32(VECTOR_COUNT), MEM_R32(RECOVERY_COUNT), seed.r[2],
                seed.flow_kind, seed.flow_target);
        return 1;
    }
    puts("generated tail ERET and scheduler reuse: OK");
    return 0;
}
'''
        source = "\n\n".join((
            prefix, outer, middle, leaf, eret_vector, recovery, followup, suffix,
        ))
        env = os.environ.copy()
        compiler = CC
        include_flags = []
        # A host without SDL3 development headers (the hosted Python gate) gets a
        # test-only timer shim below; sched.c reaches SDL for its monotonic clock
        # and precise delay only, and the fixture runs with VBLANK pacing off.
        sdl_available = os.name == "nt"
        if os.name == "nt":
            msys_bin = Path("C:/msys64/ucrt64/bin")
            msys_usr_bin = Path("C:/msys64/usr/bin")
            msys_gcc = msys_bin / "gcc.exe"
            if msys_gcc.exists():
                compiler = str(msys_gcc)
                env["PATH"] = os.pathsep.join(
                    [str(msys_bin), str(msys_usr_bin), env.get("PATH", "")]
                )
                include_flags.append(f"-I{msys_bin.parent / 'include'}")
        else:
            pkg_config = shutil.which("pkg-config")
            if pkg_config:
                sdl_flags = subprocess.run(
                    [pkg_config, "--cflags", "sdl3"], capture_output=True, text=True,
                )
                if sdl_flags.returncode == 0:
                    include_flags.extend(sdl_flags.stdout.split())
                    sdl_available = True
        env["SR_NOVBPACE"] = "1"

        with tempfile.TemporaryDirectory(prefix="lle_sched_eret_") as tmp:
            work = Path(tmp)
            source_path = work / "fixture.c"
            exe_path = work / "fixture.exe"
            source_path.write_text(source, encoding="ascii", newline="\n")
            if not sdl_available:
                shim_dir = work / "sdl_timer_shim"
                (shim_dir / "SDL3").mkdir(parents=True)
                (shim_dir / "SDL3" / "SDL_timer.h").write_text(
                    SDL_TIMER_SHIM, encoding="ascii", newline="\n")
                include_flags.extend((f"-I{shim_dir}", "-D_POSIX_C_SOURCE=200809L"))
            common = [
                "-std=c11", "-O0", "-g", "-fno-strict-aliasing",
                "-ffunction-sections", "-fdata-sections", "-Isrc/rt",
                "-Isrc/core", *include_flags, "-DSR_SDL3VK",
                "-D_CRT_SECURE_NO_WARNINGS", "-Wall", "-Wextra",
                "-DSR_FLIGHT_RECORDER_LINKED", "-DPERF_AOT_INSTRUCTIONS=0",
                "-DSR_PUBLIC_SAFE", '-DSR_BUILD_DIR="build/lle-integrated"',
            ]

            objects = []

            def run_checked(args):
                completed = subprocess.run(
                    args, cwd=ROOT, env=env, capture_output=True, text=True,
                )
                self.assertEqual(
                    completed.returncode, 0, completed.stderr + completed.stdout,
                )

            harness_obj = work / "fixture.o"
            run_checked([compiler, *common, "-c", str(source_path), "-o", str(harness_obj)])
            objects.append(harness_obj)
            production_sources = (
                "recomp.c", "sched.c", "sr_coro.c", "nested_frames.c",
                "flight_recorder.c", "guest_interp.c", "cpu_lle.c",
                "domain_mode.c", "stale_code.c", "vfpu_tables.c", "perf.c",
            )
            for name in production_sources:
                obj = work / (Path(name).stem + ".o")
                run_checked([
                    compiler, *common, "-c", str(ROOT / "src" / "rt" / name),
                    "-o", str(obj),
                ])
                objects.append(obj)

            run_checked([
                compiler, *(str(obj) for obj in objects), "-Wl,--gc-sections",
                "-lm", "-o", str(exe_path),
            ])
            ran = subprocess.run(
                [str(exe_path)], cwd=work, env=env,
                capture_output=True, text=True, timeout=60,
            )
            self.assertEqual(ran.returncode, 0, ran.stderr + ran.stdout)
            self.assertIn("generated tail ERET and scheduler reuse: OK", ran.stdout)


class CpuLleSourcesTests(unittest.TestCase):
    """Source-owned COP0/exception implementation matches spec 3.2/3.3."""

    def test_header_defines_cop0_registers(self):
        text = CPU_LLE_H.read_text(encoding="utf-8")
        for name, value in (("SR_CP0_BADVADDR", 8), ("SR_CP0_COUNT", 9),
                            ("SR_CP0_COMPARE", 11), ("SR_CP0_STATUS", 12),
                            ("SR_CP0_CAUSE", 13), ("SR_CP0_EPC", 14),
                            ("SR_CP0_PRID", 15), ("SR_CP0_CONFIG", 16)):
            self.assertRegex(text, rf"{name}\s*=?\s*{value}u?")

    def test_header_defines_exceptions_and_flows(self):
        text = CPU_LLE_H.read_text(encoding="utf-8")
        for name, value in (("SR_EXC_INT", 0), ("SR_EXC_ADEL", 4),
                            ("SR_EXC_ADES", 5), ("SR_EXC_SYS", 8),
                            ("SR_EXC_BP", 9), ("SR_EXC_RI", 10),
                            ("SR_EXC_CPU", 11), ("SR_EXC_OV", 12),
                            ("SR_FLOW_NONE", 0), ("SR_FLOW_EXCEPTION", 1),
                            ("SR_FLOW_ERET", 2), ("SR_FLOW_INTERRUPT", 3),
                            ("SR_FLOW_FATAL", 4)):
            self.assertRegex(text, rf"{name}\s*=?\s*{value}u?")

    def test_header_declares_spec_helpers(self):
        text = CPU_LLE_H.read_text(encoding="utf-8")
        for proto in (
                r"sr_cp0_mfc0\s*\(",
                r"sr_cp0_mtc0\s*\(",
                r"sr_cpu_raise_exception\s*\(",
                r"sr_cpu_eret\s*\(",
                r"sr_cpu_poll\s*\(",
                r"sr_cpu_in_kernel\s*\(",
                r"sr_cpu_clear_flow\s*\("):
            self.assertRegex(text, proto)

    def test_raise_sets_epc_cause_exl_vector(self):
        text = CPU_LLE_C.read_text(encoding="utf-8")
        self.assertIn("SR_CP0_EPC", text)
        self.assertIn("SR_CAUSE_BD", text)
        self.assertIn("SR_STATUS_EXL", text)
        self.assertIn("SR_FLOW_EXCEPTION", text)
        self.assertIn("sr_exec_span_owns_fetch", text)
        self.assertNotIn("sr_guest_span_readable", text)

    def test_status_cause_writes_are_masked(self):
        text = CPU_LLE_C.read_text(encoding="utf-8")
        self.assertIn("SR_STATUS_WRITABLE_MASK", text)
        self.assertIn("SR_CAUSE_IP_SW_MASK", text)
        header = CPU_LLE_H.read_text(encoding="utf-8")
        mask_def = re.search(r"#define SR_STATUS_WRITABLE_MASK.*?\)", header, re.DOTALL)
        self.assertIsNotNone(mask_def)
        self.assertNotIn("SR_STATUS_ERL", mask_def.group(0))

    def test_interp_results_cover_exception_flows(self):
        text = GUEST_INTERP_H.read_text(encoding="utf-8")
        self.assertIn("SR_GUEST_INTERP_EXCEPTION", text)
        self.assertIn("SR_GUEST_INTERP_ERET", text)


class MakefileWiringTests(unittest.TestCase):
    """The new selftest is wired like the existing native selftests."""

    def test_cpu_lle_selftest_target_exists(self):
        self.assertIn("cpu-lle-selftest:", MAKEFILE)
        recipe = MAKEFILE.split("cpu-lle-selftest:", 1)[1].split("\n\n", 1)[0]
        self.assertIn("src/rt/cpu_lle_selftest.c", recipe)
        self.assertIn("src/rt/guest_interp.c", recipe)
        self.assertIn("$(BUILD_DIR)/cpu_lle_selftest.exe", recipe)

    def test_cpu_lle_selftest_is_phony(self):
        block = re.search(r"(?ms)^PUBLIC_TARGETS := \\\n(.*?)(?=^INTERNAL_TARGETS :=)", MAKEFILE)
        self.assertIsNotNone(block)
        self.assertIn("cpu-lle-selftest", block.group(1).split())
        self.assertIn(".PHONY: $(PUBLIC_TARGETS) $(INTERNAL_TARGETS)", MAKEFILE)

    def test_runtime_source_lists_carry_cpu_lle(self):
        for var in ("RT_SRCS", "PORTABLE_CORE_SRCS"):
            block = re.search(rf"^{var}\s*:?=\s*(.*?)(?=\n\S|\Z)",
                              MAKEFILE, re.MULTILINE | re.DOTALL)
            self.assertIsNotNone(block, var)
            self.assertIn("src/rt/cpu_lle.c", block.group(1))

    def test_every_guest_interp_link_also_links_cpu_lle(self):
        offenders = []
        for number, raw in enumerate(MAKEFILE.splitlines(), start=1):
            if "src/rt/guest_interp.c" in raw and "-o " in raw:
                if "src/rt/cpu_lle.c" not in raw:
                    offenders.append(f"Makefile:{number}: {raw.strip()}")
        self.assertEqual(offenders, [])

    def test_every_python_harness_link_also_links_cpu_lle(self):
        # tools/*.py inline gcc commands that link guest_interp.c must also
        # link cpu_lle.c (same drift class as test_native_gate_stub_link).
        # Only quoted path operands count, so prose mentions in docstrings
        # are not mistaken for link surfaces; only files that actually build
        # a link command (an "-o" output operand) are surfaces at all, so
        # audit-only tests that quote the filename are excluded.
        # NOTE: .github/workflows/ci.yml carries two more such commands
        # (vfpu_interp_selftest + its ASan twin); agents may not edit
        # .github/, so that hunk is a maintainer followup, not asserted here.
        offenders = []
        for path in sorted((ROOT / "tools").glob("*.py")):
            text = path.read_text(encoding="utf-8", errors="replace")
            if re.search(r"""["']guest_interp\.c["']""", text) and '"-o "' in text:
                if "cpu_lle.c" not in text:
                    offenders.append(path.name)
        self.assertEqual(offenders, [])

    def test_native_core_tests_depends_on_cpu_lle_selftest(self):
        self.assertRegex(MAKEFILE, r"(?m)^native-core-tests:\s*cpu-lle-selftest\b")


def _mem(op, base, rt, imm):
    return (op << 26) | (base << 21) | (rt << 16) | (imm & 0xFFFF)


LW = _mem(0x23, 13, 14, 4)
SW = _mem(0x2B, 13, 14, 4)
LB = _mem(0x20, 13, 14, 1)
LWL = _mem(0x22, 13, 14, 1)
LWR = _mem(0x26, 13, 14, 1)
SWL = _mem(0x2A, 13, 14, 1)
SWR = _mem(0x2E, 13, 14, 1)


def _vfpu(op, base=13, vt=0, off=0):
    return (op << 26) | (base << 21) | (vt << 16) | (off & 0xFFFF)


LVS = _vfpu(0x32, 13, 0, 0)
SVS = _vfpu(0x3A, 13, 0, 0)
LVQ = _vfpu(0x36, 13, 0, 0)
SVQ = _vfpu(0x3E, 13, 0, 0)
LVL = _vfpu(0x35, 13, 0, 0)
LVR = _vfpu(0x35, 13, 0, 2)
SVL = _vfpu(0x3D, 13, 0, 0)
SVR = _vfpu(0x3D, 13, 0, 2)


class LleDataAccessGuardTests(unittest.TestCase):
    """Loads and stores are address-checked under --lle-cpu (spec 3.3).

    Failing-before evidence: on the base tree LLE_ACCESS and
    _lle_access_stmt do not exist, and effect(..., lle_cpu=True) emits the
    same bare MEM_* access as the default lane, so a user-mode kernel-segment
    load is masked into RAM and silently succeeds.
    """

    def test_lw_is_guarded(self):
        stmt, saddr, ssize = codegen.effect(0x1000, LW, lle_cpu=True)
        self.assertIn("sr_cpu_guard_access(s, _ea, 4u, 0, 0x00001000u", stmt)
        self.assertIn("MEM_R32(_ea)", stmt)
        self.assertIsNone(saddr)
        self.assertEqual(ssize, 0)

    def test_sw_is_guarded_and_keeps_store_metadata(self):
        stmt, saddr, ssize = codegen.effect(0x1000, SW, lle_cpu=True)
        self.assertIn("sr_cpu_guard_access(s, _ea, 4u, 1, 0x00001000u", stmt)
        self.assertIn("MEM_W32_PC(_ea,", stmt)
        self.assertEqual(saddr, "(s->r[13] + 0x00000004u)")
        self.assertEqual(ssize, 4)

    def test_byte_access_is_guarded_at_width_one(self):
        # A byte has no alignment constraint, but the segment check still applies.
        stmt, _, _ = codegen.effect(0x1000, LB, lle_cpu=True)
        self.assertIn("sr_cpu_guard_access(s, _ea, 1u, 0,", stmt)

    def test_guarded_access_leaves_the_body_on_fault(self):
        stmt, _, _ = codegen.effect(0x1000, LW, lle_cpu=True)
        self.assertIn("{ sr_end(s, 0u, 0); return; }", stmt)

    def test_effective_address_is_evaluated_once(self):
        stmt, _, _ = codegen.effect(0x1000, LW, lle_cpu=True)
        self.assertEqual(stmt.count("uint32_t _ea ="), 1)

    def test_unaligned_access_forms_are_never_guarded(self):
        # lwl/lwr/swl/swr exist to cross an alignment boundary; a misaligned
        # effective address is their normal case, not an address error.
        for name, word in (("lwl", LWL), ("lwr", LWR), ("swl", SWL), ("swr", SWR)):
            with self.subTest(form=name):
                lle, _, _ = codegen.effect(0x1000, word, lle_cpu=True)
                default, _, _ = codegen.effect(0x1000, word)
                self.assertNotIn("sr_cpu_guard_access", lle)
                self.assertEqual(lle, default)

    def test_delay_slot_access_carries_the_branch_pc(self):
        lines = codegen.delay_slot_lines(0x1004, LW, 0x1000, lle_cpu=True)
        body = "\n".join(lines)
        # instr_pc is the load, branch_pc is the branch, in_delay is set.
        self.assertIn("0x00001004u, 0x00001000u, 1u)", body)

    def test_default_lane_access_is_unchanged(self):
        for name, word in (("lw", LW), ("sw", SW), ("lb", LB)):
            with self.subTest(form=name):
                stmt, _, _ = codegen.effect(0x1000, word)
                self.assertNotIn("sr_cpu_guard_access", stmt)
                self.assertNotIn("_ea", stmt)

    def test_default_delay_slot_access_is_unchanged(self):
        lines = codegen.delay_slot_lines(0x1004, LW, 0x1000)
        self.assertNotIn("sr_cpu_guard_access", "\n".join(lines))

    def test_guard_helper_exists_in_the_runtime(self):
        header = CPU_LLE_H.read_text(encoding="utf-8")
        source = CPU_LLE_C.read_text(encoding="utf-8")
        self.assertIn("sr_cpu_guard_access", header)
        self.assertIn("sr_cpu_data_access_fault", header)
        self.assertIn("int sr_cpu_guard_access(", source)


class LleVfpuGuardTests(unittest.TestCase):
    """VFPU loads/stores carry the measured alignment guard under --lle-cpu.

    Failing-before evidence: vfpu_effect() ignored lle_cpu, so effect(...,
    lle_cpu=True) for lv.s/lv.q/sv.s/sv.q emitted the same bare access as the
    default lane with no sr_cpu_guard_access call.
    """

    def test_lvs_guarded_at_width_four(self):
        stmt, saddr, ssize = codegen.effect(0x1000, LVS, lle_cpu=True)
        self.assertIn("sr_cpu_guard_access(s, _ea, 4u, 0, 0x00001000u", stmt)
        self.assertIn("MEM_R32(_ea)", stmt)
        self.assertIsNone(saddr)
        self.assertEqual(ssize, 0)

    def test_svs_guarded_at_width_four_store(self):
        stmt, saddr, ssize = codegen.effect(0x1000, SVS, lle_cpu=True)
        self.assertIn("sr_cpu_guard_access(s, _ea, 4u, 1, 0x00001000u", stmt)
        self.assertIn("MEM_W32_PC(_ea,", stmt)
        self.assertEqual(ssize, 4)

    def test_lvq_guarded_at_width_sixteen(self):
        stmt, saddr, ssize = codegen.effect(0x1000, LVQ, lle_cpu=True)
        self.assertIn("sr_cpu_guard_access(s, _a, 16u, 0, 0x00001000u", stmt)
        self.assertIsNone(saddr)
        self.assertEqual(ssize, 0)

    def test_svq_guarded_at_width_sixteen_store(self):
        stmt, saddr, ssize = codegen.effect(0x1000, SVQ, lle_cpu=True)
        self.assertIn("sr_cpu_guard_access(s, _a, 16u, 1, 0x00001000u", stmt)
        self.assertEqual(ssize, 16)

    def test_vfpu_left_right_never_guarded(self):
        # lvl/lvr/svl/svr bypass like lwl/lwr/swl/swr (width 0, PSP-A3-11).
        for name, word in (("lvl.q", LVL), ("lvr.q", LVR),
                           ("svl.q", SVL), ("svr.q", SVR)):
            with self.subTest(form=name):
                lle, _, _ = codegen.effect(0x1000, word, lle_cpu=True)
                default, _, _ = codegen.effect(0x1000, word)
                self.assertNotIn("sr_cpu_guard_access", lle)
                self.assertEqual(lle, default)

    def test_delay_slot_vfpu_carries_the_branch_pc(self):
        lines = codegen.delay_slot_lines(0x1004, LVQ, 0x1000, lle_cpu=True)
        body = "\n".join(lines)
        self.assertIn("sr_cpu_guard_access(s, _a, 16u, 0,", body)
        self.assertIn("0x00001004u, 0x00001000u, 1u)", body)

    def test_default_lane_vfpu_is_unchanged(self):
        for name, word in (("lv.s", LVS), ("sv.s", SVS),
                           ("lv.q", LVQ), ("sv.q", SVQ)):
            with self.subTest(form=name):
                stmt, _, _ = codegen.effect(0x1000, word)
                self.assertNotIn("sr_cpu_guard_access", stmt)


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "--generate-lle-aot-flow-fixture":
        output = Path(sys.argv[2])
        output.parent.mkdir(parents=True, exist_ok=True)
        with output.open("w", encoding="ascii", newline="\n") as generated_file:
            generated_file.write(_emit_generated_fatal_flow_fixture())
            generated_file.write("\n")
            generated_file.write(_emit_llsc_parity_fixture())
            generated_file.write("\n")
    elif len(sys.argv) == 1:
        unittest.main()
    else:
        raise SystemExit(
            "usage: test_cpu_lle.py [--generate-lle-aot-flow-fixture OUTPUT.c]"
        )
