# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025-2026 the psp-recomp authors

import json
from pathlib import Path
import subprocess
import tempfile
import unittest

from tools import history_audit, publication_policy, public_export
from tools.build_public_export import (
    check_unresolved_legal_blockers,
    export_sanitized_public_tree,
    history_audit_gate_result,
    is_public_safe_export_tree,
    run_all_publication_gates,
    run_history_audit,
    run_publish_audit,
    run_sbom_verification,
)

# The same tests run in the source checkout and in a materialized public-safe
# candidate. Profile-excluded files are asserted by path/policy using synthetic
# conditions; publication-security coverage must not disappear behind skips.
_PUBLIC_SAFE_TREE = is_public_safe_export_tree()


def _git(argv: list[str], cwd: Path) -> None:
    subprocess.run(["git", *argv], cwd=cwd, check=True, capture_output=True)


def _init_synthetic_repo(root: Path, sensitive: bool) -> None:
    """Build a small multi-commit git repository in *root*.

    ``sensitive=True`` drops a DEFINITE_SECRET token into one commit so the
    history audit must fail closed; ``sensitive=False`` produces a sanitized
    multi-commit history that must pass.  The repo is deliberately tiny and
    synthetic: no private bytes, no network, no shared refs.
    """
    for argv in (
        ("init", "-q"),
        ("config", "user.email", "t@example.invalid"),
        ("config", "user.name", "history-audit-test"),
    ):
        _git(argv, root)
    (root / "safe.txt").write_text("safe\n", encoding="utf-8")
    _git(["add", "safe.txt"], root)
    _git(["commit", "-qm", "safe base"], root)
    (root / "second.txt").write_text("also safe\n", encoding="utf-8")
    _git(["add", "second.txt"], root)
    _git(["commit", "-qm", "second commit"], root)
    if sensitive:
        (root / "legacy_keys.txt").write_text(
            "legacy token " + "ghp_" + "012345678901234567890123456789012345" + "\n",
            encoding="utf-8",
        )
        _git(["add", "legacy_keys.txt"], root)
        _git(["commit", "-qm", "legacy artifact"], root)


class TestPublicExport(unittest.TestCase):
    def test_in_place_metadata_is_idempotent_across_its_own_previous_bytes(self):
        policy = publication_policy.load_policy(Path("assets/public_source_profile.json"))
        common = [("README.md", b"source bytes\n")]
        first = public_export.build_document(
            policy,
            common + [(public_export.EXPORT_PATH, b"old generated bytes\n")],
            provenance_ledger=b"ledger bytes\n",
            manifest=b"manifest bytes\n",
        )
        first_bytes = json.dumps(first, indent=2, ensure_ascii=False).encode("utf-8") + b"\n"
        second = public_export.build_document(
            policy,
            common + [(public_export.EXPORT_PATH, first_bytes)],
            provenance_ledger=b"ledger bytes\n",
            manifest=b"manifest bytes\n",
        )
        self.assertEqual(first, second)
        self.assertNotIn("source_tree", first)

    def test_legal_blockers_fail_closed_without_profile(self):
        res = check_unresolved_legal_blockers(public_safe_profile=False)
        self.assertFalse(res.passed)
        self.assertIn("OPEN PUBLICATION BLOCKERS", res.detail)

    def test_legal_blockers_pass_with_public_safe_profile(self):
        res = check_unresolved_legal_blockers(public_safe_profile=True)
        self.assertTrue(res.passed)
        self.assertIn("PUBLIC-SAFE PROFILE ACTIVE", res.detail)

    def test_publish_audit_gate(self):
        res = run_publish_audit()
        self.assertTrue(res.passed, f"publish_audit gate failed: {res.detail}")

    def test_history_audit_gate_fails_closed_on_legacy_history(self):
        # A legacy/dirty history must fail closed regardless of the ambient
        # checkout's own refs: build a synthetic repo whose history contains a
        # definite secret and prove the audit and the publication gate reject it.
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _init_synthetic_repo(root, sensitive=True)
            report = history_audit.generate_full_history_audit_report(root)
            self.assertEqual(report["status"], "FAIL")
            self.assertGreater(report["summary"]["total_findings"], 0)
            self.assertEqual(report["summary"]["category_counts"].get("DEFINITE_SECRET", 0), 1)
            res = history_audit_gate_result(report)
            self.assertFalse(res.passed, "legacy dirty history must fail closed")
            self.assertIn("SENSITIVE FINDINGS DETECTED", res.detail)

    def test_history_audit_gate_passes_on_sanitized_history(self):
        # A sanitized multi-commit history must pass: the gate criterion is the
        # audit state (zero findings), never the commit count. This is the
        # current intended public baseline (sanitized main plus fresh export).
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _init_synthetic_repo(root, sensitive=False)
            report = history_audit.generate_full_history_audit_report(root)
            self.assertEqual(report["status"], "OK")
            self.assertEqual(report["summary"]["total_findings"], 0)
            self.assertGreater(report["baseline"]["total_commits"], 1)
            res = history_audit_gate_result(report)
            self.assertTrue(res.passed, "sanitized multi-commit history must pass")
            self.assertIn("0 sensitive findings", res.detail)

    def test_sbom_verification_gate(self):
        res = run_sbom_verification()
        self.assertTrue(res.passed, f"sbom_verification gate failed: {res.detail}")

    def test_run_all_publication_gates(self):
        results = run_all_publication_gates(public_safe_profile=True)
        self.assertEqual(len(results), 4)
        history = results[2]
        if history.passed:
            # Sanitized history: the intended public baseline is fully green.
            for gate in results:
                self.assertTrue(gate.passed, f"Gate '{gate.name}' failed: {gate.detail}")
        else:
            # Dirty legacy ancestry present in this checkout: the history gate
            # must stay visibly failed, but non-blocking because the legacy
            # ancestry is not exported into the fresh sanitized root. The other
            # gates must still pass under the public-safe profile.
            self.assertFalse(history.blocking, "old history is non-blocking only because it is not exported")
            self.assertIn("not exported", history.name)
            for gate in results[:2] + results[3:]:
                self.assertTrue(gate.passed, f"Gate '{gate.name}' failed: {gate.detail}")

    def test_dry_run_export(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "export_repo"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True, dry_run=True)
            self.assertTrue(success)

    def test_public_safe_export_excludes_unreviewed_components(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "public_export"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True)
            self.assertTrue(success, "public-safe export should succeed at the tree level")
            # Core toolkit and required publication files are present.
            self.assertTrue((target_path / "src" / "rt" / "recomp.c").is_file())
            self.assertTrue((target_path / "LICENSE").is_file())
            self.assertTrue((target_path / "NOTICE.md").is_file())
            # Unresolved PGF/font and PGD/amctrl surfaces are excluded from the tree.
            for rel in (
                "font/jpn0.pgf",
                "font/kr0.pgf",
                "font/ltn0.pgf",
                "font/ltn8.pgf",
                "src/rt/pgf.c",
                "src/rt/pgf.h",
                "src/rt/pgd.c",
                "src/rt/pgd.h",
                "tools/pgd_decrypt.py",
                "tools/pgd_e2e_harness.c",
                "tools/test_pgd_c.py",
                "tools/test_pgd_decrypt.py",
            ):
                self.assertFalse((target_path / rel).exists(), f"{rel} must be excluded")
            # Provenance metadata records the profile, source commit, and exclusions.
            metadata_path = target_path / "PUBLIC_EXPORT.json"
            self.assertTrue(metadata_path.is_file())
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
            self.assertEqual(metadata["profile"], "public-safe-v1")
            self.assertEqual(
                metadata["excluded_file_count"],
                len(metadata.get("excluded_present_paths", [])),
            )
            self.assertGreater(len(metadata["excluded_paths"]), 0)
            self.assertIn("font/*.pgf", metadata["excluded_globs"])
            self.assertIn("src/rt/pgd.c", metadata["excluded_paths"])
            self.assertTrue(metadata.get("source_tree"))

    def test_public_safe_export_audits_in_public_scope_in_its_own_pre_commit(self):
        # The exported tree lacks the manifest-declared excluded components by
        # design; the export's own publication-safety pre-commit hook must run
        # in public scope so contributor commits do not fail on their absence.
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "public_export"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True)
            self.assertTrue(success, "public-safe export should succeed at the tree level")
            pre_commit_text = (target_path / ".pre-commit-config.yaml").read_text(encoding="utf-8")
            self.assertIn(
                "entry: python tools/publish_audit.py --tracked-only --public-scope",
                pre_commit_text,
            )
            self.assertNotIn(
                "entry: python tools/publish_audit.py --tracked-only\n",
                pre_commit_text.replace("--public-scope", ""),
            )

    def test_profile_excludes_unreviewed_components_without_materializing_them(self):
        from tools import public_candidate

        profile = public_candidate.load_profile(Path("assets/public_source_profile.json"))
        for rel in (
            "font/jpn0.pgf",
            "src/rt/pgf.c",
            "src/rt/pgd.c",
            "tools/pgd_decrypt.py",
        ):
            self.assertTrue(public_candidate.is_excluded(rel, profile), rel)


if __name__ == "__main__":
    unittest.main()
