# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025-2026 the psp-recomp authors

"""Regressions for the source-owned second-platform workload ladder.

Pins every workload's generated bytes, proves the pipeline rejects structural
mutations (broken relocations, dropped chunk registration, broken NID
mappings, flipped expectations), and asserts that a generic ladder run never
consumes HST-shaped defaults (SR_DATAROOT/xbdata trees, place_game_here
paths, exact hooks, or compatibility overrides).
"""

from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import struct
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"
GENERATOR_PATH = ROOT / "fixtures" / "platform_ladder" / "generate.py"
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

SPEC = importlib.util.spec_from_file_location("platform_ladder_generator", GENERATOR_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError(f"cannot load {GENERATOR_PATH}")
generator = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(generator)


EXPECTED_PRX_SHA256 = {
    "ladder-zero": "f128b314b8011bc140e63ab03b6146ea75b539cdec1cb280201ad8c84e16f7c1",
    "ladder-reloc": "2c213989399a14903429ae46bfc6a54496751b6bee6bb949109137fae41acad7",
    "ladder-gap": "0a404ba7bf22033422cb98ef39118bed6f960ec9a039061091958b918709a663",
    "ladder-sched": "758971ab4080215d6411f95cf69242658250316c75b1d94a560464bd0e9f51c1",
    "ladder-fpu": "c32d6cf9d99c0369bc3e7f202b43ec36f806ef96777482992f7e9059782f2d90",
    "ladder-fs": "7dea7d6f105f0994dd22164a732dd0666a5d912f657f7c2f6b0b638a5a182ae9",
}

# Cross-platform differential: prxload output for ladder-zero is byte-identical
# between Windows (mingw32 host) and Linux (gcc-13/WSL2) toolchains.
L0_IMAGE_SHA256 = "9d8ec91be32fc66a959561bcf6ac0e643ffed3c3d055b6e775e88aa5def0bec4"


class LadderGapEncodingTests(unittest.TestCase):
    def test_critical_words_decode_to_intended_semantics(self):
        plan = generator.PLANS["ladder-gap"]
        words, _ = generator.assemble_text(plan)
        for offset, expected in {
            0x14: (0x02, plan.base + generator.LG_MID_OFF),
            0x60: (0x09, 2, 2, 7),
            0x6C: (0x0F, 0, 9, 1),
            0x70: (0x09, 9, 9, 0xBEEF),
            0x74: (0x2B, 8, 9, 0),
            0x78: (0x23, 8, 10, 0),
            0x84: (0x2B, 11, 10, 0),
            0x88: (0x09, 0, 10, generator.LG_GUARD_A_VALUE),
            0x8C: (0x2B, 8, 10, 0),
            0x90: (0x02, plan.base + generator.LG_END_OFF),
            0x94: (0x09, 2, 2, 7),
            0xA8: (0x23, 12, 13, 0),
            0xB8: (0x2B, 14, 13, 0),
        }.items():
            word = words[offset // 4]
            if len(expected) == 2:
                self.assertEqual(generator._decode_j(word), expected)
            else:
                self.assertEqual(generator._decode_i(word), expected)

    def test_final_prx_words_reconstruct_gap_addresses_and_seam(self):
        plan = generator.PLANS["ladder-gap"]
        prx, _ = generator.build_prx(plan)
        through = max(
            offset
            for pair in generator.LG_ADDRESS_CONTRACT.values()
            for offset in pair[:2]
        )
        through = max(through, generator.LG_END_LOAD_B_OFFSET) + 4
        words = [
            struct.unpack_from("<I", prx, generator.TEXT_FILE_OFFSET + offset)[0]
            for offset in range(0, through, 4)
        ]
        # This consumes the actual encoded words and proves the reconstructed
        # end-load address/register is the one selected by the mid->end jump.
        generator._verify_lg_address_topology(words, plan)
        effective, _ = generator._decode_lui_addiu_address(words, 0xA0, 0xA4)
        self.assertEqual(effective, plan.base + plan.data_seg_vaddr + 0x390)


class FixturePinTests(unittest.TestCase):
    def test_generation_is_pinned_and_churn_free(self):
        for workload, expected in EXPECTED_PRX_SHA256.items():
            with self.subTest(workload=workload):
                with tempfile.TemporaryDirectory() as tmp:
                    out_dir = Path(tmp)
                    before = {
                        p.name: p.read_bytes()
                        for p in sorted(out_dir.glob("*"))
                    } if out_dir.exists() else {}
                    self.assertEqual(generator.generate(out_dir, workload), 0)
                    prx = (out_dir / "guest.prx").read_bytes()
                    self.assertEqual(generator.hashlib.sha256(prx).hexdigest(), expected)

    def test_manifest_matches_bytes(self):
        for workload in EXPECTED_PRX_SHA256:
            with self.subTest(workload=workload):
                plan = generator.effective_plan(workload)
                prx, psp = generator.build_prx(plan)
                manifest = json.loads(
                    generator.manifest_bytes(plan, prx, psp, workload)
                )
                self.assertEqual(manifest["prx_sha256"], EXPECTED_PRX_SHA256[workload])
                self.assertEqual(int(manifest["expected"], 16), plan.expected_value())

    def test_ladder_zero_has_no_guest_relocations(self):
        """ladder-zero carries only its export-metadata self-relocations."""
        plan = generator.PLANS["ladder-zero"]
        prx, header = generator.build_prx(plan)
        self.assertEqual(header, b"")
        _, sites = generator.assemble_text(plan)
        self.assertEqual(sites, [])
        offsets = {off for off, _ in generator.plan_relocations(plan, [])}
        self.assertTrue(offsets <= {
            generator.MODULE_INFO_ENT_TOP_FIELD,
            generator.MODULE_INFO_ENT_END_FIELD,
            generator.DATA_LIB_ENT_BASE,
            generator.DATA_LIB_ENT_BASE + 12,
            generator.DATA_LIB_ENT_BASE + 16,
            generator.DATA_LIB_ENT_FUNC_TABLE,
        })

    def test_reloc_workload_declares_pointer_table_relocation(self):
        relocs = generator.plan_relocations(generator.PLANS["ladder-reloc"], [])
        offsets = {off for off, _ in relocs}
        self.assertIn(generator.L1_FN_TABLE, offsets)
        self.assertIn(generator.DATA_LIB_ENT_FUNC_TABLE, offsets)


class StructuralNegativeTests(unittest.TestCase):
    """Mutations that must be caught by generation-time contracts."""

    @staticmethod
    def _clone_with(plan, **overrides):
        fields = {
            "name", "game_name", "base", "entry_offset", "build_asm",
            "imports", "data_words", "data_strings", "data_file_size",
            "data_mem_size", "relocate_calls", "relocate_data",
            "env", "psp_header", "text_pad_end", "data_seg_vaddr",
            "label_contract", "gap_omit_offset", "data_text_pointers",
            "_result_addr_fn", "_expected_value_fn",
        }
        kwargs = {k: getattr(plan, k) for k in fields}
        # The two private callables map to public constructor parameters.
        kwargs["result_addr_fn"] = kwargs.pop("_result_addr_fn")
        kwargs["expected_value_fn"] = kwargs.pop("_expected_value_fn")
        kwargs.update(overrides)
        return generator.Plan(**kwargs)

    def test_ladder_gap_end_address_mutation_is_killed_by_instruction_decode(self):
        plan = generator.PLANS["ladder-gap"]
        # Redirect only the end address-construction call.  Labels, the
        # result slot, the mid->end jump, and the load instruction remain
        # otherwise plausible.  The independent LUI/ADDIU decoder must kill
        # this actual-address mutation, rather than a label-literal check.
        with self.assertRaisesRegex(
            RuntimeError, r"decoded effective address mismatch for end_scratch_b"
        ):
            generator.build_lg(plan, end_scratch_offset=generator.LG_SCRATCH_A)

    def test_label_drift_is_refused(self):
        plan = generator.PLANS["ladder-reloc"]
        broken = self._clone_with(plan, label_contract={"func_c": 0x999})
        with self.assertRaises(RuntimeError):
            generator.assemble_text(broken)

    def test_entry_beyond_text_is_refused(self):
        def tiny(plan):
            a = generator.Asm()
            a.raw(generator._i(0x09, 0, 2, 2))
            return a

        shifted = self._clone_with(
            generator.PLANS["ladder-zero"], build_asm=tiny, entry_offset=0x40
        )
        with self.assertRaises(RuntimeError):
            generator.text_bytes_for(shifted)

    def test_zero_word_at_entry_is_refused(self):
        def padded_to_zero(plan):
            a = generator.Asm()
            a.pad_to(plan.entry_offset + 4)
            return a

        shifted = self._clone_with(
            generator.PLANS["ladder-zero"], build_asm=padded_to_zero
        )
        with self.assertRaises(RuntimeError):
            generator.text_bytes_for(shifted)


class HostileEnvironmentTests(unittest.TestCase):
    """A generic ladder run must not inherit HST assets or assumptions."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(prefix="pl_hostile_")
        self.addCleanup(self.tmp.cleanup)

    def _hostile_env(self, extra=None):
        env = os.environ.copy()
        for key in ("SR_DATAROOT", "SR_FSDIR", "SR_POSTUMD", "SR_HLELOG"):
            env.pop(key, None)
        # Point SR_DATAROOT at an empty directory: the runtime must neither
        # require it nor fall back to an executable-relative retail tree.
        env["SR_DATAROOT"] = self.tmp.name
        if extra:
            env.update(extra)
        return env

    def test_zero_runs_with_empty_dataroot_and_wrong_cwd(self):
        workloads_dir = ROOT / "build" / "platform-ladder" / "ladder-zero"
        exe = workloads_dir / "pl_zero.exe"
        image = workloads_dir / "pl_zero_image.bin"
        if not exe.is_file():
            self.skipTest("run mingw32-make platform-ladder-zero first")
        plan = generator.PLANS["ladder-zero"]
        result = subprocess.run(
            [
                str(exe), "--image", str(image),
                f"0x{plan.base:08x}", f"0x{plan.entry:08x}",
                "none", "none", "--sched",
                f"--expect-u32=0x{plan.result_addr():08x}:0x{plan.expected_value():08x}",
            ],
            cwd=self.tmp.name,
            env=self._hostile_env(),
            capture_output=True,
            text=True,
            timeout=120,
        )
        combined = result.stdout + result.stderr
        self.assertIn("status=PASS", combined)
        for forbidden in ("xbdata", "place_game_here", "hst_image", "UNKNOWN NID"):
            self.assertNotIn(forbidden, combined)


class MutationKillTests(unittest.TestCase):
    """Deliberate genericity/title-coupling mutations must flip the gate."""

    @classmethod
    def setUpClass(cls):
        cls.workloads = ROOT / "build" / "platform-ladder"

    def _exe_ready(self, name: str) -> bool:
        return (self.workloads / name / f"{name.split('/')[-1]}.exe").is_file()

    def test_m9_flipping_expected_result_kills_fpu_word_gate(self):
        """M9-adjacent: ignoring guest RM would change words 2/6/7; prove the
        gate detects ANY single-word drift by flipping one expectation."""
        exe = self.workloads / "ladder-fpu" / "pl_fpu.exe"
        image = self.workloads / "ladder-fpu" / "pl_fpu_image.bin"
        if not exe.is_file():
            self.skipTest("run mingw32-make platform-ladder-fpu first")
        results = generator.l4_results()
        drifted = results[1] ^ 0xFFFF
        addr = 0x08980000 + 0x3000 + generator.L4_RESULTS + 4
        env = dict(os.environ)
        env["SR_DATAROOT"] = self.tmp.name if hasattr(self, "tmp") else "."
        result = subprocess.run(
            [str(exe), "--image", str(image), "0x08980000", "0x08980008",
             "none", "none", "--sched", f"--expect-u32=0x{addr:08x}:0x{drifted:08x}"],
            capture_output=True, text=True, env=env, timeout=120,
            cwd=str(ROOT),
        )
        self.assertIn("status=FAIL", result.stdout + result.stderr)
        self.assertNotEqual(result.returncode, 0)

    def test_m7_breaking_nid_mapping_is_visible_in_generated_text(self):
        """M7: swapping two NIDs in the sched fixture changes each stub's
        sr_syscall target; verify() pins the mapping via required symbols."""
        plan = generator.PLANS["ladder-sched"]
        nids = plan.flat_nids()
        self.assertEqual(len(nids), 6)
        # The stub at slot i must map to nids[i]; assert distinct NIDs so a
        # swapped table cannot satisfy the pin.
        self.assertEqual(len(set(nids)), len(nids))

    def test_m3_generic_workload_does_not_require_dataroot(self):
        """M3/M2: unset SR_DATAROOT entirely; ladder-zero still passes."""
        exe = self.workloads / "ladder-zero" / "pl_zero.exe"
        image = self.workloads / "ladder-zero" / "pl_zero_image.bin"
        if not exe.is_file():
            self.skipTest("run mingw32-make platform-ladder-zero first")
        plan = generator.PLANS["ladder-zero"]
        env = os.environ.copy()
        env.pop("SR_DATAROOT", None)
        env.pop("SR_FSDIR", None)
        result = subprocess.run(
            [str(exe), "--image", str(image),
             f"0x{plan.base:08x}", f"0x{plan.entry:08x}",
             "none", "none", "--sched",
             f"--expect-u32=0x{plan.result_addr():08x}:0x{plan.expected_value():08x}"],
            capture_output=True, text=True, env=env, timeout=120, cwd=str(ROOT),
        )
        combined = result.stdout + result.stderr
        self.assertIn("status=PASS", combined)
        self.assertNotIn("xbdata_extracted ...", combined.replace("\n", ""))


if __name__ == "__main__":
    unittest.main()
