# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 the Nakagawa Recomp authors

"""Regression tests for the path-gated CI classifier."""

from __future__ import annotations

import os
from pathlib import Path
import json
import re
import subprocess
import tempfile
import textwrap
import unittest
from unittest import mock
from unittest.mock import patch

try:
    import ci_paths as ci_paths_module
except ModuleNotFoundError:  # Running as ``python -m unittest tools.test_ci_paths``.
    import tools.ci_paths as ci_paths_module

classify = ci_paths_module.classify


class CiPathClassificationTests(unittest.TestCase):
    def test_tools_data_artefacts_do_not_force_the_full_matrix(self) -> None:
        """tools/import_audit_baseline.json is regenerated by every change to the
        HLE registrations. While it was unclassified it counted as an unknown
        path, which sets force_full and pulled in the full matrix on PRs that
        do not touch the affected subsystem -- turning them red for reasons unrelated
        to their content."""
        result = classify(["src/rt/hle.c", "tools/import_audit_baseline.json"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")

    def test_oracle_manifest_is_python_tooling_data(self) -> None:
        result = classify(["tools/psp_oracle/manifest.json"])
        self.assertEqual(result["run_python"], "true")

    def test_docs_only_keeps_expensive_jobs_off(self) -> None:
        # Safe because publication integrity is not path-gated: the ungated
        # hygiene job audits the generated public metadata on every event.
        # PublicationCoverageInvariantTests pins that.
        result = classify(["docs/CI.md", "README.md"])
        self.assertEqual(result["docs_only"], "true")
        self.assertEqual(result["run_markdown"], "true")
        self.assertEqual(result["run_python"], "false")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_windows"], "false")

    def test_tools_readme_runs_the_python_gate_that_guards_it(self) -> None:
        """tools/README.md is Markdown, but tools/test_lint_docs.py compares its module
        index against the tracked tools/ set. Routing the file that can break that
        check to the docs gate only meant the hosted ``python_tests`` job was skipped
        for exactly the edit that breaks it."""
        result = classify(["tools/README.md"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["markdown"], "true")
        self.assertEqual(result["docs_only"], "true")
        # Narrow, not a blanket Markdown routing: ordinary documentation keeps skipping
        # the Python matrix, including the other Markdown file under tools/.
        self.assertEqual(classify(["docs/CI.md"])["run_python"], "false")
        self.assertEqual(classify(["tools/TRACE_FORMAT.md"])["run_python"], "false")

    def test_generated_public_metadata_is_recognised_and_preserves_docs_only(self) -> None:
        """Finding 13 (O-13): generated public metadata must not trigger force_full."""
        result = classify([
            "docs/CI.md",
            "PUBLIC_EXPORT.json",
            "assets/public_provenance_ledger.json",
            "assets/public_source_profile.json",
        ])
        self.assertEqual(result["docs_only"], "true")
        self.assertEqual(result["run_markdown"], "true")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_windows"], "false")
        self.assertEqual(result["security_publication"], "true")
        self.assertEqual(result["run_python"], "true")

    def test_provenance_and_independence_campaign_route_security_publication(self) -> None:
        for path in (
            "docs/INDEPENDENCE_CAMPAIGN.md",
            "docs/provenance/INDEPENDENCE_MODEL.md",
            "docs/provenance/MODIFIED_FILE_NOTICES.json",
            "tools/provenance_record_gap.py",
            "tools/test_provenance_record_gap.py",
        ):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["security_publication"], "true")
                self.assertEqual(result["run_python"], "true")
                if path.startswith("docs/"):
                    self.assertEqual(result["docs_only"], "true")
                    self.assertEqual(result["run_native"], "false")
                    self.assertEqual(result["run_windows"], "false")

    def test_native_changes_run_python_native_and_windows(self) -> None:
        result = classify(["src/rt/sched.c"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")

    def test_python_only_does_not_force_native(self) -> None:
        result = classify(["tools/test_progress_tracker.py"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_windows"], "false")

    def test_codegen_tool_is_native_relevant(self) -> None:
        result = classify(["tools/codegen.py"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")

    def test_cosim_fixture_reaches_the_windows_gate(self) -> None:
        """The AOT/interpreter cosimulation gate only runs in the Windows job.

        Its guest recipe, harness and mutation driver all live under fixtures/,
        so a classification that treated them as inert data would let a change to
        the comparator -- or to the guest it compares -- ship without the gate
        ever executing. That is the false negative this classifier exists to
        prevent.
        """
        for path in (
            "fixtures/cosim/generate.py",
            "fixtures/cosim/cosim_selftest.c",
            "fixtures/cosim/mutate.py",
        ):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true")
                self.assertEqual(result["run_windows"], "true")

    def test_draft_pr_runs_substantive_jobs(self) -> None:
        result = classify(["src/rt/recomp.c"], draft=True)
        self.assertEqual(result["allow_substantive"], "true")
        self.assertEqual(result["run_native"], "true")

    def test_ordinary_main_push_keeps_only_smoke_jobs(self) -> None:
        with patch.dict(os.environ, {"GITHUB_REF": "refs/heads/main"}):
            result = classify(["src/rt/recomp.c"], event_name="push")
        self.assertEqual(result["run_main_smoke"], "true")
        self.assertEqual(result["allow_substantive"], "false")

    def test_workflow_changes_are_full_validation(self) -> None:
        result = classify([".github/workflows/ci.yml"])
        self.assertEqual(result["workflow_ci"], "true")
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")

    def test_empty_or_manual_classification_is_conservative(self) -> None:
        result = classify([], event_name="workflow_dispatch")
        for key in (
            "run_python",
            "run_native",
            "run_windows",
            "run_markdown",
            "run_main_smoke",
            "allow_substantive",
        ):
            self.assertEqual(result[key], "true")

    def test_history_failure_is_conservative(self) -> None:
        result = classify(["<history-unavailable>"])
        for key in ("run_python", "run_native", "run_windows", "run_markdown",
                    "allow_substantive"):
            self.assertEqual(result[key], "true")

    def test_unknown_paths_fail_closed_to_full_validation(self) -> None:
        result = classify(["new-tool-input.dat"])
        for key in ("run_python", "run_native", "run_windows", "run_markdown",
                    "allow_substantive"):
            self.assertEqual(result[key], "true")


class CiPathAdversarialTests(unittest.TestCase):
    """Independent false-negative hunt, written against the classifier rather than with it.

    The failure mode that matters is a build-affecting change classified as
    docs/tooling and therefore skipping a native or Windows gate.  Every case
    here asserts the *expensive* direction.
    """

    NATIVE_RELEVANT = (
        "src/rt/hle.c",
        "src/rt/recomp.h",
        "src/ref/interp.cpp",
        "src/player/main.c",
        "src/core/nk_launch.c",
        "include/whatever.h",
        "Makefile",
        "GNUmakefile",
        "CMakeLists.txt",
        "mk/toolchain.mk",
        "cmake/toolchain.cmake",
        "assets/vfpu/tables.bin",
        "assets/shaders/blit.frag",
        "nk.ps1",
        "nk_manager.ps1",
        "tools/title_codegen_plan.py",
        "tools/title_manifest.py",
        "tools/test_title_manifest.py",
        "assets/title_manifest.schema.json",
        "assets/titles/synthetic.json",
        "tools/codegen.py",
        "tools/prxload.py",
        "tools/imports.py",
        "tools/gen_microtest.py",
        "tools/verify_gates.py",
        "tools/nk_doctor.py",
        "tools/nk_doctor_checks.py",
        "tools/nk_doctor_core.py",
        "tools/nk_safety.ps1",
        "tools/pspdev_lock.py",
        "tests/native/test_player_ui.py",
    )

    def test_every_native_relevant_path_runs_native_and_windows(self) -> None:
        for path in self.NATIVE_RELEVANT:
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true", f"{path} must run native gates")
                self.assertEqual(result["run_windows"], "true", f"{path} must run the Windows gate")
                self.assertEqual(result["docs_only"], "false", f"{path} is not documentation")

    def test_deleted_native_source_still_runs_native_gates(self) -> None:
        """A deletion is a build-affecting change.

        Regression for the ``--diff-filter=ACMR`` defect: that filter dropped
        deletions, so removing a C source while touching a document classified
        as docs-only and skipped the native and Windows compile gates.
        """
        result = classify(["docs/GUIDE.md", "src/rt/audio.c"])
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")
        self.assertEqual(result["docs_only"], "false")

    def test_git_extraction_does_not_filter_out_deletions(self) -> None:
        """Guard the call itself, not just the pure classifier.

        ``--diff-filter=ACMR`` silently omits deleted paths.  Assert the source
        does not reintroduce a filter that can drop a change type.
        """
        source = (Path(__file__).resolve().parent / "ci_paths.py").read_text(encoding="utf-8")
        self.assertNotIn("--diff-filter=ACMR", source)
        for line in source.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            if "--diff-filter" in stripped:
                self.fail(f"unexpected diff-filter narrows the changed-file set: {stripped}")

    def test_renamed_native_source_runs_native_gates(self) -> None:
        result = classify(["src/rt/renamed.c"])
        self.assertEqual(result["run_native"], "true")

    def test_mixed_docs_and_native_is_not_docs_only(self) -> None:
        result = classify(["docs/CI.md", "Makefile"])
        self.assertEqual(result["docs_only"], "false")
        self.assertEqual(result["run_native"], "true")

    def test_repository_metadata_fails_closed(self) -> None:
        for path in (".gitignore", ".gitattributes", "assets/release_manifest.json"):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true", f"{path} is unrecognised and must fail closed")

    def test_dependency_and_hook_metadata_is_recognised(self) -> None:
        """These are covered by the always-on hygiene job, so they need not be full runs.

        Asserted explicitly so a future change that makes them *skip* hygiene is
        caught rather than assumed.
        """
        for path in (".github/dependabot.yml", ".pre-commit-config.yaml"):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["docs_only"], "false")

    def test_workflow_and_classifier_changes_force_full_validation(self) -> None:
        for path in (".github/workflows/ci.yml", "tools/ci_paths.py", "tools/test_ci_paths.py",
                     "tools/ci_test_shards.py", "tools/test_ci_test_shards.py"):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["workflow_ci"], "true")
                self.assertEqual(result["run_native"], "true")

    def test_ready_for_review_runs_substantive_gates(self) -> None:
        result = classify(["src/rt/hle.c"], event_name="pull_request", draft=False)
        self.assertEqual(result["allow_substantive"], "true")
        self.assertEqual(result["run_native"], "true")

    def test_draft_keeps_gates_applicable_and_running(self) -> None:
        """Draft status must not delay path-applicable validation."""
        result = classify(["src/rt/hle.c"], draft=True)
        self.assertEqual(result["allow_substantive"], "true")
        self.assertEqual(result["run_native"], "true")

    def test_draft_unknown_path_runs_full_matrix_and_fails_closed(self) -> None:
        result = classify(["new-tool-input.dat"], draft=True)
        self.assertEqual(result["allow_substantive"], "true")
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")

    def test_workflow_change_on_main_push_still_allows_substantive(self) -> None:
        with patch.dict(os.environ, {"GITHUB_REF": "refs/heads/main"}):
            result = classify([".github/workflows/ci.yml"], event_name="push")
        self.assertEqual(result["allow_substantive"], "true")
        self.assertEqual(result["run_main_smoke"], "true")

    def test_non_main_push_is_not_treated_as_main_smoke(self) -> None:
        with patch.dict(os.environ, {"GITHUB_REF": "refs/heads/feature"}):
            result = classify(["src/rt/hle.c"], event_name="push")
        self.assertEqual(result["run_main_smoke"], "false")
        self.assertEqual(result["allow_substantive"], "true")

    def test_workflow_dispatch_ignores_paths_entirely(self) -> None:
        result = classify(["docs/CI.md"], event_name="workflow_dispatch")
        for key in (
            "run_python",
            "run_native",
            "run_windows",
            "run_markdown",
            "run_main_smoke",
            "allow_substantive",
        ):
            self.assertEqual(result[key], "true")

    def test_manual_dispatch_requests_the_complete_contract(self) -> None:
        result = classify([], event_name="workflow_dispatch")
        for key in (
            "run_python",
            "run_native",
            "run_windows",
            "run_markdown",
            "run_main_smoke",
            "allow_substantive",
        ):
            self.assertEqual(result[key], "true")

    def test_pull_request_does_not_request_main_smoke(self) -> None:
        self.assertEqual(classify(["src/rt/hle.c"], event_name="pull_request")["run_main_smoke"], "false")

    def test_git_extraction_retains_deleted_and_renamed_paths(self) -> None:
        status = "D\tsrc/rt/removed.c\nR100\tsrc/rt/old.c\tdocs/new.md\n"
        self.assertEqual(
            ci_paths_module._parse_changed_paths(status),
            ["src/rt/removed.c", "src/rt/old.c", "docs/new.md"],
        )

    def test_git_extraction_accepts_valid_one_path_statuses(self) -> None:
        status = "A\tsrc/a.c\nM\tsrc/m.c\nD\tsrc/d.c\nT\tsrc/t.c\nU\tsrc/u.c\n"
        self.assertEqual(
            ci_paths_module._parse_changed_paths(status),
            ["src/a.c", "src/m.c", "src/d.c", "src/t.c", "src/u.c"],
        )

    def test_git_extraction_accepts_valid_copy_records(self) -> None:
        status = "C075\tsrc/old.c\tdocs/new.md\n"
        self.assertEqual(
            ci_paths_module._parse_changed_paths(status),
            ["src/old.c", "docs/new.md"],
        )

    def test_git_extraction_accepts_valid_rename_copy_score_boundaries(self) -> None:
        for status in (
            "R000\tsrc/old.c\tdocs/new.md",
            "C000\tsrc/old.c\tdocs/new.md",
            "R075\tsrc/old.c\tdocs/new.md",
            "C075\tsrc/old.c\tdocs/new.md",
            "R100\tsrc/old.c\tdocs/new.md",
            "C100\tsrc/old.c\tdocs/new.md",
        ):
            with self.subTest(status=status):
                self.assertEqual(
                    ci_paths_module._parse_changed_paths(status),
                    ["src/old.c", "docs/new.md"],
                )

    def test_invalid_rename_copy_scores_fail_closed(self) -> None:
        for status in (
            "R\tsrc/old.c\tdocs/new.md",
            "C\tsrc/old.c\tdocs/new.md",
            "R101\tsrc/old.c\tdocs/new.md",
            "C999\tsrc/old.c\tdocs/new.md",
            "Rabc\tsrc/old.c\tdocs/new.md",
            "C-1\tsrc/old.c\tdocs/new.md",
        ):
            with self.subTest(status=status):
                self.assertEqual(
                    ci_paths_module._parse_changed_paths(status),
                    ["<history-unavailable>"],
                )

    def test_malformed_status_records_force_full_classification(self) -> None:
        malformed = (
            "R100\tdocs/foo.md",
            "C075\tsrc/foo.c",
            "M",
            "M\t",
            "garbage",
            "Q\tdocs/foo.md",
            "M\tdocs/foo.md\textra",
            "R100\tdocs/foo.md\tsrc/foo.c\textra",
        )
        for status in malformed:
            with self.subTest(status=status):
                self.assertEqual(ci_paths_module._parse_changed_paths(status), ["<history-unavailable>"])
                result = classify(ci_paths_module._parse_changed_paths(status))
                self.assertEqual(result["run_native"], "true")
                self.assertEqual(result["run_windows"], "true")

    def test_blank_lines_are_ignored_but_mixed_malformed_records_fail_closed(self) -> None:
        self.assertEqual(
            ci_paths_module._parse_changed_paths("\nA\tsrc/a.c\n\nM\tdocs/b.md\n"),
            ["src/a.c", "docs/b.md"],
        )
        self.assertEqual(
            ci_paths_module._parse_changed_paths("A\tsrc/a.c\nR100\tdocs/only.md\n"),
            ["<history-unavailable>"],
        )

    def test_hst_tests_use_their_logical_build_subject(self) -> None:
        for path in (
            "tools/test_hst_manager_manifest.py",
            "tools/test_hst_title_manifest.py",
            "tools/test_hst_doctor.py",
        ):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true")
                self.assertEqual(result["run_windows"], "true")

    def test_codegen_test_uses_its_logical_native_subject(self) -> None:
        result = classify(["tools/test_codegen.py"])
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")

    def test_c_harness_tests_use_their_logical_native_subject(self) -> None:
        for path in (
            "tools/test_dispatch_c.py",
            "tools/test_evf_c.py",
            "tools/test_guestmem_c.py",
            "tools/test_pgd_c.py",
            "tools/test_sdkver_c.py",
            "tools/test_vfs_c.py",
            "tools/test_native_driver_hardening.py",
            "tools/test_ref_run_elf_hardening.py",
            "tools/test_savedata_spans.py",
            "tools/test_sched_invariants.py",
        ):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true")
                self.assertEqual(result["run_windows"], "true")

    def test_python_only_test_keeps_native_gates_off(self) -> None:
        result = classify(["tools/test_progress_tracker.py"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_windows"], "false")

    def test_all_test_tools_follow_logical_subject_predicates(self) -> None:
        tools_root = Path(__file__).resolve().parent
        for test_path in sorted(tools_root.glob("test_*.py")):
            relative = test_path.relative_to(tools_root.parent).as_posix()
            logical = ci_paths_module._logical_tool_path(relative)
            self.assertIsNotNone(logical)
            assert logical is not None
            expected_native = any(
                predicate(logical)
                for predicate in (
                    ci_paths_module._is_workflow_ci,
                    ci_paths_module._is_title_manifest,
                    ci_paths_module._is_build_system,
                    ci_paths_module._is_native_tool,
                )
            )
            result = classify([relative])
            self.assertEqual(result["run_native"] == "true", expected_native, relative)
            self.assertEqual(result["run_windows"] == "true", expected_native, relative)

    @patch.object(ci_paths_module.subprocess, "run")
    def test_git_diff_requests_status_and_rename_information(self, run) -> None:
        run.return_value.stdout = "D\tsrc/rt/removed.c\nR100\tsrc/rt/old.c\tdocs/new.md\n"
        paths = ci_paths_module._changed_files_from_git(
            "pull_request",
            {"pull_request": {"base": {"sha": "base"}}},
        )
        self.assertEqual(paths, ["src/rt/removed.c", "src/rt/old.c", "docs/new.md"])
        args = run.call_args.args[0]
        self.assertIn("--name-status", args)
        self.assertIn("--find-renames", args)

    def test_backslash_and_dotslash_paths_normalise(self) -> None:
        """A Windows-style or ./-prefixed path must not fall through to unknown."""
        self.assertEqual(classify(["src\\rt\\hle.c"])["run_native"], "true")
        self.assertEqual(classify(["./docs/CI.md"])["docs_only"], "true")



class PublicSurfaceRoutingRegressionTests(unittest.TestCase):
    """Publication integrity must be reachable for any published path.

    The published surface is derived from the publication policy, not a
    hand-maintained path list. Publication integrity remains protected by the
    always-on hygiene job; publication-contract paths also route a Python gate.
    """

    def test_public_surface_is_derived_from_the_policy_not_a_hardcoded_list(self) -> None:
        # A tracked implementation file matches no security predicate but is
        # still included by the publication policy.
        self.assertFalse(ci_paths_module._is_security_publication("tools/nk_doctor_checks.py"))
        self.assertTrue(ci_paths_module._is_public_surface("tools/nk_doctor_checks.py"))

    def test_removed_ui_lockfile_is_not_in_public_policy(self) -> None:
        self.assertFalse(ci_paths_module._is_public_surface("interface/package-lock.json"))

    def test_representative_published_classes_are_all_recognised_as_public(self) -> None:
        for path in (
            "tools/nk_doctor_checks.py",            # implementation
            "docs/DEBUGGING.md",                     # documentation
            "tools/test_hst_doctor.py",              # synthetic fixture
            "assets/public_provenance_ledger.json",  # generated public metadata
            "PUBLIC_EXPORT.json",                    # generated public export
            "assets/public_source_profile.json",     # the policy itself
            "docs/SETUP.md",                         # a removed path arrives by name
        ):
            with self.subTest(path=path):
                self.assertEqual(classify([path])["public_surface"], "true")

    def test_security_publication_is_no_longer_a_dead_output(self) -> None:
        # It was computed and exported while feeding no routing decision at all,
        # so a change to the publication contract document routed no Python gate.
        result = classify(["docs/PUBLICATION_READINESS.md"])
        self.assertEqual(result["security_publication"], "true")
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(classify(["tools/publish_audit.py"])["run_python"], "true")

    def test_unreadable_policy_fails_closed_to_public(self) -> None:
        ci_paths_module._public_policy.cache_clear()
        try:
            with mock.patch.object(ci_paths_module, "_public_policy", return_value=None):
                self.assertTrue(ci_paths_module._is_public_surface("anything/at/all.txt"))
        finally:
            ci_paths_module._public_policy.cache_clear()

    def test_a_new_public_path_still_fails_closed_to_full_validation(self) -> None:
        self.assertEqual(classify(["src/rt/brand_new_thing.c"])["run_python"], "true")


_SYNTHETIC_MAKEFILE = textwrap.dedent(
    """\
    # Synthetic Makefile for the recipe-only classifier.
    CC ?= gcc
    CFLAGS := -O2 -Wall
    PUBLIC_TARGETS := lint-docs ui-tests
    .PHONY: $(PUBLIC_TARGETS) report

    build/%.o: src/%.c
    \t$(CC) $(CFLAGS) -c $< -o $@

    build/app: build/main.o
    \t$(CC) $^ -o $@

    lint-docs:
    \tpython tools/lint_docs.py \\
    \t  --strict
    ifeq ($(OS),Windows_NT)
    \techo windows
    endif

    ui-tests: export UI_EXE := build/app
    ui-tests: build/app
    \tpython -m unittest discover -s tests/native -p "test_ui.py"

    report:
    \tpython tools/report.py
    """
).replace("\\t", "\t")


class MakefileRecipeOnlyRoutingTests(unittest.TestCase):
    """#702: a recipe-only edit of phony targets must not route the full build matrix,
    and every other Makefile edit must still fail safe to it."""

    analyse = staticmethod(ci_paths_module.makefile_recipe_only_targets)

    def edit(self, old: str, new: str) -> tuple[str, ...] | None:
        self.assertIn(old, _SYNTHETIC_MAKEFILE)
        return self.analyse(_SYNTHETIC_MAKEFILE, _SYNTHETIC_MAKEFILE.replace(old, new, 1))

    def test_synthetic_fixture_parses_as_intended(self) -> None:
        kinds, phony = ci_paths_module._makefile_line_kinds(_SYNTHETIC_MAKEFILE)
        self.assertEqual(phony, frozenset({"lint-docs", "ui-tests", "report"}))
        recipe_targets = {kind[1] for kind in kinds if kind[0] == "recipe"}
        self.assertEqual(
            recipe_targets,
            {("build/%.o",), ("build/app",), ("lint-docs",), ("ui-tests",), ("report",)},
        )
        self.assertEqual(self.analyse(_SYNTHETIC_MAKEFILE, _SYNTHETIC_MAKEFILE), ())

    def test_recipe_edits_of_phony_targets_are_narrow(self) -> None:
        cases = {
            "rewrite": ('-p "test_ui.py"', '-p "test_ui*.py"', ("ui-tests",)),
            "continuation line": ("\t  --strict", "\t  --strict --verbose", ("lint-docs",)),
            "recipe inside a conditional": ("\techo windows", "\techo win32", ("lint-docs",)),
            "added line": (
                "\tpython tools/report.py",
                "\tpython tools/report.py\n\tpython tools/report.py --json",
                ("report",),
            ),
            "two targets": ("\tpython tools/report.py", "\tpython3 tools/report.py", ("report",)),
            "comment only": ("# Synthetic Makefile", "# A synthetic Makefile", ()),
        }
        for label, (old, new, expected) in cases.items():
            with self.subTest(label):
                self.assertEqual(self.edit(old, new), expected)

    def test_every_structural_edit_keeps_full_routing(self) -> None:
        cases = {
            "compiler flag": ("CFLAGS := -O2 -Wall", "CFLAGS := -O3 -Wall"),
            "default variable": ("CC ?= gcc", "CC ?= clang"),
            "pattern-rule recipe": ("\t$(CC) $(CFLAGS) -c $< -o $@", "\t$(CC) $(CFLAGS) -g -c $< -o $@"),
            "file-target recipe": ("\t$(CC) $^ -o $@", "\t$(CC) $^ -lm -o $@"),
            "prerequisite": ("ui-tests: build/app", "ui-tests: build/app lint-docs"),
            "rule header": ("report:", "report: FORCE"),
            "target-specific variable": ("export UI_EXE := build/app", "export UI_EXE := build/app2"),
            "conditional": ("ifeq ($(OS),Windows_NT)", "ifeq ($(OS),Linux)"),
            "phony list": ("PUBLIC_TARGETS := lint-docs ui-tests", "PUBLIC_TARGETS := lint-docs"),
            "phony declaration": (".PHONY: $(PUBLIC_TARGETS) report", ".PHONY: $(PUBLIC_TARGETS)"),
            "new include": ("# Synthetic Makefile", "include extra.mk"),
            "recipe-prefix change": ("# Synthetic Makefile", ".RECIPEPREFIX := >"),
        }
        for label, (old, new) in cases.items():
            with self.subTest(label):
                self.assertIsNone(self.edit(old, new))

    def test_an_edit_that_reshapes_an_unchanged_line_keeps_full_routing(self) -> None:
        # A recipe continuation line need not start with a tab. Dropping the backslash
        # on the line above leaves it byte-identical but turns it into a top-level
        # line, so only the unchanged-line comparison can see the change.
        base = _SYNTHETIC_MAKEFILE.replace(
            "\tpython tools/report.py\n", "\tpython tools/report.py \\\n  --json\n"
        )
        kinds, _ = ci_paths_module._makefile_line_kinds(base)
        line = base.split("\n").index("  --json")
        self.assertEqual(kinds[line], ("recipe", ("report",), True))
        edited = base.replace("python tools/report.py \\", "python tools/report.py")
        self.assertEqual(ci_paths_module._makefile_line_kinds(edited)[0][line][0], "other")
        self.assertIsNone(self.analyse(base, edited))

    def test_even_trailing_backslashes_do_not_continue_a_line(self) -> None:
        """GNU make joins a line only on an odd number of trailing backslashes."""
        flag_base = "# keep C:\\\\\nCFLAGS = -O2\n.PHONY: t\nt:\n\techo $(CFLAGS)\n"
        kinds, _ = ci_paths_module._makefile_line_kinds(flag_base)
        self.assertEqual(kinds[1], ("other", "assignment"))
        self.assertIsNone(self.analyse(flag_base, flag_base.replace("-O2", "-O3")))
        rule_base = ".PHONY: t\nt:\n\techo C:\\\\\nall: foo\n\tcc foo\n"
        kinds, _ = ci_paths_module._makefile_line_kinds(rule_base)
        self.assertEqual(kinds[3][:3], ("other", "rule-header", ("all",)))
        self.assertIsNone(self.analyse(rule_base, rule_base.replace("all: foo", "all: foo bar")))
        # An odd count still continues: the next line belongs to the recipe.
        odd = ".PHONY: t\nt:\n\techo a \\\n  b\n"
        self.assertEqual(ci_paths_module._makefile_line_kinds(odd)[0][3], ("recipe", ("t",), True))

    def test_nested_define_fails_safe(self) -> None:
        nested = "define A\ndefine B\nx\nendef\n.PHONY: t\nt:\n\ta\nendef\n"
        self.assertIsNone(self.analyse(nested, nested.replace("\ta\n", "\tb\n")))

    def test_define_directive_is_recognised_by_words_not_spaces(self) -> None:
        # A tab-separated prefix still opens a define block, so a rule-shaped body
        # line is define text, not a recipe that could narrow routing.
        tabbed = ".PHONY: t\noverride\tdefine BODY\nt:\n\techo a\nendef\n"
        self.assertEqual(ci_paths_module._makefile_line_kinds(tabbed)[0][3], ("other", "define"))
        self.assertIsNone(self.analyse(tabbed, tabbed.replace("echo a", "echo b")))
        # A body line that merely contains the word is not a nested define.
        worded = "define BODY\nfoo define bar\nendef\n.PHONY: t\nt:\n\techo a\n"
        self.assertEqual(self.analyse(worded, worded.replace("echo a", "echo b")), ("t",))

    def test_static_pattern_rules_are_conservatively_shared(self) -> None:
        base = _SYNTHETIC_MAKEFILE + ".PHONY: check-a check-b\ncheck-a check-b: check-%:\n\techo $*\n"
        self.assertEqual(ci_paths_module._makefile_line_kinds(base)[1] >= {"check-a", "check-b"}, True)
        self.assertIsNone(self.analyse(base, base.replace("\techo $*", "\techo $* done")))

    def test_appended_or_conditional_phony_lists_are_not_trusted(self) -> None:
        appended = _SYNTHETIC_MAKEFILE.replace(
            "PUBLIC_TARGETS := lint-docs ui-tests", "PUBLIC_TARGETS := lint-docs\nPUBLIC_TARGETS += ui-tests"
        )
        edited = appended.replace('-p "test_ui.py"', '-p "test_ui*.py"')
        self.assertIsNone(self.analyse(appended, edited))
        conditional = _SYNTHETIC_MAKEFILE.replace(
            ".PHONY: $(PUBLIC_TARGETS) report", ".PHONY: $(PUBLIC_TARGETS)\nifdef X\n.PHONY: report\nendif"
        )
        edited = conditional.replace("\tpython tools/report.py", "\tpython3 tools/report.py")
        self.assertIsNone(self.analyse(conditional, edited))
        conditional_list = _SYNTHETIC_MAKEFILE.replace(
            "PUBLIC_TARGETS := lint-docs ui-tests", "ifdef X\nPUBLIC_TARGETS := lint-docs ui-tests\nendif"
        )
        edited = conditional_list.replace('-p "test_ui.py"', '-p "test_ui*.py"')
        self.assertIsNone(self.analyse(conditional_list, edited))

    def test_unmodelled_constructs_fail_safe(self) -> None:
        orphan = "\techo orphan\n" + _SYNTHETIC_MAKEFILE
        self.assertIsNone(self.analyse(orphan, orphan.replace("orphan", "orphan2")))
        unterminated = _SYNTHETIC_MAKEFILE + "define BODY\n\tline\n"
        self.assertIsNone(self.analyse(unterminated, unterminated.replace("report.py", "report2.py")))

    def test_live_makefile_recipe_edit_narrows_and_flag_edit_does_not(self) -> None:
        makefile = (Path(__file__).resolve().parents[1] / "Makefile").read_text(encoding="utf-8")
        recipe = '\t$(PYTHON) -m unittest discover -s tests/native -p "test_player_ui.py" -v\n'
        self.assertIn(recipe, makefile)
        self.assertEqual(
            self.analyse(makefile, makefile.replace(recipe, recipe.replace(" -v", " -v -f"), 1)),
            ("player-ui-regressions",),
        )
        flag = re.search(r"(?m)^PLAYER_EXE \?= .*$", makefile)
        self.assertIsNotNone(flag)
        self.assertIsNone(self.analyse(makefile, makefile.replace(flag.group(0), flag.group(0) + " ", 1)))
        file_recipe = "-DNK_PLAYER_UI_REGRESSION_TEST"
        self.assertIn(file_recipe, makefile)
        self.assertIsNone(self.analyse(makefile, makefile.replace(file_recipe, file_recipe + " -O0", 1)))

    def test_recipe_only_change_routes_native_windows_and_the_coupled_python_subset(self) -> None:
        result = classify(["Makefile"], makefile_change=("player-ui-regressions",))
        self.assertEqual(result["makefile_recipe_only"], "true")
        self.assertEqual(result["build_system"], "false")
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["python_scope"], "makefile")
        self.assertEqual(json.loads(result["python_shards"]), [0, 1])
        self.assertEqual(result["python_num_shards"], "2")

    def test_any_other_python_routing_restores_the_full_suite(self) -> None:
        for other in ("tools/codegen.py", "src/rt/hle.c", ".github/workflows/ci.yml",
                      "tools/publish_audit.py", "mk/build_common.mk", "brand_new_file.xyz"):
            with self.subTest(other=other):
                result = classify(["Makefile", other], makefile_change=("player-ui-regressions",))
                self.assertEqual(result["python_scope"], "all")
                self.assertEqual(json.loads(result["python_shards"]), [0, 1, 2, 3])
                self.assertEqual(result["run_native"], "true")

    def test_unproven_or_absent_analysis_keeps_build_system_routing(self) -> None:
        result = classify(["Makefile"])
        self.assertEqual(result["build_system"], "true")
        self.assertEqual(result["makefile_recipe_only"], "false")
        self.assertEqual(result["python_scope"], "all")
        self.assertEqual(json.loads(result["python_shards"]), [0, 1, 2, 3])
        # The analysis result is ignored when the Makefile is not among the changes,
        # and a manual dispatch is always the full matrix.
        self.assertEqual(classify(["docs/CI.md"], makefile_change=())["run_native"], "false")
        dispatch = classify([], event_name="workflow_dispatch", makefile_change=())
        self.assertEqual(dispatch["python_scope"], "all")
        self.assertEqual(dispatch["build_system"], "true")

    def test_main_reads_both_makefile_revisions_from_git(self) -> None:
        """Production path: the workflow's classify step diffs real revisions."""

        def git(*args: str) -> str:
            return subprocess.run(
                ["git", "-c", "user.name=ci-paths-test", "-c", "user.email=ci-paths-test@invalid", *args],
                cwd=repo, check=True, capture_output=True, text=True,
            ).stdout.strip()

        with tempfile.TemporaryDirectory() as scratch:
            repo = Path(scratch)
            git("init", "-q")
            (repo / "Makefile").write_text(_SYNTHETIC_MAKEFILE, encoding="utf-8")
            git("add", "Makefile")
            git("commit", "-q", "-m", "base")
            base = git("rev-parse", "HEAD")
            outputs: dict[str, dict[str, str]] = {}
            for label, old, new in (
                ("recipe", '-p "test_ui.py"', '-p "test_ui*.py"'),
                ("flag", "CFLAGS := -O2 -Wall", "CFLAGS := -O3 -Wall"),
            ):
                git("checkout", "-q", base)
                (repo / "Makefile").write_text(_SYNTHETIC_MAKEFILE.replace(old, new), encoding="utf-8")
                git("commit", "-q", "-am", label)
                head = git("rev-parse", "HEAD")
                event = repo / "event.json"
                event.write_text(json.dumps({"pull_request": {"base": {"sha": base}}}), encoding="utf-8")
                github_output = repo / f"{label}.out"
                with mock.patch.object(ci_paths_module, "ROOT", repo), \
                        mock.patch.dict(os.environ, {"GITHUB_SHA": head}), \
                        mock.patch("sys.stdout"):
                    ci_paths_module.main([
                        "--event-name", "pull_request", "--event-path", str(event),
                        "--github-output", str(github_output),
                    ])
                outputs[label] = dict(
                    line.split("=", 1) for line in github_output.read_text(encoding="utf-8").splitlines()
                )
        self.assertEqual(outputs["recipe"]["python_scope"], "makefile")
        self.assertEqual(outputs["recipe"]["build_system"], "false")
        self.assertEqual(outputs["recipe"]["run_windows"], "true")
        self.assertEqual(outputs["flag"]["python_scope"], "all")
        self.assertEqual(outputs["flag"]["build_system"], "true")

    def test_missing_revision_fails_safe(self) -> None:
        with mock.patch.object(
            ci_paths_module.subprocess, "run", side_effect=subprocess.CalledProcessError(128, "git")
        ):
            self.assertIsNone(ci_paths_module.makefile_change_from_git("base", "head"))


class PublicationCoverageInvariantTests(unittest.TestCase):
    """Publication integrity must never become path-gated.

    Every tracked file is inside the published surface and the ledger carries a
    content hash for each one, so *any* tracked change invalidates the generated
    public metadata until it is refreshed. The only reason a docs-only change can
    safely skip the Python suite is that the publication audit runs ungated on
    every event. If someone ever path-gates the hygiene job, or drops the audit
    from the shared pre-commit run, a stale public ledger becomes mergeable --
    so both facts are pinned here rather than left to a comment.
    """

    def test_hygiene_job_is_not_path_gated(self) -> None:
        workflow = (Path(__file__).resolve().parents[1] / ".github" / "workflows" / "ci.yml").read_text(
            encoding="utf-8")
        marker = "\n  markdown:"
        block = workflow.split("  hygiene:", 1)[1].split(marker, 1)[0]
        condition = [line for line in block.splitlines() if line.strip().startswith("if:")]
        self.assertTrue(condition, "hygiene must keep an explicit always() condition")
        self.assertIn("always()", condition[0])
        for gate in ("run_python", "run_native", "docs_only", "run_markdown"):
            self.assertNotIn(gate, condition[0],
                             "hygiene must not be gated on %s: publication integrity would "
                             "become path-dependent" % gate)

    def test_shared_precommit_run_audits_publication(self) -> None:
        config = (Path(__file__).resolve().parents[1] / ".pre-commit-config.yaml").read_text(
            encoding="utf-8")
        self.assertIn("tools/publish_audit.py", config)
        self.assertIn("--provenance-self-consistency", config)
        self.assertIn("tools/policy_sync.py", config)

    PUBLICATION_HOOKS = (
        "documentation-freshness",
        "publication-policy-sync",
        "publication-audit",
        "modified-file-notice-audit",
        "provenance-record-gap-check",
    )

    @staticmethod
    def _hook_stages(config: str, hook_id: str) -> list[str] | None:
        """Return a hook's declared stages, or None when it runs at every stage."""
        match = re.search(
            rf"(?ms)^[ \t]*- id: {re.escape(hook_id)}[ \t]*\n(.*?)(?=^[ \t]*- (?:id|repo): |\Z)",
            config,
        )
        assert match is not None, f"hook {hook_id} is missing from .pre-commit-config.yaml"
        stages = re.search(r"(?m)^[ \t]*stages:[ \t]*\[([^\]]*)\]", match.group(1))
        if stages is None:
            return None
        return [stage.strip() for stage in stages.group(1).split(",") if stage.strip()]

    def test_publication_hooks_run_in_the_hosted_run_and_at_commit_time(self) -> None:
        """Moving a publication hook off the commit stage must not silently drop it.

        Hosted CI's hygiene job runs ``pre-commit run --all-files``, which runs the
        commit stage only; a hook declared ``stages: [pre-push]`` would vanish from
        CI while this file still names it. The commit stage is also the only local
        point that audits every commit: the push stage audits the index, not each
        pushed commit, and branch commits are public once pushed.
        """
        root = Path(__file__).resolve().parents[1]
        config = (root / ".pre-commit-config.yaml").read_text(encoding="utf-8")
        workflow = (root / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
        hosted = re.findall(r"pre-commit run --all-files[^\n]*", workflow)
        self.assertTrue(hosted, "the hygiene job no longer runs the shared pre-commit hooks")
        hosted_stages = {
            (re.search(r"--hook-stage[ =](\S+)", line) or [None, "pre-commit"])[1]
            for line in hosted
        }
        for hook_id in self.PUBLICATION_HOOKS:
            stages = self._hook_stages(config, hook_id)
            with self.subTest(hook=hook_id):
                if stages is not None:
                    self.assertIn("pre-commit", stages)
                    self.assertTrue(hosted_stages & set(stages), (hook_id, stages, hosted_stages))


class PrecommitPathCoverageTests(unittest.TestCase):
    def test_global_exclusion_preserves_public_hook_inputs(self) -> None:
        config = (Path(__file__).resolve().parents[1] / ".pre-commit-config.yaml").read_text(
            encoding="utf-8")
        block = re.search(r"(?m)^exclude:\s*\|\n((?:[ \t]+[^\n]*(?:\n|$))+)", config)
        self.assertIsNotNone(block, "global pre-commit exclusion must remain explicit")
        pattern = re.compile(textwrap.dedent(block.group(1)))
        for path in (
            "README.md", ".github/workflows/ci.yml", ".pre-commit-config.yaml",
            "src/rt/hle.c", "tools/test_ci_paths.py", "fixtures/profile_zero/main.c",
            "docs/build/layout.md", "tools/third_party_audit.py",
        ):
            with self.subTest(path=path):
                self.assertIsNone(pattern.search(path), f"public hook input excluded: {path}")
        for prefix in (
            "build", "third_party", "place_game_here", "original_game",
            "oracle", "fs", "memstick", "logs",
        ):
            with self.subTest(prefix=prefix):
                self.assertIsNotNone(pattern.search(f"{prefix}/input.bin"))


if __name__ == "__main__":
    unittest.main()
