# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025-2026 the psp-recomp authors

import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools import build_public_export, history_audit, publication_policy, public_export
from tools.nk_core.git_isolation import isolated_git_env, run_git
from tools.build_public_export import (
    ROOT,
    GateResult,
    _quarantine_failed_export,
    check_unresolved_legal_blockers,
    export_sanitized_public_tree,
    history_audit_gate_result,
    is_public_safe_export_tree,
    run_all_publication_gates,
    run_candidate_audit,
    run_publish_audit,
    run_sbom_verification,
)

# The same tests run in the source checkout and in a materialized public-safe
# candidate. Profile-excluded files are asserted by path/policy using synthetic
# conditions; publication-security coverage must not disappear behind skips.
_PUBLIC_SAFE_TREE = is_public_safe_export_tree()


def _git(argv: list[str], cwd: Path) -> None:
    run_git(argv, cwd=cwd, check=True, capture_output=True)


def _tree_bytes(root: Path) -> dict[str, bytes]:
    """Materialized candidate bytes keyed by repo-relative POSIX path.

    Excluded: ``.git`` (commit objects are per-invocation snapshot metadata,
    not tracked candidate identity) and host runtime residue (``__pycache__``/
    ``*.pyc`` written when Python executes ``tools/*.py`` in place inside a
    candidate). Neither is candidate content.
    """
    result: dict[str, bytes] = {}
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        if ".git" in rel.parts or "__pycache__" in rel.parts or path.suffix == ".pyc":
            continue
        result[rel.as_posix()] = path.read_bytes()
    return result


def _init_synthetic_repo(root: Path, sensitive: bool) -> None:
    """Build a small multi-commit git repository in *root*.

    ``sensitive=True`` drops a DEFINITE_SECRET token into one commit so the
    history audit must fail closed; ``sensitive=False`` produces a sanitized
    multi-commit history that must pass.  The repo is deliberately tiny and
    synthetic: no private bytes, no network, no shared refs.
    """
    for argv in (("init", "-q"),):
        _git(argv, root)
    (root / "safe.txt").write_text("safe\n", encoding="utf-8")
    _git(["add", "safe.txt"], root)
    _git(["commit", "-qm", "safe base"], root)
    (root / "second.txt").write_text("also safe\n", encoding="utf-8")
    _git(["add", "second.txt"], root)
    _git(["commit", "-qm", "second commit"], root)
    if sensitive:
        (root / "legacy_keys.txt").write_text(
            "legacy token " + "ghp_" + "012345678901234567890123456789012345" + "\n",
            encoding="utf-8",
        )
        _git(["add", "legacy_keys.txt"], root)
        _git(["commit", "-qm", "legacy artifact"], root)


class TestPublicExport(unittest.TestCase):
    def test_in_place_metadata_is_idempotent_across_its_own_previous_bytes(self):
        policy = publication_policy.load_policy(ROOT / "assets/public_source_profile.json")
        common = [("README.md", b"source bytes\n")]
        first = public_export.build_document(
            policy,
            common + [(public_export.EXPORT_PATH, b"old generated bytes\n")],
            provenance_ledger=b"ledger bytes\n",
            manifest=b"manifest bytes\n",
        )
        first_bytes = json.dumps(first, indent=2, ensure_ascii=False).encode("utf-8") + b"\n"
        second = public_export.build_document(
            policy,
            common + [(public_export.EXPORT_PATH, first_bytes)],
            provenance_ledger=b"ledger bytes\n",
            manifest=b"manifest bytes\n",
        )
        self.assertEqual(first, second)
        self.assertNotIn("source_tree", first)

    def test_legal_blockers_fail_closed_without_profile(self):
        res = check_unresolved_legal_blockers(public_safe_profile=False)
        self.assertFalse(res.passed)
        self.assertIn("OPEN PUBLICATION BLOCKERS", res.detail)

    def test_legal_blockers_pass_with_public_safe_profile(self):
        res = check_unresolved_legal_blockers(public_safe_profile=True)
        self.assertTrue(res.passed)
        self.assertIn("PUBLIC-SAFE PROFILE ACTIVE", res.detail)

    def test_publish_audit_gate(self):
        res = run_publish_audit()
        self.assertTrue(res.passed, f"publish_audit gate failed: {res.detail}")

    def test_history_audit_gate_fails_closed_on_legacy_history(self):
        # A legacy/dirty history must fail closed regardless of the ambient
        # checkout's own refs: build a synthetic repo whose history contains a
        # definite secret and prove the audit and the publication gate reject it.
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _init_synthetic_repo(root, sensitive=True)
            report = history_audit.generate_full_history_audit_report(root)
            self.assertEqual(report["status"], "FAIL")
            self.assertGreater(report["summary"]["total_findings"], 0)
            self.assertEqual(report["summary"]["category_counts"].get("DEFINITE_SECRET", 0), 1)
            res = history_audit_gate_result(report)
            self.assertFalse(res.passed, "legacy dirty history must fail closed")
            self.assertIn("SENSITIVE FINDINGS DETECTED", res.detail)

    def test_history_audit_gate_passes_on_sanitized_history(self):
        # A sanitized multi-commit history must pass: the gate criterion is the
        # audit state (zero findings), never the commit count. This is the
        # current intended public baseline (sanitized main plus fresh export).
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _init_synthetic_repo(root, sensitive=False)
            report = history_audit.generate_full_history_audit_report(root)
            self.assertEqual(report["status"], "OK")
            self.assertEqual(report["summary"]["total_findings"], 0)
            self.assertGreater(report["baseline"]["total_commits"], 1)
            res = history_audit_gate_result(report)
            self.assertTrue(res.passed, "sanitized multi-commit history must pass")
            self.assertIn("0 sensitive findings", res.detail)

    def test_sbom_verification_gate(self):
        res = run_sbom_verification()
        self.assertTrue(res.passed, f"sbom_verification gate failed: {res.detail}")

    def test_run_all_publication_gates(self):
        results = run_all_publication_gates(public_safe_profile=True)
        self.assertEqual(len(results), 4)
        history = results[2]
        if history.passed:
            # Sanitized history: the intended public baseline is fully green.
            for gate in results:
                self.assertTrue(gate.passed, f"Gate '{gate.name}' failed: {gate.detail}")
        else:
            # Dirty legacy ancestry present in this checkout: the history gate
            # must stay visibly failed, but non-blocking because the legacy
            # ancestry is not exported into the fresh sanitized root. The other
            # gates must still pass under the public-safe profile.
            self.assertFalse(history.blocking, "old history is non-blocking only because it is not exported")
            self.assertIn("not exported", history.name)
            for gate in results[:2] + results[3:]:
                self.assertTrue(gate.passed, f"Gate '{gate.name}' failed: {gate.detail}")

    def test_dry_run_export(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "export_repo"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True, dry_run=True)
            self.assertTrue(success)

    def test_public_safe_export_excludes_unreviewed_components(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "public_export"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True)
            self.assertTrue(success, "public-safe export should succeed at the tree level")
            # Core toolkit and required publication files are present.
            self.assertTrue((target_path / "src" / "rt" / "recomp.c").is_file())
            self.assertTrue((target_path / "LICENSE").is_file())
            self.assertTrue((target_path / "NOTICE.md").is_file())
            # Unresolved PGF/font and PGD/amctrl surfaces are excluded from the tree.
            for rel in (
                "font/jpn0.pgf",
                "font/kr0.pgf",
                "font/ltn0.pgf",
                "font/ltn8.pgf",
                "src/rt/pgf.c",
                "src/rt/pgf.h",
                "src/rt/pgd.c",
                "src/rt/pgd.h",
                "tools/pgd_decrypt.py",
                "tools/pgd_e2e_harness.c",
                "tools/test_pgd_c.py",
                "tools/test_pgd_decrypt.py",
            ):
                self.assertFalse((target_path / rel).exists(), f"{rel} must be excluded")
            # Provenance metadata records the profile, source commit, and exclusions.
            metadata_path = target_path / "PUBLIC_EXPORT.json"
            self.assertTrue(metadata_path.is_file())
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
            self.assertEqual(metadata["profile"], "public-safe-v1")
            self.assertEqual(
                metadata["excluded_file_count"],
                len(metadata.get("excluded_present_paths", [])),
            )
            self.assertGreater(len(metadata["excluded_paths"]), 0)
            self.assertIn("font/*.pgf", metadata["excluded_globs"])
            self.assertIn("src/rt/pgd.c", metadata["excluded_paths"])
            self.assertTrue(metadata.get("source_tree"))

    def test_public_safe_export_audits_in_public_scope_in_its_own_pre_commit(self):
        # The exported tree lacks the manifest-declared excluded components by
        # design; the export's own publication-safety pre-commit hook must run
        # in public scope so contributor commits do not fail on their absence.
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "public_export"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True)
            self.assertTrue(success, "public-safe export should succeed at the tree level")
            pre_commit_text = (target_path / ".pre-commit-config.yaml").read_text(encoding="utf-8")
            self.assertIn(
                "entry: python tools/publish_audit.py --tracked-only --public-scope",
                pre_commit_text,
            )
            self.assertNotIn(
                "entry: python tools/publish_audit.py --tracked-only\n",
                pre_commit_text.replace("--public-scope", ""),
            )

    def test_profile_excludes_unreviewed_components_without_materializing_them(self):
        from tools import public_candidate

        profile = public_candidate.load_profile(ROOT / "assets/public_source_profile.json")
        for rel in (
            "font/jpn0.pgf",
            "src/rt/pgf.c",
            "src/rt/pgd.c",
            "tools/pgd_decrypt.py",
        ):
            self.assertTrue(public_candidate.is_excluded(rel, profile), rel)


class TestCandidateImmutability293(unittest.TestCase):
    """Issue #293: candidate bytes are frozen when PUBLIC_EXPORT.json is written.

    ``export_sanitized_public_tree`` must never mutate a provenance-pinned
    candidate file after that point, two exports of the same index must be
    byte-identical apart from the intentionally variable commit metadata, and
    the exhaustive candidate-tree audit must read the exact final bytes.
    """

    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        cls._tmp = tempfile.TemporaryDirectory()
        base = Path(cls._tmp.name)
        cls.export_a = base / "export_a"
        cls.export_b = base / "export_b"
        for target in (cls.export_a, cls.export_b):
            if not export_sanitized_public_tree(target, public_safe_profile=True):
                raise AssertionError(f"public-safe export failed for {target}")
        cls.manifest_a = json.loads(
            (cls.export_a / "PUBLIC_EXPORT.json").read_text(encoding="utf-8")
        )
        cls.manifest_b = json.loads(
            (cls.export_b / "PUBLIC_EXPORT.json").read_text(encoding="utf-8")
        )
        # A rejected copy used by the tamper/authority tests, built once so the
        # shared fixtures are never modified in place.
        cls.tampered = base / "export_tampered"
        shutil.copytree(cls.export_a, cls.tampered, ignore=shutil.ignore_patterns(".git"))
        pre_commit = cls.tampered / ".pre-commit-config.yaml"
        pre_commit.write_bytes(pre_commit.read_bytes() + b"# tampered after freeze\n")

    @classmethod
    def tearDownClass(cls) -> None:
        cls._tmp.cleanup()
        super().tearDownClass()

    def test_real_candidate_audit_promotes_a_clean_export(self):
        # Property: audit-before-promotion -- the exhaustive candidate-tree
        # audit (release-controlled trusted ledger) runs against the staging
        # bytes, and the requested path exists only because that audit passed.
        with tempfile.TemporaryDirectory() as tmpdir:
            target = Path(tmpdir) / "e2e_cleared"
            ok = export_sanitized_public_tree(
                target,
                public_safe_profile=True,
                audit_candidate=lambda root: run_candidate_audit(
                    root, trusted_ledger=ROOT / "assets/public_provenance_ledger.json"
                ),
            )
            self.assertTrue(ok)
            self.assertTrue((target / "PUBLIC_EXPORT.json").is_file())
            self.assertFalse((Path(tmpdir) / "e2e_cleared.not-cleared").exists())
            leftovers = [
                p.name
                for p in Path(tmpdir).iterdir()
                if ".e2e_cleared.staging-" in p.name
            ]
            self.assertEqual(leftovers, [])

    def test_recorded_identity_matches_materialized_bytes_and_source_is_untouched(self):
        # Property: PUBLIC_EXPORT.json and the ledger/manifest shas it records
        # describe the exact materialized candidate bytes; generating the
        # export never mutates the source tree. The staged-index-vs-worktree
        # binding is asserted hermetically by
        # test_export_materializes_staged_index_bytes_not_unstaged_worktree_drift
        # so this test never depends on ambient index/worktree state.
        policy = publication_policy.load_policy(ROOT / "assets" / "public_source_profile.json")
        files = _tree_bytes(self.export_a)
        included = [
            (rel, raw)
            for rel, raw in files.items()
            if policy.resolve(rel).disposition == "included"
        ]
        self.assertEqual(
            public_export.content_digest(included),
            self.manifest_a["included_content_sha256"],
        )
        self.assertEqual(
            self.manifest_a["provenance_ledger_sha256"],
            hashlib.sha256(
                (self.export_a / "assets" / "public_provenance_ledger.json").read_bytes()
            ).hexdigest(),
        )
        self.assertEqual(
            self.manifest_a["manifest_sha256"],
            hashlib.sha256(
                (self.export_a / "assets" / "release_manifest.json").read_bytes()
            ).hexdigest(),
        )

    def test_tampered_candidate_fails_the_candidate_tree_audit(self):
        # Property: any post-freeze byte change is detected by re-auditing the
        # materialized candidate against the trusted ledger.
        res = subprocess.run(
            [
                sys.executable,
                "tools/publish_audit.py",
                "--candidate-root", str(self.tampered),
                "--candidate-tree",
                "--public-scope",
                "--provenance-ledger", "assets/public_provenance_ledger.json",
            ],
            cwd=ROOT,
            env=isolated_git_env(root=self.tampered),
            capture_output=True,
            text=True,
        )
        self.assertNotEqual(res.returncode, 0)
        self.assertIn("PROVENANCE_CONTENT_MISMATCH", res.stdout + res.stderr)

    def test_two_exports_are_deterministic_and_commit_metadata_is_variable(self):
        # Property: two exports of the same index are byte-identical in every
        # tracked candidate file and in PUBLIC_EXPORT.json. The export commit id
        # and its timestamps are intentionally variable snapshot metadata and
        # are not part of the recorded identity.
        self.assertEqual(self.manifest_a, self.manifest_b)
        self.assertEqual(_tree_bytes(self.export_a), _tree_bytes(self.export_b))
        commit_a = run_git(
            ["rev-parse", "HEAD"], cwd=self.export_a,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        commit_b = run_git(
            ["rev-parse", "HEAD"], cwd=self.export_b,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        tree_a = run_git(
            ["rev-parse", "HEAD^{tree}"], cwd=self.export_a,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        tree_b = run_git(
            ["rev-parse", "HEAD^{tree}"], cwd=self.export_b,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        # Tracked identity is the tree plus the recorded digest; commit ids are
        # never recorded in PUBLIC_EXPORT.json and may differ across runs.
        self.assertEqual(tree_a, tree_b)
        recorded = json.dumps(self.manifest_a)
        self.assertNotIn(commit_a, recorded)
        self.assertNotIn(commit_b, recorded)
        for key in ("commit", "commit_id", "export_commit"):
            self.assertNotIn(key, self.manifest_a)

    def test_exported_pre_commit_audit_passes_functionally(self):
        # Property: the exported tree's own pre-commit publication-audit entry
        # runs against the candidate and passes (public scope, tripwire
        # provenance scope) without any further mutation of the tree.
        before = _tree_bytes(self.export_a)
        res = subprocess.run(
            [
                sys.executable,
                "tools/publish_audit.py",
                "--tracked-only",
                "--public-scope",
                "--provenance-self-consistency",
            ],
            cwd=self.export_a,
            env=isolated_git_env(root=self.export_a),
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0, res.stdout + res.stderr)
        self.assertEqual(before, _tree_bytes(self.export_a), "the audit must not mutate the candidate")

    def test_authority_unavailable_is_not_conflated_with_content_invalid(self):
        # Property: a missing trusted ledger (authority unavailable) fails as
        # PROVENANCE_UNVERIFIED, while a trusted ledger plus altered bytes fails
        # as PROVENANCE_CONTENT_MISMATCH. The two failures never collapse into
        # one another.
        base_cmd = [
            sys.executable,
            "tools/publish_audit.py",
            "--candidate-root", str(self.export_a),
            "--candidate-tree",
            "--public-scope",
        ]
        no_authority = subprocess.run(
            base_cmd,
            cwd=ROOT,
            env=isolated_git_env(root=self.export_a),
            capture_output=True,
            text=True,
        )
        self.assertNotEqual(no_authority.returncode, 0)
        no_authority_out = no_authority.stdout + no_authority.stderr
        self.assertIn("PROVENANCE_UNVERIFIED", no_authority_out)
        self.assertNotIn("PROVENANCE_CONTENT_MISMATCH", no_authority_out)

        invalid = subprocess.run(
            [
                sys.executable,
                "tools/publish_audit.py",
                "--candidate-root", str(self.tampered),
                "--candidate-tree",
                "--public-scope",
                "--provenance-ledger", "assets/public_provenance_ledger.json",
            ],
            cwd=ROOT,
            env=isolated_git_env(root=self.tampered),
            capture_output=True,
            text=True,
        )
        self.assertNotEqual(invalid.returncode, 0)
        invalid_out = invalid.stdout + invalid.stderr
        self.assertIn("PROVENANCE_CONTENT_MISMATCH", invalid_out)
        self.assertNotIn("PROVENANCE_UNVERIFIED", invalid_out)

    def test_interrupted_export_is_not_finalized(self):
        # Property: a generation failure leaves no candidate at the requested
        # path and no staging residue.
        with tempfile.TemporaryDirectory() as tmpdir:
            target = Path(tmpdir) / "interrupted_export"
            with mock.patch(
                "tools.build_public_export._index_snapshot",
                side_effect=RuntimeError("simulated interrupt"),
            ):
                ok = export_sanitized_public_tree(target, public_safe_profile=True)
            self.assertFalse(ok)
            self.assertFalse(target.exists())
            leftovers = [
                p.name
                for p in Path(tmpdir).iterdir()
                if p.name.startswith(".interrupted_export.staging-")
            ]
            self.assertEqual(leftovers, [])

    def test_failed_candidate_audit_quarantines_the_export(self):
        # Property: an uncleared candidate is moved to a diagnostic sibling of
        # the REQUESTED path; the requested path is never created for it.
        with tempfile.TemporaryDirectory() as tmpdir:
            candidate = Path(tmpdir) / ".doomed.staging-0"
            candidate.mkdir()
            (candidate / "file.txt").write_text("not cleared\n", encoding="utf-8", newline="\n")
            requested = Path(tmpdir) / "doomed"
            quarantined = _quarantine_failed_export(candidate, requested)
            self.assertIsNotNone(quarantined)
            self.assertFalse(requested.exists())
            self.assertFalse(candidate.exists())
            self.assertEqual(quarantined.name, "doomed.not-cleared")
            self.assertTrue(quarantined.exists())

    def test_passing_candidate_audit_promotes_staging_to_requested_path(self):
        # Property (regression, #293): audit-before-promotion -- a PASS gate
        # atomically promotes the staging tree to the requested path with no
        # staging residue, and the promoted bytes are exactly what the audit
        # saw.
        seen: dict[str, dict[str, bytes]] = {}

        def _clear(root: Path) -> GateResult:
            self.assertNotEqual(root.name, "cleared")
            self.assertTrue(root.is_dir())
            seen["tree"] = _tree_bytes(root)
            return GateResult("Candidate-Tree Audit", True, "synthetic clear")

        with tempfile.TemporaryDirectory() as tmpdir:
            target = Path(tmpdir) / "cleared"
            ok = export_sanitized_public_tree(
                target, public_safe_profile=True, audit_candidate=_clear
            )
            self.assertTrue(ok)
            self.assertTrue(target.is_dir())
            self.assertEqual(seen["tree"], _tree_bytes(target))
            leftovers = [
                p.name for p in Path(tmpdir).iterdir() if ".staging-" in p.name
            ]
            self.assertEqual(leftovers, [])

    def test_failing_candidate_audit_never_materializes_requested_path(self):
        # Property (regression, #293): a FAIL gate runs against a completed
        # staging tree that is not the requested path; afterwards the requested
        # path is absent and the rejected candidate survives only as the
        # *.not-cleared diagnostic sibling.
        audited: dict[str, Path] = {}

        def _reject(root: Path) -> GateResult:
            audited["root"] = root
            self.assertTrue(root.is_dir())
            return GateResult("Candidate-Tree Audit", False, "synthetic reject")

        with tempfile.TemporaryDirectory() as tmpdir:
            target = Path(tmpdir) / "rejected"
            ok = export_sanitized_public_tree(
                target, public_safe_profile=True, audit_candidate=_reject
            )
            self.assertFalse(ok)
            self.assertIn("root", audited)
            self.assertNotEqual(audited["root"], target)
            self.assertFalse(target.exists())
            quarantined = Path(tmpdir) / "rejected.not-cleared"
            self.assertTrue(quarantined.is_dir())
            self.assertTrue((quarantined / "PUBLIC_EXPORT.json").is_file())
            leftovers = [
                p.name for p in Path(tmpdir).iterdir() if ".staging-" in p.name
            ]
            self.assertEqual(leftovers, [])

    def test_quarantine_failure_leaves_requested_path_absent(self):
        # Property (regression, #293): even when the diagnostic copy itself
        # fails, the requested path is never created -- staging is cleaned up
        # and no partially promoted candidate survives anywhere releasable.
        with tempfile.TemporaryDirectory() as tmpdir:
            target = Path(tmpdir) / "quarantine_boom"
            with mock.patch.object(
                build_public_export,
                "_quarantine_failed_export",
                side_effect=OSError("simulated quarantine failure"),
            ):
                ok = export_sanitized_public_tree(
                    target,
                    public_safe_profile=True,
                    audit_candidate=lambda root: GateResult(
                        "Candidate-Tree Audit", False, "synthetic reject"
                    ),
                )
            self.assertFalse(ok)
            self.assertFalse(target.exists())
            leftovers = [
                p.name for p in Path(tmpdir).iterdir() if ".staging-" in p.name
            ]
            self.assertEqual(leftovers, [])

    def test_existing_nonempty_destination_is_untouched(self):
        # Property (regression, #293): an existing nonempty destination fails
        # closed before any staging work or audit runs; its bytes are never
        # mutated or removed.
        calls: list[Path] = []

        def _audit(root: Path) -> GateResult:
            calls.append(root)
            return GateResult("Candidate-Tree Audit", True, "must not run")

        with tempfile.TemporaryDirectory() as tmpdir:
            target = Path(tmpdir) / "occupied"
            target.mkdir()
            sentinel = target / "precious.txt"
            sentinel.write_text("do not clobber\n", encoding="utf-8", newline="\n")
            ok = export_sanitized_public_tree(
                target, public_safe_profile=True, audit_candidate=_audit
            )
            self.assertFalse(ok)
            self.assertEqual(sentinel.read_text(encoding="utf-8"), "do not clobber\n")
            self.assertEqual(calls, [])

    def test_malformed_index_record_fails_closed(self):
        # Property (regression, #293): a malformed nonempty
        # ``git ls-files -s -z`` record raises instead of being silently
        # skipped, so the export can never drop an index entry it cannot parse.
        real_run = subprocess.run

        def fake_run(cmd, **kwargs):
            if list(cmd[:2]) == ["git", "write-tree"]:
                return subprocess.CompletedProcess(
                    cmd, 0, stdout="synthetic-tree\n", stderr=""
                )
            if list(cmd[:2]) == ["git", "ls-files"]:
                return subprocess.CompletedProcess(
                    cmd, 0, stdout=b"100644 deadbeef\n\0", stderr=b""
                )
            raise AssertionError(f"unexpected command in malformed-record test: {cmd}")

        with tempfile.TemporaryDirectory() as tmpdir:
            synth = Path(tmpdir) / "src"
            synth.mkdir()
            _git(["init", "-q"], synth)
            with mock.patch.object(
                build_public_export.subprocess, "run", side_effect=fake_run
            ):
                with self.assertRaises(RuntimeError) as ctx:
                    build_public_export._index_snapshot(synth)
            self.assertIn("malformed git ls-files -s -z record", str(ctx.exception))
            # The original runner still works after the patch unwinds.
            self.assertIsNot(subprocess.run, fake_run)
            self.assertTrue(real_run is subprocess.run)

    def test_export_materializes_staged_index_bytes_not_unstaged_worktree_drift(self):
        # Property (#293, the original victim): with worktree bytes (B)
        # diverging from the staged index (A), the export materializes A --
        # never B -- and generation mutates neither the worktree nor the index.
        # The recorded content digest covers the A variant and differs from the
        # B variant, so binding to worktree drift would be detectable.
        with tempfile.TemporaryDirectory() as tmpdir:
            synth = Path(tmpdir) / "synth source"
            synth.mkdir()
            _git(["init", "-q"], synth)
            assets = synth / "assets"
            assets.mkdir()
            shutil.copy2(
                ROOT / "assets" / "public_source_profile.json",
                assets / "public_source_profile.json",
            )
            staged_a = b"# staged index payload A\n"
            worktree_b = b"unstaged worktree payload B"
            victim = synth / ".pre-commit-config.yaml"
            victim.write_bytes(staged_a)
            _git(["add", ".pre-commit-config.yaml"], synth)
            victim.write_bytes(worktree_b)

            target = Path(tmpdir) / "export_ab"
            with mock.patch.object(build_public_export, "ROOT", synth):
                ok = export_sanitized_public_tree(target, public_safe_profile=True)
            self.assertTrue(ok)

            self.assertEqual((target / ".pre-commit-config.yaml").read_bytes(), staged_a)
            self.assertEqual(victim.read_bytes(), worktree_b)
            index_a = run_git(
                ["show", ":.pre-commit-config.yaml"],
                cwd=synth, capture_output=True, check=True,
            ).stdout
            self.assertEqual(index_a, staged_a)

            policy = publication_policy.load_policy(
                synth / "assets" / "public_source_profile.json"
            )
            materialized = _tree_bytes(target)
            included = [
                (rel, raw)
                for rel, raw in materialized.items()
                if policy.resolve(rel).disposition == "included"
            ]
            self.assertIn(".pre-commit-config.yaml", [rel for rel, _ in included])
            manifest = json.loads(
                (target / "PUBLIC_EXPORT.json").read_text(encoding="utf-8")
            )
            digest_a = public_export.content_digest(included)
            self.assertEqual(digest_a, manifest["included_content_sha256"])
            included_b = [
                (rel, worktree_b if rel == ".pre-commit-config.yaml" else raw)
                for rel, raw in included
            ]
            self.assertNotEqual(public_export.content_digest(included_b), digest_a)

    def test_export_handles_source_and_target_paths_with_spaces(self):
        # Property: both a source path containing spaces and an export target
        # path containing spaces materialize byte-exact.
        with tempfile.TemporaryDirectory() as tmpdir:
            synth = Path(tmpdir) / "source repo"
            synth.mkdir()
            _git(["init", "-q"], synth)
            nested = synth / "docs" / "dir with space"
            nested.mkdir(parents=True)
            (nested / "file name.md").write_text("# spaced\n", encoding="utf-8", newline="\n")
            (synth / "README.md").write_text("readme\n", encoding="utf-8", newline="\n")
            _git(["add", "-A"], synth)

            target = Path(tmpdir) / "export with spaces" / "public export"
            with mock.patch.object(build_public_export, "ROOT", synth):
                ok = export_sanitized_public_tree(target, public_safe_profile=False)
            self.assertTrue(ok)
            materialized = target / "docs" / "dir with space" / "file name.md"
            self.assertEqual(materialized.read_text(encoding="utf-8"), "# spaced\n")


if __name__ == "__main__":
    unittest.main()
