# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 the Nakagawa Recomp authors

"""The v0.0.1 player package route on a source-owned fixture (#509).

A consumer's whole route is: add an ISO, press BUILD PACKAGE, press PLAY. Every
other gate proves one of those halves on its own. This one drives both halves
the way the player does, on a source-owned fixture, with no mocked compilation:

  * the build half runs ``package_builder_start`` -- the player's own BUILD
    PACKAGE action, which spawns ``tools/nk_cli.py build-package`` and reads its
    progress stream -- against real analysis, real AOT codegen and a real
    ``gcc``/``mingw32-make`` link of the display/presentation fixture;
  * the package is then checked with the player's own validator
    (``player_app_validate_runtime_package``);
  * the launch half runs the player executable's ``--launch-index`` route with
    ``--headless-launch``, the headless sibling of PLAY NOW, so a host with no
    display still reaches ``player_app_launch_game`` -> ``nk_launch_start`` and
    the guest actually runs;
  * two missing-prerequisite boundaries must arrive as the player's named,
    structured failures instead of a silent package;
  * the whole route must leave every repository-tracked file untouched.

The fixture is the source-owned display smoke guest generated by
``fixtures/display_smoke/generate.py``: hand-assembled MIPS from a committed
recipe, no PSPDEV toolchain, no retail bytes. It is the only public-scope title
the native player can launch, so it is the one fixture that can carry this
route. A host without the documented toolchain is a SKIP with the Makefile's own
remedy, never a silent pass.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

from test_iso_parity import (  # noqa: E402
    build_psp_container,
    create_test_iso_with_executables,
)

SHOWCASE_FIXTURE_DIR = ROOT / "fixtures" / "showcase"
if str(SHOWCASE_FIXTURE_DIR) not in sys.path:
    sys.path.insert(0, str(SHOWCASE_FIXTURE_DIR))
from showcase import DEMOS as SHOWCASE_DEMOS, make_icon_png, write_iso  # noqa: E402

# Short enough to keep the hosted run quick, long enough that the guest really
# presents frames. The guest loops this many times, one vblank wait each.
FRAMES = 8
# The synthetic disc identity this route imports under. It is the identity the
# ISO parity fixtures already use; TEST00001 and friends belong to the bundled
# demo library.
DISC_ID = "ULUS99998"
TITLE_ID = "experimental-ulus99998"
LAUNCH_TIMEOUT_MS = 180000


def synthetic_manifest() -> dict:
    """The hand-written title manifest this route binds the imported disc to.

    The build half consumes this from the library's experimental profile, so it is
    the consumer-facing spelling of a title the analyzer never derived for us.
    tools/test_player_package_determinism.py contrasts it with the same manifest
    whose guest addresses come from the fixture recipe's generated metadata.
    """
    return {
        "schema_version": 1,
        "id": TITLE_ID,
        "display_name": "Synthetic player package route",
        "kind": "retail",
        "disc": {"id": DISC_ID, "region": "NA", "revision_policy": "exact-disc-id"},
        "game_name": "display_smoke",
        "executable": {
            "base": 0x08810000,
            "entry": 0x08810000,
            "bss_metadata_source": "elf",
            "extra_executable_spans": [],
        },
        "modules": [],
        "filesystem": {
            "data_root": "fixtures/display_smoke",
            "memory_stick_root": "build/display-smoke-v1/memstick",
            "device_prefixes": ["host0:", "ms0:"],
        },
        "hle_profile": "synthetic-minimal",
        "codegen_profile": "none",
        "feature_requirements": ["allegrex-core", "psp-hle"],
        "verification_profile": "synthetic-public",
    }


def tracked_status() -> str:
    """The repository's tracked-file status, with untracked output excluded."""
    completed = subprocess.run(
        ["git", "-C", str(ROOT), "status", "--porcelain", "--untracked-files=no"],
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        raise AssertionError(f"git status failed: {completed.stderr.strip()}")
    return completed.stdout


def align_executable(executable: bytes) -> bytes:
    """Make a source-owned ELF satisfy the ISO preflight's alignment congruence.

    The generated guests use load-relative zero addresses. Only the program
    headers' congruence field is written; no code or data byte changes.
    """
    patched = bytearray(executable)
    phoff = struct.unpack_from("<I", patched, 28)[0]
    phnum = struct.unpack_from("<H", patched, 44)[0]
    for index in range(phnum):
        struct.pack_into("<I", patched, phoff + index * 32 + 28, 0x100)
    return bytes(patched)


class TestPlayerPackageRoute(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="nk-player-route-")
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.fixture_dir = self.root / "fixture"
        self.user_root = self.root / "user"
        self.local_appdata = self.root / "localappdata"
        self.sandbox = self.root / "sandbox"
        for directory in (self.user_root, self.local_appdata, self.sandbox):
            directory.mkdir(parents=True)
        self.player = ROOT / "build" / ("nakagawa_player.exe" if os.name == "nt" else "nakagawa_player")
        self.harness = ROOT / "build" / (
            "test_package_builder.exe" if os.name == "nt" else "test_package_builder"
        )
        self.validator = ROOT / "build" / (
            "test_player_state.exe" if os.name == "nt" else "test_player_state"
        )
        self.manifest = self.generate_fixture()

    # ---- fixture and library -------------------------------------------------

    def generate_fixture(self) -> dict:
        """Generate the source-owned guest and its per-user library entry.

        The ISO carries the guest's own bytes as EBOOT.BIN so the build half
        reads a real disc image, and the executable is bound to an experimental
        profile carrying the display-smoke manifest -- the same binding an
        imported uncatalogued disc gets.
        """
        completed = subprocess.run(
            [sys.executable, str(ROOT / "fixtures" / "display_smoke" / "generate.py"),
             "generate", "--out-dir", str(self.fixture_dir), "--frames", str(FRAMES)],
            cwd=ROOT, capture_output=True, text=True,
        )
        self.assertEqual(completed.returncode, 0, completed.stdout + completed.stderr)

        executable = bytearray((self.fixture_dir / "guest.prx").read_bytes())
        # The generated bytes use load-relative zero addresses; only the
        # program headers change on the way into the disc image.
        executable_bytes = align_executable(bytes(executable))

        iso_path = self.root / "synthetic.iso"
        create_test_iso_with_executables(iso_path, executable_bytes, disc_id=DISC_ID)
        digest = hashlib.sha256(executable_bytes).hexdigest()
        self.executable_sha256 = digest

        manifest = synthetic_manifest()
        self.stage_library(self.user_root, manifest, iso_path, executable_bytes)
        return manifest

    def stage_library(self, user_root: Path, manifest: dict, iso_path: Path,
                      executable_bytes: bytes) -> None:
        digest = hashlib.sha256(executable_bytes).hexdigest()
        profile_dir = user_root / "experimental" / DISC_ID
        profile_dir.mkdir(parents=True, exist_ok=True)
        profile = {
            "schema_version": 1,
            "manifest": manifest,
            "input_identity": {
                "disc_id": DISC_ID,
                "selected_executable": "PSP_GAME/SYSDIR/EBOOT.BIN",
                "executable_sha256": digest,
                "elf_sha256": digest,
            },
        }
        (profile_dir / "profile.json").write_text(
            json.dumps(profile, sort_keys=True) + "\n", encoding="utf-8"
        )
        (user_root / "library.json").write_text(json.dumps({
            "schema_version": 1,
            "games": [{
                "disc_id": DISC_ID,
                "title_id": manifest["id"],
                "iso_path": str(iso_path),
                "selected_executable": "EBOOT.BIN",
                "is_experimental": True,
            }],
        }), encoding="utf-8")

    def write_player_library(self) -> Path:
        """Put the library entry where the player reads it: its own data dir."""
        library_dir = self.local_appdata / "Nakagawa" / "data"
        library_dir.mkdir(parents=True, exist_ok=True)
        library = library_dir / "library.json"
        library.write_bytes((self.user_root / "library.json").read_bytes())
        return library

    # ---- prerequisites -------------------------------------------------------

    def skip_if_toolchain_unavailable(self) -> None:
        required = ("mingw32-make", "gcc", "pwsh", "git")
        missing = [name for name in required if not shutil.which(name)]
        if missing:
            self.skipTest(
                "the player package route requires " + ", ".join(missing) + " on PATH"
            )
        # The package route links SDL3; a host without the supported toolchain
        # is a SKIP carrying the Makefile's own remedy, not a failed route.
        make_name = "mingw32-make" if os.name == "nt" else "make"
        probe = subprocess.run(
            [make_name, "--no-print-directory", "sdl3-check"],
            cwd=ROOT, capture_output=True, text=True,
        )
        self.skip_if_toolchain_unusable(probe)
        for binary in (self.player, self.harness, self.validator):
            if not binary.is_file():
                built = subprocess.run(
                    [make_name, "--no-print-directory", "player", "player-state-test-bin",
                     "package-builder-test-bin"],
                    cwd=ROOT, capture_output=True, text=True,
                )
                self.skip_if_toolchain_unusable(built)
                if not binary.is_file():
                    self.skipTest(f"the player package route needs {binary.name}; build failed")

    def skip_if_toolchain_unusable(self, run) -> None:
        output = run.stdout + run.stderr
        if run.returncode != 0 and "sdl3 dependency is missing" in output.lower():
            reason = next(line for line in output.splitlines()
                          if "sdl3 dependency is missing" in line.lower())
            self.skipTest(reason.strip())

    # ---- the two halves ------------------------------------------------------

    def run_build_action(self, user_root: Path) -> subprocess.CompletedProcess:
        """Press BUILD PACKAGE: the player's own session, start to finish."""
        return subprocess.run(
            [str(self.harness), "--build-package", str(ROOT), str(user_root), DISC_ID,
             str(user_root / "logs")],
            cwd=ROOT, capture_output=True, text=True, timeout=1800,
        )

    def run_validator(self) -> subprocess.CompletedProcess:
        return subprocess.run(
            [str(self.validator), "--validate-package", str(self.user_root), DISC_ID,
             TITLE_ID, "1", "EBOOT.BIN"],
            cwd=ROOT, capture_output=True, text=True,
        )

    def run_launch(self, boot_log: Path, perf_csv: Path) -> subprocess.CompletedProcess:
        environment = os.environ.copy()
        environment["LOCALAPPDATA"] = str(self.local_appdata)
        environment["SR_BOOT_EVENT_FILE"] = str(boot_log)
        # The opt-in child evidence channels. SR_PERF_CSV is how a launcher
        # proves the guest consumed vblanks without reading the child's stderr,
        # which is not a stable API of either process backend.
        environment["SR_PERF"] = "1"
        environment["SR_PERF_CSV"] = str(perf_csv)
        ucrt_bin = Path("C:/msys64/ucrt64/bin")
        if os.name == "nt" and ucrt_bin.is_dir():
            environment["PATH"] = str(ucrt_bin) + os.pathsep + environment.get("PATH", "")
        return subprocess.run(
            [str(self.player), "--empty", "--launch-index=0", "--headless-launch",
             f"--runtime-root={self.user_root}"],
            cwd=ROOT, env=environment, capture_output=True, text=True,
            timeout=LAUNCH_TIMEOUT_MS / 1000,  # subprocess.run takes seconds
        )

    def test_release_package_layout_finds_public_cli(self):
        self.skip_if_toolchain_unavailable()
        package = self.root / "release-package"
        install_root = package / "bin"
        cli = package / "source" / "tools" / "nk_cli.py"
        cli.parent.mkdir(parents=True)
        install_root.mkdir()
        cli.write_text("# source-owned test fixture\n", encoding="utf-8")

        completed = subprocess.run(
            [str(self.harness), "--find-cli", str(install_root)],
            cwd=package, capture_output=True, text=True,
        )
        self.assertEqual(completed.returncode, 0, completed.stdout + completed.stderr)
        self.assertIn("PACKAGE_BUILDER_CLI status=PASS", completed.stdout)
        discovered = completed.stdout.partition("path=")[2].strip()
        self.assertEqual(Path(discovered).resolve(), cli.resolve())

    def test_source_owned_showcase_iso_without_companion_assets_stages(self):
        self.skip_if_toolchain_unavailable()
        demo = next(item for item in SHOWCASE_DEMOS if item["disc_id"] == "TEST00007")
        executable = align_executable((self.fixture_dir / "guest.prx").read_bytes())
        iso_path = self.root / "showcase-without-xbdata.iso"
        write_iso(
            iso_path,
            "TEST00007",
            "Nakagawa 3D Showcase",
            make_icon_png(demo["palette"]),
            executable,
            b"Source-owned synthetic notice\n",
        )

        environment = os.environ.copy()
        environment["LOCALAPPDATA"] = str(self.local_appdata)
        environment["APPDATA"] = str(self.root / "appdata")
        environment["USERPROFILE"] = str(self.root / "userprofile")
        completed = subprocess.run(
            [str(self.player), f"--iso={iso_path}", "--stage-only"],
            cwd=ROOT, env=environment, capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(completed.returncode, 0,
                         completed.stdout + completed.stderr)
        self.assertIn("STAGING_RESULT status=PASS", completed.stdout)

    def test_build_validates_and_launches_through_the_player(self):
        self.skip_if_toolchain_unavailable()
        before = tracked_status()

        # 1. BUILD PACKAGE, through the player's own session, with real
        #    analysis, codegen and compilation.
        built = self.run_build_action(self.user_root)
        self.assertEqual(built.returncode, 0, built.stdout[-4000:] + built.stderr[-4000:])
        self.assertIn("PACKAGE_BUILD_ROUTE status=PASS", built.stdout)
        self.assertIn("complete=1", built.stdout)
        # The child really analysed, generated and compiled: its own log names
        # the codegen entry point and the compiler that linked the runtime.
        log_path = self.user_root / "logs" / f"build_{DISC_ID}.log"
        build_log = log_path.read_text(encoding="utf-8", errors="replace")
        self.assertIn("title_codegen_plan.py", build_log)
        self.assertIn("gcc", build_log)
        self.assertIn("Build finished:", build_log)
        package_dir = self.user_root / "packages" / DISC_ID
        self.assertTrue((package_dir / "package.json").is_file())
        self.assertTrue((package_dir / "build-report.json").is_file())
        self.assertTrue((package_dir / "display_smoke.exe").is_file())

        # 2. The player's own validator accepts what the action produced.
        validated = self.run_validator()
        self.assertEqual(validated.returncode, 0, validated.stdout + validated.stderr)
        self.assertIn("PACKAGE_STATUS=OK", validated.stdout)

        # 3. PLAY, headless, through the player's own launch session. The player
        #    reads its library from its own per-user data directory, so the
        #    entry the build half consumed is the entry the launch half sees.
        self.write_player_library()
        boot_log = self.sandbox / "boot-events.log"
        perf_csv = self.sandbox / "perf.csv"
        launched = self.run_launch(boot_log, perf_csv)
        self.assertEqual(launched.returncode, 0,
                         launched.stdout[-4000:] + launched.stderr[-4000:])
        self.assertIn("[PLAYER] Launch index 0: PLAY NOW available", launched.stdout)
        self.assertIn("[PLAYER] Launch argv contains --gui: no", launched.stdout)
        self.assertIn("[PLAYER] Headless launch child exited with code 0", launched.stdout)

        # 4. Guest-visible startup state, from the child's own evidence file.
        self.assertTrue(boot_log.is_file(), "the child runtime wrote no boot evidence")
        events = boot_log.read_text(encoding="utf-8", errors="replace")
        for milestone in (
            "BOOT_EVENT phase=init public_safe=1",
            "BOOT_EVENT phase=image_loaded",
            "BOOT_EVENT phase=runtime_registered",
            "BOOT_EVENT phase=index_prepare_end",
            "BOOT_EVENT phase=guest_start mode=scheduler",
        ):
            self.assertIn(milestone, events)
        for forbidden in ("UNKNOWN NID", "NONPLT_MISS", "INTERP_REJECT", "DRIVER_EXPECT_U32"):
            self.assertNotIn(forbidden, events)

        # 5. The fixture's frame checkpoint: the guest consumed the vblanks its
        #    frame loop waits for, so a launch that never delivered a vblank
        #    cannot pass this.
        self.assertTrue(perf_csv.is_file(), "the child runtime wrote no perf CSV")
        rows = perf_csv.read_text(encoding="utf-8", errors="replace").splitlines()
        self.assertGreaterEqual(len(rows), 2, "the perf CSV has header and summary rows only")
        header = rows[0].split(",")
        self.assertEqual(header[0], "vblank_total")
        vblank_total = int(rows[-1].split(",")[0])
        self.assertGreaterEqual(vblank_total, FRAMES)

        # 6. Nothing this route did reached a repository-tracked file.
        self.assertEqual(tracked_status(), before)

        # 7. Negative control. A tampered package must fail closed at the
        #    validator and the launch, which is what makes steps 2 to 5
        #    load-bearing rather than decorative.
        executable = package_dir / "display_smoke.exe"
        executable.write_bytes(executable.read_bytes() + b"tampered")
        stale = self.run_validator()
        self.assertEqual(stale.returncode, 0, stale.stdout + stale.stderr)
        self.assertIn("PACKAGE_STATUS=STALE", stale.stdout)
        refused_boot_log = self.sandbox / "refused-boot-events.log"
        refused = self.run_launch(refused_boot_log, self.sandbox / "refused-perf.csv")
        self.assertNotEqual(refused.returncode, 0)
        self.assertIn("PLAY NOW is unavailable", refused.stdout + refused.stderr)
        self.assertFalse(refused_boot_log.exists(),
                         "a stale package must not reach a guest run")
        self.assertEqual(tracked_status(), before)

    def test_missing_prerequisites_fail_closed_with_documented_codes(self):
        self.skip_if_toolchain_unavailable()
        before = tracked_status()

        # (a) A missing input: the disc's executable is still the encrypted
        #     PSP container, so the route must name the decrypted-module
        #     boundary instead of producing a package.
        encrypted_root = self.root / "encrypted-input"
        encrypted_root.mkdir()
        encrypted_iso = encrypted_root / "disc.iso"
        create_test_iso_with_executables(
            encrypted_iso, build_psp_container(), disc_id=DISC_ID
        )
        self.stage_library(encrypted_root, self.manifest, encrypted_iso,
                           build_psp_container())
        encrypted = self.run_build_action(encrypted_root)
        self.assertNotEqual(encrypted.returncode, 0)
        self.assertIn("PACKAGE_BUILD_ROUTE status=FAIL", encrypted.stdout)
        self.assertIn("[preflight] FAIL: Encrypted executable", encrypted.stdout)
        self.assertIn("supply decrypted modules at", encrypted.stdout)
        self.assertIn("(#295)", encrypted.stdout)
        self.assertIn("in the works", encrypted.stdout)
        self.assertFalse((encrypted_root / "packages" / DISC_ID).exists())

        # (b) A missing prerequisite the manifest itself names: it reads BSS
        #     metadata from the disc's ~PSP header, and this disc's executable
        #     has none. The build must say which input is missing, not fall
        #     back to a guess.
        header_manifest = dict(self.manifest)
        header_manifest["executable"] = dict(
            self.manifest["executable"], bss_metadata_source="psp-header"
        )
        header_root = self.root / "missing-psp-header"
        header_root.mkdir()
        header_iso = header_root / "disc.iso"
        header_elf = align_executable((self.fixture_dir / "guest.prx").read_bytes())
        create_test_iso_with_executables(header_iso, header_elf, disc_id=DISC_ID)
        self.stage_library(header_root, header_manifest, header_iso, header_elf)
        header = self.run_build_action(header_root)
        self.assertNotEqual(header.returncode, 0)
        self.assertIn("PACKAGE_BUILD_ROUTE status=FAIL", header.stdout)
        self.assertIn("[extract] FAIL: This manifest reads BSS metadata", header.stdout)
        self.assertIn("provide --psp-header (#296)", header.stdout)
        self.assertFalse((header_root / "packages" / DISC_ID).exists())

        self.assertEqual(tracked_status(), before)


if __name__ == "__main__":
    unittest.main()
