# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 the Nakagawa Recomp authors

"""The v0.0.1 player package route on a source-owned fixture (#509).

A consumer's whole route is: add an ISO, press BUILD PACKAGE, press PLAY. Every
other gate proves one of those halves on its own. This one drives both halves
the way the player does, on a source-owned fixture, with no mocked compilation:

  * the build half runs ``package_builder_start`` -- the player's own BUILD
    PACKAGE action, which spawns ``tools/nk_cli.py build-package`` and reads its
    progress stream -- against real analysis, real AOT codegen and a real
    ``gcc``/``mingw32-make`` link of the display/presentation fixture;
  * the package is then checked with the player's own validator
    (``player_app_validate_runtime_package``);
  * the launch half runs the player executable's ``--launch-index`` route with
    ``--headless-launch``, the headless sibling of PLAY NOW, so a host with no
    display still reaches ``player_app_launch_game`` -> ``nk_launch_start`` and
    the guest actually runs;
  * two missing-prerequisite boundaries must arrive as the player's named,
    structured failures instead of a silent package;
  * the whole route must leave every repository-tracked file untouched.

The fixture is the source-owned display smoke guest generated by
``fixtures/display_smoke/generate.py``: hand-assembled MIPS from a committed
recipe, no PSPDEV toolchain, no retail bytes. It is the only public-scope title
the native player can launch, so it is the one fixture that can carry this
route. A host without the documented toolchain is a SKIP with the Makefile's own
remedy, never a silent pass.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch


ROOT = Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

import nk_cli  # noqa: E402
from nk_core import package_cache  # noqa: E402
from import_fixtures import BASE_VADDR, _elf  # noqa: E402
from test_iso_parity import (  # noqa: E402
    build_psp_container,
    create_test_iso_with_executables,
    create_test_iso_with_modules,
)

SHOWCASE_FIXTURE_DIR = ROOT / "fixtures" / "showcase"
if str(SHOWCASE_FIXTURE_DIR) not in sys.path:
    sys.path.insert(0, str(SHOWCASE_FIXTURE_DIR))
from showcase import DEMOS as SHOWCASE_DEMOS, make_icon_png, write_iso  # noqa: E402

# Short enough to keep the hosted run quick, long enough that the guest really
# presents frames. The guest loops this many times, one vblank wait each.
FRAMES = 8
# The synthetic disc identity this route imports under. It is the identity the
# ISO parity fixtures already use; TEST00001 and friends belong to the bundled
# demo library.
DISC_ID = "ULUS99998"
TITLE_ID = "experimental-ulus99998"
LAUNCH_TIMEOUT_MS = 180000


def synthetic_manifest() -> dict:
    """The hand-written title manifest this route binds the imported disc to.

    The build half consumes this from the library's experimental profile, so it is
    the consumer-facing spelling of a title the analyzer never derived for us.
    tools/test_player_package_determinism.py contrasts it with the same manifest
    whose guest addresses come from the fixture recipe's generated metadata.
    """
    return {
        "schema_version": 1,
        "id": TITLE_ID,
        "display_name": "Synthetic player package route",
        "kind": "retail",
        "disc": {"id": DISC_ID, "region": "NA", "revision_policy": "exact-disc-id"},
        "game_name": "display_smoke",
        "executable": {
            "base": 0x08810000,
            "entry": 0x08810000,
            "bss_metadata_source": "elf",
            "extra_executable_spans": [],
        },
        "modules": [],
        "filesystem": {
            "data_root": "fixtures/display_smoke",
            "memory_stick_root": "build/display-smoke-v1/memstick",
            "device_prefixes": ["host0:", "ms0:"],
        },
        "hle_profile": "synthetic-minimal",
        "codegen_profile": "none",
        "feature_requirements": ["allegrex-core", "psp-hle"],
        "verification_profile": "synthetic-public",
    }


def native_legacy_experimental_manifest() -> dict:
    """The generic zero-layout profile shape emitted by the native importer."""
    return {
        "schema_version": 1,
        "id": TITLE_ID,
        "game_name": TITLE_ID,
        "display_name": "Synthetic Experimental Disc",
        "kind": "retail",
        "disc": {"id": DISC_ID, "region": "NA", "revision_policy": "exact-disc-id"},
        "executable": {
            "base": 0,
            "entry": 0,
            "bss_metadata_source": "none",
            "extra_executable_spans": [],
        },
        "modules": [],
        "filesystem": {
            "data_root": "data",
            "memory_stick_root": "savedata",
            "device_prefixes": ["disc0:", "ms0:"],
        },
        "hle_profile": "generic",
        "feature_requirements": [],
        "verification_profile": "experimental-unverified",
    }


def synthetic_required_module() -> bytes:
    """Build a tiny project-owned PRX ELF with a bounded module-info section."""
    segment = bytearray(128)
    segment[4:11] = b"fixture"
    struct.pack_into("<I", segment, 32, BASE_VADDR + 64)
    struct.pack_into("<2I", segment, 64, 0x03E00008, 0)  # jr $ra; nop
    return _elf(
        bytes(segment),
        BASE_VADDR,
        extra_sections=[(b".text", BASE_VADDR + 64, 8)],
    )


class TestPackageRuntimeDependencies(unittest.TestCase):
    def test_embeddable_cli_restores_tools_directory_to_import_path(self):
        tools_directory = str(Path(nk_cli.__file__).resolve().parent)
        with patch.object(nk_cli.sys, "path", []):
            nk_cli._ensure_cli_module_path()
            self.assertEqual(nk_cli.sys.path, [tools_directory])

    def test_codegen_plan_restores_tools_directory_for_embedded_python(self):
        script = TOOLS / "title_codegen_plan.py"
        code = (
            "import runpy, sys\n"
            f"script = {str(script)!r}\n"
            "sys.argv = [script, '--help']\n"
            "runpy.run_path(script, run_name='__main__')\n"
        )
        completed = subprocess.run(
            [sys.executable, "-I", "-c", code], cwd=ROOT,
            capture_output=True, text=True, timeout=20,
        )
        self.assertEqual(completed.returncode, 0,
                         completed.stdout + completed.stderr)
        self.assertIn("usage:", completed.stdout.lower())

    def test_title_runtime_config_restores_tools_directory_for_embedded_python(self):
        script = TOOLS / "title_runtime_config.py"
        code = (
            "import runpy, sys\n"
            f"script = {str(script)!r}\n"
            "sys.argv = [script, '--help']\n"
            "runpy.run_path(script, run_name='__main__')\n"
        )
        completed = subprocess.run(
            [sys.executable, "-I", "-c", code], cwd=ROOT,
            capture_output=True, text=True, timeout=20,
        )
        self.assertEqual(completed.returncode, 0,
                         completed.stdout + completed.stderr)
        self.assertIn("usage:", completed.stdout.lower())

    def test_codegen_restores_tools_directory_for_embedded_python(self):
        script = TOOLS / "codegen.py"
        code = (
            "import importlib.util, sys\n"
            f"script = {str(script)!r}\n"
            "spec = importlib.util.spec_from_file_location('embedded_codegen', script)\n"
            "module = importlib.util.module_from_spec(spec)\n"
            "sys.modules[spec.name] = module\n"
            "spec.loader.exec_module(module)\n"
        )
        completed = subprocess.run(
            [sys.executable, "-I", "-c", code], cwd=ROOT,
            capture_output=True, text=True, timeout=20,
        )
        self.assertEqual(completed.returncode, 0,
                         completed.stdout + completed.stderr)

    def test_prxload_and_imports_restore_tools_directory_for_embedded_python(self):
        for name in ("prxload.py", "imports.py"):
            with self.subTest(script=name):
                script = TOOLS / name
                code = (
                    "import importlib.util, sys\n"
                    f"script = {str(script)!r}\n"
                    "spec = importlib.util.spec_from_file_location('embedded_tool', script)\n"
                    "module = importlib.util.module_from_spec(spec)\n"
                    "sys.modules[spec.name] = module\n"
                    "spec.loader.exec_module(module)\n"
                )
                completed = subprocess.run(
                    [sys.executable, "-I", "-c", code], cwd=ROOT,
                    capture_output=True, text=True, timeout=20,
                )
                self.assertEqual(completed.returncode, 0,
                                 completed.stdout + completed.stderr)

    def test_runtime_package_uses_the_configured_sdl3_provider(self):
        with tempfile.TemporaryDirectory(prefix="nk-sdl3-package-") as temporary:
            root = Path(temporary)
            provider = root / "ucrt64"
            runtime = provider / "bin" / "SDL3.dll"
            iconv = provider / "bin" / "libiconv-2.dll"
            vulkan = provider / "bin" / "vulkan-1.dll"
            runtime.parent.mkdir(parents=True)
            runtime.write_bytes(b"source-owned synthetic SDL3 test payload")
            iconv.write_bytes(b"source-owned synthetic iconv test payload")
            vulkan.write_bytes(b"source-owned synthetic Vulkan test payload")
            package = root / "package"
            package.mkdir()
            with patch.dict(os.environ, {
                "SDL3_DIR": str(provider), "SDL3_DLL": "",
                "VULKAN_SDK": str(provider),
            }):
                with patch("nk_cli._windows_host", return_value=True):
                    nk_cli._stage_runtime_assets(package)
            self.assertEqual((package / "SDL3.dll").read_bytes(), runtime.read_bytes())
            self.assertEqual((package / "libiconv-2.dll").read_bytes(), iconv.read_bytes())
            self.assertEqual((package / "vulkan-1.dll").read_bytes(), vulkan.read_bytes())

    def test_runtime_package_fails_closed_without_vulkan_loader(self):
        with tempfile.TemporaryDirectory(prefix="nk-vulkan-package-") as temporary:
            root = Path(temporary)
            provider = root / "ucrt64"
            sdl = provider / "bin" / "SDL3.dll"
            sdl.parent.mkdir(parents=True)
            sdl.write_bytes(b"source-owned synthetic SDL3 test payload")
            (provider / "bin" / "libiconv-2.dll").write_bytes(
                b"source-owned synthetic iconv test payload"
            )
            package = root / "package"
            package.mkdir()
            with patch.dict(os.environ, {
                "SDL3_DIR": str(provider), "SDL3_DLL": "",
                "VULKAN_SDK": str(root / "missing-sdk"),
            }):
                with patch("nk_cli._windows_host", return_value=True), patch("nk_cli.shutil.which", return_value=None):
                    with self.assertRaisesRegex(nk_cli.PackageBuildError, "vulkan-1.dll"):
                        nk_cli._stage_runtime_assets(package)

    @unittest.skipUnless(os.name == "nt", "Windows UCRT path precedence")
    def test_runtime_build_keeps_an_available_downloaded_toolchain_first(self):
        with tempfile.TemporaryDirectory(prefix="nk-ucrt-path-") as temporary:
            toolchain_bin = Path(temporary) / "ucrt64" / "bin"
            toolchain_bin.mkdir(parents=True)
            (toolchain_bin / "gcc.exe").write_bytes(b"synthetic executable path marker")
            with patch.dict(os.environ, {"PATH": str(toolchain_bin)}):
                env = nk_cli._runtime_build_environment()
            self.assertEqual(env["PATH"].split(os.pathsep, 1)[0], str(toolchain_bin))

    @unittest.skipUnless(os.name == "nt", "Windows embedded Python path")
    def test_runtime_build_exposes_its_interpreter_after_the_downloaded_toolchain(self):
        with tempfile.TemporaryDirectory(prefix="nk-package-python-path-") as temporary:
            root = Path(temporary)
            toolchain_bin = root / "ucrt64" / "bin"
            python_bin = root / "python"
            toolchain_bin.mkdir(parents=True)
            python_bin.mkdir()
            (toolchain_bin / "gcc.exe").write_bytes(b"synthetic executable path marker")
            interpreter = python_bin / "python.exe"
            interpreter.write_bytes(b"synthetic executable path marker")
            with patch.dict(os.environ, {"PATH": str(toolchain_bin) + os.pathsep + r"C:\Windows"}):
                with patch("nk_cli.sys.executable", str(interpreter)):
                    path = nk_cli._runtime_build_environment()["PATH"].split(os.pathsep)
            self.assertEqual(path[:2], [str(toolchain_bin), str(python_bin)])


def tracked_status() -> str:
    """The repository's tracked-file status, with untracked output excluded."""
    completed = subprocess.run(
        ["git", "-C", str(ROOT), "status", "--porcelain", "--untracked-files=no"],
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        raise AssertionError(f"git status failed: {completed.stderr.strip()}")
    return completed.stdout


def align_executable(executable: bytes) -> bytes:
    """Make a source-owned ELF satisfy the ISO preflight's alignment congruence.

    The generated guests use load-relative zero addresses. Only the program
    headers' congruence field is written; no code or data byte changes.
    """
    patched = bytearray(executable)
    phoff = struct.unpack_from("<I", patched, 28)[0]
    phnum = struct.unpack_from("<H", patched, 44)[0]
    for index in range(phnum):
        struct.pack_into("<I", patched, phoff + index * 32 + 28, 0x100)
    return bytes(patched)


class TestReleaseDocumentation(unittest.TestCase):
    def test_release_docs_match_current_player_boundaries(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        preview = (ROOT / "docs" / "PREVIEW_RELEASE.md").read_text(encoding="utf-8")
        smoke = (ROOT / "docs" / "SMOKE_TEST.md").read_text(encoding="utf-8")
        release_notes = (ROOT / "docs" / "RELEASE_NOTES_v0.0.1.md").read_text(encoding="utf-8")

        self.assertIn("PAC-MAN Championship Edition", readme)
        self.assertIn("#556", readme)
        self.assertIn("#308", readme)
        self.assertNotIn("#285", readme)
        self.assertIn("in the works", readme.lower())
        self.assertIn("START SETUP WIZARD", readme)
        self.assertIn("ADD ANOTHER ISO", readme)
        self.assertNotIn("click **Add Game**", readme)
        self.assertNotIn("No second verified title.", readme)
        self.assertIn("consent once", readme.lower())
        self.assertNotIn("automatic decryption is in the works", readme.lower())
        self.assertIn("#548", readme)
        self.assertIn("#550", readme)
        self.assertIn("#308", release_notes)
        self.assertNotIn("#285", release_notes)
        self.assertIn("PGD-protected content is unsupported", release_notes)
        self.assertIn("broader ISO-to-Play support is in the works", release_notes)
        self.assertNotIn("PGD-protected content remains unsupported ([#295]", release_notes)
        self.assertIn("#547", preview)
        self.assertNotIn("automatic prerequisite installation is in the works", preview.lower())
        self.assertIn("-ExcludeOptionalFonts", preview)
        self.assertIn("tools/stage_runtime_dlls.py --target $Bin", preview)
        self.assertIn("stage_runtime_dlls.py failed with exit code", preview)
        self.assertIn("SDL3.dll", release_notes)
        self.assertIn("SDL3_ttf", release_notes)
        self.assertIn("#556", release_notes)
        self.assertNotIn("SDL3_ttf` is optional and is not part of the release package", release_notes)
        self.assertIn("prerequisite consent", smoke.lower())
        self.assertIn("#547", smoke)
        self.assertNotIn("consent-based installation is still in the works", smoke.lower())


class TestSourceMediaIdentity(unittest.TestCase):
    def test_required_module_without_name_has_named_package_error(self):
        manifest = {"modules": [{"role": "guest-prx", "required": True}]}
        with patch.object(nk_cli, "_hash_iso_member", return_value="1" * 64):
            with self.assertRaisesRegex(
                nk_cli.PackageBuildError,
                "required guest-prx manifest record is missing its name",
            ):
                nk_cli._source_media_identity(Path("synthetic.iso"), "EBOOT.BIN", manifest)

    def test_required_guest_path_rejects_empty_components(self):
        manifest = {"modules": [{
            "name": "fixture.prx",
            "role": "guest-prx",
            "required": True,
            "guest_path": "disc0:/PSP_GAME//USRDIR/fixture.prx",
        }]}
        with patch.object(nk_cli, "_hash_iso_member", return_value="1" * 64):
            with self.assertRaisesRegex(
                nk_cli.PackageBuildError, "Guest module path contains an empty component"
            ):
                nk_cli._source_media_identity(
                    Path("synthetic.iso"), "EBOOT.BIN", manifest
                )


class TestPlayerPackageRoute(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="nk-player-route-")
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.fixture_dir = self.root / "fixture"
        self.user_root = self.root / "user"
        self.local_appdata = self.root / "localappdata"
        self.sandbox = self.root / "sandbox"
        for directory in (self.user_root, self.local_appdata, self.sandbox):
            directory.mkdir(parents=True)
        self.player = ROOT / "build" / ("nakagawa_player.exe" if os.name == "nt" else "nakagawa_player")
        self.harness = ROOT / "build" / (
            "test_package_builder.exe" if os.name == "nt" else "test_package_builder"
        )
        self.validator = ROOT / "build" / (
            "test_player_state.exe" if os.name == "nt" else "test_player_state"
        )
        self.manifest = self.generate_fixture()

    # ---- fixture and library -------------------------------------------------

    def generate_fixture(self) -> dict:
        """Generate the source-owned guest and its per-user library entry.

        The ISO carries the guest's own bytes as EBOOT.BIN so the build half
        reads a real disc image, and the executable is bound to an experimental
        profile carrying the display-smoke manifest -- the same binding an
        imported uncatalogued disc gets.
        """
        completed = subprocess.run(
            [sys.executable, str(ROOT / "fixtures" / "display_smoke" / "generate.py"),
             "generate", "--out-dir", str(self.fixture_dir), "--frames", str(FRAMES)],
            cwd=ROOT, capture_output=True, text=True,
        )
        self.assertEqual(completed.returncode, 0, completed.stdout + completed.stderr)

        executable = bytearray((self.fixture_dir / "guest.prx").read_bytes())
        # The generated bytes use load-relative zero addresses; only the
        # program headers change on the way into the disc image.
        executable_bytes = align_executable(bytes(executable))
        self.executable_bytes = executable_bytes
        self.module_bytes = synthetic_required_module()
        manifest = synthetic_manifest()
        manifest["modules"] = [{
            "name": "fixture.prx",
            "load_address": 0x08A00000,
            "required": True,
            "role": "guest-prx",
            "guest_path": "disc0:/PSP_GAME/USRDIR/fixture.prx",
        }]

        iso_path = self.root / "synthetic.iso"
        self.iso_path = iso_path
        create_test_iso_with_modules(
            iso_path,
            executable_bytes,
            sysdir_modules={},
            usrdir_modules={"fixture.prx": self.module_bytes},
            disc_id=DISC_ID,
        )
        digest = hashlib.sha256(executable_bytes).hexdigest()
        self.executable_sha256 = digest

        self.stage_library(self.user_root, manifest, iso_path, executable_bytes)
        return manifest

    def stage_library(self, user_root: Path, manifest: dict, iso_path: Path,
                      executable_bytes: bytes) -> None:
        digest = hashlib.sha256(executable_bytes).hexdigest()
        profile_dir = user_root / "experimental" / DISC_ID
        profile_dir.mkdir(parents=True, exist_ok=True)
        profile = {
            "schema_version": 1,
            "manifest": manifest,
            "input_identity": {
                "disc_id": DISC_ID,
                "selected_executable": "PSP_GAME/SYSDIR/EBOOT.BIN",
                "executable_sha256": digest,
                "elf_sha256": digest,
            },
        }
        (profile_dir / "profile.json").write_text(
            json.dumps(profile, sort_keys=True) + "\n", encoding="utf-8"
        )
        (user_root / "library.json").write_text(json.dumps({
            "schema_version": 1,
            "games": [{
                "disc_id": DISC_ID,
                "title_id": manifest["id"],
                "iso_path": str(iso_path),
                "selected_executable": "EBOOT.BIN",
                "is_experimental": True,
            }],
        }), encoding="utf-8")
        data_root = manifest.get("filesystem", {}).get("data_root")
        if data_root:
            (user_root / data_root).mkdir(parents=True, exist_ok=True)

    def write_player_library(self) -> Path:
        """Put the library entry where the player reads it: its own data dir."""
        library_dir = self.local_appdata / "Nakagawa" / "data"
        library_dir.mkdir(parents=True, exist_ok=True)
        library = library_dir / "library.json"
        library.write_bytes((self.user_root / "library.json").read_bytes())
        return library

    # ---- prerequisites -------------------------------------------------------

    def skip_if_toolchain_unavailable(self) -> None:
        required = ("mingw32-make", "gcc", "pwsh", "git")
        missing = [name for name in required if not shutil.which(name)]
        if missing:
            self.skipTest(
                "the player package route requires " + ", ".join(missing) + " on PATH"
            )
        # The package route links SDL3; a host without the supported toolchain
        # is a SKIP carrying the Makefile's own remedy, not a failed route.
        make_name = "mingw32-make" if os.name == "nt" else "make"
        probe = subprocess.run(
            [make_name, "--no-print-directory", "sdl3-check"],
            cwd=ROOT, capture_output=True, text=True,
        )
        self.skip_if_toolchain_unusable(probe)
        for binary in (self.player, self.harness, self.validator):
            if not binary.is_file():
                built = subprocess.run(
                    [make_name, "--no-print-directory", "player", "player-state-test-bin",
                     "package-builder-test-bin"],
                    cwd=ROOT, capture_output=True, text=True,
                )
                self.skip_if_toolchain_unusable(built)
                if not binary.is_file():
                    self.skipTest(f"the player package route needs {binary.name}; build failed")

    def skip_if_toolchain_unusable(self, run) -> None:
        output = run.stdout + run.stderr
        if run.returncode != 0 and "sdl3 dependency is missing" in output.lower():
            reason = next(line for line in output.splitlines()
                          if "sdl3 dependency is missing" in line.lower())
            self.skipTest(reason.strip())

    # ---- the two halves ------------------------------------------------------

    def run_build_action(self, user_root: Path, *, env=None) -> subprocess.CompletedProcess:
        """Press BUILD PACKAGE: the player's own session, start to finish."""
        return subprocess.run(
            [str(self.harness), "--build-package", str(ROOT), str(user_root), DISC_ID,
             str(user_root / "logs")],
            cwd=ROOT, env=env, capture_output=True, text=True, timeout=1800,
        )

    def run_validator(self) -> subprocess.CompletedProcess:
        return subprocess.run(
            [str(self.validator), "--validate-package", str(self.user_root), DISC_ID,
             TITLE_ID, "1", "EBOOT.BIN"],
            cwd=ROOT, capture_output=True, text=True,
        )

    def run_launch(self, perf_csv: Path) -> subprocess.CompletedProcess:
        environment = os.environ.copy()
        environment["LOCALAPPDATA"] = str(self.local_appdata)
        # The opt-in child evidence channels. SR_PERF_CSV is how a launcher
        # proves the guest consumed vblanks without reading the child's stderr,
        # which is not a stable API of either process backend.
        environment["SR_PERF"] = "1"
        environment["SR_PERF_CSV"] = str(perf_csv)
        ucrt_bin = Path("C:/msys64/ucrt64/bin")
        if os.name == "nt" and ucrt_bin.is_dir():
            environment["PATH"] = str(ucrt_bin) + os.pathsep + environment.get("PATH", "")
        return subprocess.run(
            [str(self.player), "--empty", "--launch-index=0", "--headless-launch",
             f"--runtime-root={self.user_root}"],
            cwd=ROOT, env=environment, capture_output=True, text=True,
            timeout=LAUNCH_TIMEOUT_MS / 1000,  # subprocess.run takes seconds
        )

    def player_boot_event_files(self) -> set[Path]:
        cache = self.local_appdata / "Nakagawa" / "cache"
        return set(cache.glob("player-boot-*.events"))

    def test_release_package_layout_finds_public_cli(self):
        self.skip_if_toolchain_unavailable()
        package = self.root / "release-package"
        install_root = package / "bin"
        cli = package / "source" / "tools" / "nk_cli.py"
        cli.parent.mkdir(parents=True)
        install_root.mkdir()
        cli.write_text("# source-owned test fixture\n", encoding="utf-8")

        completed = subprocess.run(
            [str(self.harness), "--find-cli", str(install_root)],
            cwd=package, capture_output=True, text=True,
        )
        self.assertEqual(completed.returncode, 0, completed.stdout + completed.stderr)
        self.assertIn("PACKAGE_BUILDER_CLI status=PASS", completed.stdout)
        discovered = completed.stdout.partition("path=")[2].strip()
        self.assertEqual(Path(discovered).resolve(), cli.resolve())

    def test_source_owned_showcase_without_data_root_stages_without_data(self):
        self.skip_if_toolchain_unavailable()
        demo = next(item for item in SHOWCASE_DEMOS if item["disc_id"] == "TEST00007")
        executable = align_executable((self.fixture_dir / "guest.prx").read_bytes())
        iso_path = self.root / "showcase-without-xbdata.iso"
        write_iso(
            iso_path,
            "TEST00007",
            "Nakagawa 3D Showcase",
            make_icon_png(demo["palette"]),
            executable,
            b"Source-owned synthetic notice\n",
        )

        environment = os.environ.copy()
        environment["LOCALAPPDATA"] = str(self.local_appdata)
        environment["APPDATA"] = str(self.root / "appdata")
        environment["USERPROFILE"] = str(self.root / "userprofile")
        completed = subprocess.run(
            [str(self.player), f"--iso={iso_path}", "--stage-only"],
            cwd=ROOT, env=environment, capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(completed.returncode, 0,
                         completed.stdout + completed.stderr)
        self.assertIn("STAGING_RESULT status=PASS", completed.stdout)
        self.assertNotIn("STAGING_RESULT status=INCOMPLETE", completed.stdout)

    def test_uncatalogued_player_route_builds_with_generic_profile(self):
        """The package action upgrades the native profile through bring-up's writer."""
        self.skip_if_toolchain_unavailable()
        before = tracked_status()

        elf_bytes = self.executable_bytes
        iso_path = self.root / "uncatalogued-plain-elf.iso"
        create_test_iso_with_executables(
            iso_path, elf_bytes, disc_id=DISC_ID,
            title="Synthetic Experimental Disc",
        )
        user_root = self.root / "generic-user-data"
        # This is the profile shape emitted by the native player's current
        # experimental import path; it predates the shared Python writer's
        # generic ELF layout and codegen_profile declaration.
        self.stage_library(
            user_root, native_legacy_experimental_manifest(), iso_path, elf_bytes
        )
        profile_path = user_root / "experimental" / DISC_ID / "profile.json"
        profile = json.loads(profile_path.read_text(encoding="utf-8"))
        self.assertNotIn("codegen_profile", profile["manifest"])

        expected_root = self.root / "expected-generic-profile"
        expected_profile_path = nk_cli.write_experimental_profile(iso_path, expected_root)
        expected_profile = json.loads(expected_profile_path.read_text(encoding="utf-8"))

        build_environment = os.environ.copy()
        build_environment["SDL_VIDEODRIVER"] = "dummy"
        build_environment["SDL_AUDIODRIVER"] = "dummy"
        build_environment["NK_BUILD_ROOT"] = str(self.root / "b")
        built = self.run_build_action(user_root, env=build_environment)
        self.assertEqual(built.returncode, 0, built.stdout[-4000:] + built.stderr[-4000:])
        self.assertIn("PACKAGE_BUILD_ROUTE status=PASS", built.stdout)
        self.assertIn("complete=1", built.stdout)

        profile = json.loads(profile_path.read_text(encoding="utf-8"))
        self.assertEqual(profile, expected_profile)
        manifest = nk_cli.title_manifest.validate_manifest(profile["manifest"])
        self.assertEqual(manifest["id"], TITLE_ID)
        self.assertEqual(manifest["hle_profile"], "generic")
        self.assertEqual(manifest["codegen_profile"], "none")
        self.assertEqual(manifest["executable"], expected_profile["manifest"]["executable"])
        self.assertEqual(manifest["modules"], [])
        self.assertNotIn("runtime_bindings", manifest)

        identity = package_cache.read_local_title_input_identity(user_root, DISC_ID)
        self.assertIsNotNone(identity)
        self.assertEqual(identity["manifest"]["id"], TITLE_ID)
        package_dir = user_root / "packages" / DISC_ID
        self.assertTrue((package_dir / "package.json").is_file())
        self.assertTrue((package_dir / "build-report.json").is_file())
        validated = subprocess.run(
            [str(self.validator), "--validate-package", str(user_root), DISC_ID,
             TITLE_ID, "1", "EBOOT.BIN"],
            cwd=ROOT, env=build_environment, capture_output=True, text=True,
        )
        self.assertEqual(validated.returncode, 0, validated.stdout + validated.stderr)
        self.assertIn("PACKAGE_STATUS=OK", validated.stdout)
        self.assertEqual(tracked_status(), before)

    def test_unsupported_generic_layout_shows_sentence_and_keeps_detail(self):
        import argparse
        import contextlib
        import io

        elf_bytes = self.executable_bytes
        iso_path = self.root / "generic-profile-refusal.iso"
        create_test_iso_with_executables(
            iso_path, elf_bytes, disc_id=DISC_ID,
            title="Synthetic Experimental Disc",
        )
        user_root = self.root / "generic-profile-refusal-user-data"
        self.stage_library(
            user_root, native_legacy_experimental_manifest(), iso_path,
            elf_bytes,
        )
        progress_path = user_root / "logs" / "profile-refusal.jsonl"
        log_path = user_root / "logs" / "profile-refusal.log"
        args = argparse.Namespace(
            disc_id=DISC_ID,
            user_data_root=user_root,
            module_dir=None,
            psp_header=None,
            instruction_trace=False,
            register_local_compatibility_record=False,
            progress_json=progress_path,
            log_file=log_path,
        )
        expected_message = (
            "This executable needs a supported generic MIPS ELF layout; provide a "
            "decrypted ELF with a documented load binding, then retry the build."
        )
        stderr = io.StringIO()
        with patch.object(
            nk_cli, "write_experimental_profile",
            side_effect=nk_cli.IsoInspectionError("synthetic unsupported load layout"),
        ), contextlib.redirect_stderr(stderr):
            status = nk_cli.cmd_build_package(args)
        self.assertNotEqual(status, 0)
        events = [json.loads(line) for line in progress_path.read_text(encoding="utf-8").splitlines()]
        failure = next(event for event in events if event["status"] == "FAIL")
        self.assertEqual(failure["message"], expected_message)
        self.assertIn(
            "GENERIC_EXPERIMENTAL_PROFILE_UNAVAILABLE (#308, in the works)",
            failure["detail"],
        )
        self.assertIn("GENERIC_EXPERIMENTAL_PROFILE_UNAVAILABLE (#308, in the works)",
                      log_path.read_text(encoding="utf-8"))
        self.assertEqual(
            stderr.getvalue(), f"Package build refused: {expected_message}\n"
        )
        self.assertNotIn("GENERIC_EXPERIMENTAL_PROFILE_UNAVAILABLE", stderr.getvalue())
        self.assertNotIn("synthetic unsupported load layout", stderr.getvalue())

    def test_native_legacy_profile_matcher_rejects_added_optional_fields(self):
        default = nk_cli.title_manifest.validate_manifest(
            native_legacy_experimental_manifest()
        )
        self.assertTrue(
            nk_cli._is_native_legacy_experimental_manifest(
                default, DISC_ID, TITLE_ID,
                "Synthetic Experimental Disc", "NA",
            )
        )

        changes = (
            ("notes", lambda value: value.update(notes="Preserve this user-authored note.")),
            ("display_name", lambda value: value.update(display_name="User title")),
            ("disc.region", lambda value: value["disc"].update(region="EU")),
            ("disc.revision_policy", lambda value: value["disc"].update(
                revision_policy="compatible-revisions"
            )),
            ("disc.compatible_revisions", lambda value: value["disc"].update(
                compatible_revisions=[DISC_ID]
            )),
        )
        for field, change in changes:
            with self.subTest(field=field):
                customized = json.loads(json.dumps(default))
                change(customized)
                self.assertFalse(
                    nk_cli._is_native_legacy_experimental_manifest(
                        customized, DISC_ID, TITLE_ID,
                        "Synthetic Experimental Disc", "NA",
                    )
                )

    def test_legacy_profile_upgrade_refuses_changed_executable_before_rewrite(self):
        import argparse
        import contextlib
        import io

        iso_path = self.root / "legacy-profile-drift.iso"
        original_executable = self.executable_bytes
        create_test_iso_with_executables(
            iso_path, original_executable, disc_id=DISC_ID,
            title="Synthetic Experimental Disc",
        )
        user_root = self.root / "legacy-profile-drift-user-data"
        self.stage_library(
            user_root, native_legacy_experimental_manifest(), iso_path,
            original_executable,
        )
        profile_path = user_root / "experimental" / DISC_ID / "profile.json"
        original_profile = profile_path.read_bytes()

        changed_executable = bytearray(original_executable)
        changed_executable[-1] ^= 1
        create_test_iso_with_executables(
            iso_path, bytes(changed_executable), disc_id=DISC_ID,
            title="Synthetic Experimental Disc",
        )
        args = argparse.Namespace(
            disc_id=DISC_ID,
            user_data_root=user_root,
            module_dir=None,
            psp_header=None,
            instruction_trace=False,
            register_local_compatibility_record=False,
            progress_json=user_root / "logs" / "drift.jsonl",
            log_file=user_root / "logs" / "drift.log",
        )
        stderr = io.StringIO()
        with patch.object(
            nk_cli, "_current_package_cache_key",
            side_effect=AssertionError("build continued after an executable drift"),
        ), patch.object(
            nk_cli, "write_experimental_profile",
            wraps=nk_cli.write_experimental_profile,
        ) as profile_writer, contextlib.redirect_stderr(stderr):
            status = nk_cli.cmd_build_package(args)

        self.assertNotEqual(status, 0)
        self.assertIn("Selected executable SHA-256 differs", stderr.getvalue())
        profile_writer.assert_not_called()
        self.assertEqual(profile_path.read_bytes(), original_profile)

    def test_nondefault_legacy_profile_without_codegen_setting_refuses_with_detail(self):
        import argparse
        import contextlib
        import io

        iso_path = self.root / "legacy-profile-custom.iso"
        executable = self.executable_bytes
        create_test_iso_with_executables(
            iso_path, executable, disc_id=DISC_ID,
            title="Synthetic Experimental Disc",
        )
        manifest = native_legacy_experimental_manifest()
        manifest["notes"] = "Preserve this user-authored profile note."
        user_root = self.root / "legacy-profile-custom-user-data"
        self.stage_library(user_root, manifest, iso_path, executable)
        profile_path = user_root / "experimental" / DISC_ID / "profile.json"
        original_profile = profile_path.read_bytes()
        progress_path = user_root / "logs" / "missing-codegen.jsonl"
        log_path = user_root / "logs" / "missing-codegen.log"
        args = argparse.Namespace(
            disc_id=DISC_ID,
            user_data_root=user_root,
            module_dir=None,
            psp_header=None,
            instruction_trace=False,
            register_local_compatibility_record=False,
            progress_json=progress_path,
            log_file=log_path,
        )
        expected_message = (
            "This experimental profile is missing its generic build setting; "
            "re-import the disc to rebuild the profile, then retry."
        )
        stderr = io.StringIO()
        with patch.object(
            nk_cli, "_current_package_cache_key",
            side_effect=AssertionError("custom profile was incorrectly upgraded"),
        ), patch.object(
            nk_cli, "write_experimental_profile",
            wraps=nk_cli.write_experimental_profile,
        ) as profile_writer, contextlib.redirect_stderr(stderr):
            status = nk_cli.cmd_build_package(args)

        self.assertNotEqual(status, 0)
        events = [
            json.loads(line) for line in progress_path.read_text(encoding="utf-8").splitlines()
        ]
        failure = next(event for event in events if event["status"] == "FAIL")
        self.assertEqual(failure["message"], expected_message)
        self.assertEqual(
            failure["detail"],
            "EXPERIMENTAL_CODEGEN_PROFILE_MISSING (#730, in the works): "
            "codegen_profile is absent from a non-default experimental profile",
        )
        self.assertIn(failure["detail"], log_path.read_text(encoding="utf-8"))
        self.assertEqual(stderr.getvalue(), f"Package build refused: {expected_message}\n")
        profile_writer.assert_not_called()
        self.assertEqual(profile_path.read_bytes(), original_profile)

    def test_catalogued_display_smoke_plan_matches_main_bytes(self):
        """Keep the catalogued package plan byte-identical to the current-main baseline."""
        import title_codegen_plan
        import title_manifest

        manifest = title_manifest.validate_manifest(
            title_manifest.load_manifest(ROOT / "assets" / "titles" / "display-smoke.json")
        )
        plan = title_codegen_plan.build_plan(
            manifest,
            game_name="display-smoke-v1",
            game_elf=Path("fixtures/display_smoke/guest.elf"),
            build_dir=Path("build/display-smoke-v1"),
        )
        plan_bytes = title_codegen_plan.canonical_json(plan).encode("utf-8")
        self.assertEqual(
            hashlib.sha256(plan_bytes).hexdigest(),
            "d91456c94956e805509f5e3118bf77fa96d14641c37ce50abce81f8a2f16f46b",
        )

    def test_build_validates_and_launches_through_the_player(self):
        self.skip_if_toolchain_unavailable()
        before = tracked_status()

        # 1. BUILD PACKAGE, through the player's own session, with real
        #    analysis, codegen and compilation.
        built = self.run_build_action(self.user_root)
        self.assertEqual(built.returncode, 0, built.stdout[-4000:] + built.stderr[-4000:])
        self.assertIn("PACKAGE_BUILD_ROUTE status=PASS", built.stdout)
        self.assertIn("complete=1", built.stdout)
        # The child really analysed, generated and compiled: its own log names
        # the codegen entry point and the compiler that linked the runtime.
        log_path = self.user_root / "logs" / f"build_{DISC_ID}.log"
        build_log = log_path.read_text(encoding="utf-8", errors="replace")
        self.assertIn("title_codegen_plan.py", build_log)
        self.assertIn("gcc", build_log)
        self.assertIn("Build finished:", build_log)
        package_dir = self.user_root / "packages" / DISC_ID
        self.assertTrue((package_dir / "package.json").is_file())
        self.assertTrue((package_dir / "build-report.json").is_file())
        self.assertTrue((package_dir / "display_smoke.exe").is_file())

        # 2. The player's own validator accepts what the action produced.
        validated = self.run_validator()
        self.assertEqual(validated.returncode, 0, validated.stdout + validated.stderr)
        self.assertIn("PACKAGE_STATUS=OK", validated.stdout)

        # An equal DISC_ID cannot make a second executable compatible with
        # this package. Model a second, source-owned fixture identity, then
        # prove the native player refuses it before writing guest boot events.
        self.write_player_library()
        original_identity = package_cache.read_local_title_input_identity(
            self.user_root, DISC_ID
        )
        self.assertIsNotNone(original_identity)
        second_executable = bytearray(self.executable_bytes)
        second_executable[-1] ^= 1
        second_input_path = self.root / "second-source-owned-input.elf"
        second_input_path.write_bytes(second_executable)
        second_identity = dict(original_identity)
        second_identity["main_executable"] = dict(
            original_identity["main_executable"],
            sha256=package_cache.sha256_file(second_input_path),
        )
        package_cache.write_local_title_input_identity(self.user_root, second_identity)

        same_disc_stale = self.run_validator()
        self.assertEqual(same_disc_stale.returncode, 0,
                         same_disc_stale.stdout + same_disc_stale.stderr)
        self.assertIn("PACKAGE_STATUS=STALE", same_disc_stale.stdout)
        self.assertIn("main executable changed", same_disc_stale.stdout)
        self.assertIn("rebuild the package from the current inputs", same_disc_stale.stdout)
        self.assertNotIn("#315", same_disc_stale.stdout)
        second_boot_events = self.player_boot_event_files()
        second_launch = self.run_launch(self.sandbox / "second-input-perf.csv")
        self.assertNotEqual(second_launch.returncode, 0)
        self.assertEqual(self.player_boot_event_files(), second_boot_events,
                         "a same-DISC_ID executable mismatch must stop before guest execution")
        package_cache.write_local_title_input_identity(self.user_root, original_identity)

        # The library and local identity still describe the original input.
        # Replacing the selected executable in the source ISO without changing
        # DISC_ID or DISC_VERSION must still stop the package before guest boot.
        changed_iso_executable = bytearray(self.executable_bytes)
        changed_iso_executable[-1] ^= 1
        create_test_iso_with_modules(
            self.iso_path,
            bytes(changed_iso_executable),
            sysdir_modules={},
            usrdir_modules={"fixture.prx": self.module_bytes},
            disc_id=DISC_ID,
        )
        boot_events_before_changed_iso = self.player_boot_event_files()
        changed_iso_launch = self.run_launch(self.sandbox / "changed-iso-perf.csv")
        self.assertNotEqual(changed_iso_launch.returncode, 0,
                            changed_iso_launch.stdout + changed_iso_launch.stderr)
        self.assertEqual(
            self.player_boot_event_files(), boot_events_before_changed_iso,
            "a same-ID, same-version source ISO with changed executable bytes must stop before guest execution",
        )
        create_test_iso_with_modules(
            self.iso_path,
            self.executable_bytes,
            sysdir_modules={},
            usrdir_modules={"fixture.prx": self.module_bytes},
            disc_id=DISC_ID,
        )

        changed_iso_module = bytearray(self.module_bytes)
        changed_iso_module[-1] ^= 1
        create_test_iso_with_modules(
            self.iso_path,
            self.executable_bytes,
            sysdir_modules={},
            usrdir_modules={"fixture.prx": bytes(changed_iso_module)},
            disc_id=DISC_ID,
        )
        boot_events_before_changed_module = self.player_boot_event_files()
        changed_iso_module_launch = self.run_launch(
            self.sandbox / "changed-iso-module-perf.csv"
        )
        self.assertNotEqual(changed_iso_module_launch.returncode, 0,
                            changed_iso_module_launch.stdout + changed_iso_module_launch.stderr)
        self.assertEqual(
            self.player_boot_event_files(), boot_events_before_changed_module,
            "a same-ID, same-version source ISO with changed required module bytes must stop before guest execution",
        )
        create_test_iso_with_modules(
            self.iso_path,
            self.executable_bytes,
            sysdir_modules={},
            usrdir_modules={"fixture.prx": self.module_bytes},
            disc_id=DISC_ID,
        )
        restored_validator = self.run_validator()
        self.assertEqual(restored_validator.returncode, 0,
                         restored_validator.stdout + restored_validator.stderr)
        self.assertIn("PACKAGE_STATUS=OK", restored_validator.stdout)

        # 3. PLAY, headless, through the player's own launch session. The player
        #    reads its library from its own per-user data directory, so the
        #    entry the build half consumed is the entry the launch half sees.
        perf_csv = self.sandbox / "perf.csv"
        launched = self.run_launch(perf_csv)
        self.assertEqual(launched.returncode, 0,
                         launched.stdout[-4000:] + launched.stderr[-4000:])
        self.assertIn("[PLAYER] Launch index 0: PLAY NOW available", launched.stdout)
        self.assertIn("[PLAYER] Launch argv contains --gui: no", launched.stdout)
        self.assertIn("[PLAYER] Headless launch child exited with code 0", launched.stdout)

        # 4. Guest-visible startup state, from the player-owned child event file.
        boot_logs = self.player_boot_event_files()
        self.assertEqual(len(boot_logs), 1,
                         "the player did not retain the child's boot evidence")
        events = next(iter(boot_logs)).read_text(encoding="utf-8", errors="replace")
        for milestone in (
            "BOOT_EVENT phase=init public_safe=1",
            "BOOT_EVENT phase=image_loaded",
            "BOOT_EVENT phase=runtime_registered",
            "BOOT_EVENT phase=index_prepare_end",
            "BOOT_EVENT phase=guest_start mode=scheduler",
        ):
            self.assertIn(milestone, events)
        for forbidden in ("UNKNOWN NID", "NONPLT_MISS", "INTERP_REJECT", "DRIVER_EXPECT_U32"):
            self.assertNotIn(forbidden, events)

        # 5. The fixture's frame checkpoint: the guest consumed the vblanks its
        #    frame loop waits for, so a launch that never delivered a vblank
        #    cannot pass this.
        self.assertTrue(perf_csv.is_file(), "the child runtime wrote no perf CSV")
        rows = perf_csv.read_text(encoding="utf-8", errors="replace").splitlines()
        self.assertGreaterEqual(len(rows), 2, "the perf CSV has header and summary rows only")
        header = rows[0].split(",")
        self.assertEqual(header[0], "vblank_total")
        vblank_total = int(rows[-1].split(",")[0])
        self.assertGreaterEqual(vblank_total, FRAMES)

        # 6. Nothing this route did reached a repository-tracked file.
        self.assertEqual(tracked_status(), before)

        # 7. Negative control. A tampered package must fail closed at the
        #    validator and the launch, which is what makes steps 2 to 5
        #    load-bearing rather than decorative.
        executable = package_dir / "display_smoke.exe"
        executable.write_bytes(executable.read_bytes() + b"tampered")
        stale = self.run_validator()
        self.assertEqual(stale.returncode, 0, stale.stdout + stale.stderr)
        self.assertIn("PACKAGE_STATUS=STALE", stale.stdout)
        boot_logs_before_refusal = self.player_boot_event_files()
        refused = self.run_launch(self.sandbox / "refused-perf.csv")
        self.assertNotEqual(refused.returncode, 0)
        self.assertIn("PLAY NOW is unavailable", refused.stdout + refused.stderr)
        self.assertEqual(self.player_boot_event_files(), boot_logs_before_refusal,
                         "a stale package must not create guest boot evidence")
        self.assertEqual(tracked_status(), before)

    def test_missing_prerequisites_fail_closed_with_documented_codes(self):
        self.skip_if_toolchain_unavailable()
        before = tracked_status()

        # (a) A missing input: the disc's executable is still the encrypted
        #     PSP container, so the route must name the decrypted-module
        #     boundary instead of producing a package.
        encrypted_root = self.root / "encrypted-input"
        encrypted_root.mkdir()
        encrypted_iso = encrypted_root / "disc.iso"
        create_test_iso_with_executables(
            encrypted_iso, build_psp_container(), disc_id=DISC_ID
        )
        self.stage_library(encrypted_root, self.manifest, encrypted_iso,
                           build_psp_container())
        encrypted = self.run_build_action(encrypted_root)
        self.assertNotEqual(encrypted.returncode, 0)
        self.assertIn("PACKAGE_BUILD_ROUTE status=FAIL", encrypted.stdout)
        self.assertIn("[preflight] FAIL: Encrypted executable", encrypted.stdout)
        self.assertIn("supply decrypted modules at", encrypted.stdout)
        self.assertIn("local key file", encrypted.stdout)
        self.assertNotIn("decryption support is in the works (#295)", encrypted.stdout.lower())
        self.assertNotIn("automatic decryption is in the works", encrypted.stdout.lower())
        self.assertFalse((encrypted_root / "packages" / DISC_ID).exists())

        # (b) A missing prerequisite the manifest itself names: it reads BSS
        #     metadata from the disc's ~PSP header, and this disc's executable
        #     has none. The build must say which input is missing, not fall
        #     back to a guess.
        header_manifest = dict(self.manifest)
        header_manifest["executable"] = dict(
            self.manifest["executable"], bss_metadata_source="psp-header"
        )
        header_root = self.root / "missing-psp-header"
        header_root.mkdir()
        header_iso = header_root / "disc.iso"
        header_elf = align_executable((self.fixture_dir / "guest.prx").read_bytes())
        create_test_iso_with_executables(header_iso, header_elf, disc_id=DISC_ID)
        self.stage_library(header_root, header_manifest, header_iso, header_elf)
        header = self.run_build_action(header_root)
        self.assertNotEqual(header.returncode, 0)
        self.assertIn("PACKAGE_BUILD_ROUTE status=FAIL", header.stdout)
        self.assertIn("[extract] FAIL: This manifest reads BSS metadata", header.stdout)
        self.assertIn("provide --psp-header (#296)", header.stdout)
        self.assertFalse((header_root / "packages" / DISC_ID).exists())

        self.assertEqual(tracked_status(), before)


class TestRuntimeDllStaging(unittest.TestCase):
    """Runtime staging ships SDL3_ttf, its resolved closure, and licences (#421).

    Synthetic DLL files plus a fake import resolver are enough: the contract under
    test is the mechanical closure walk, the copy, and the licence staging, not
    the toolchain's PE bytes.
    """

    GRAPH = {
        "sdl3.dll": ["KERNEL32.dll"],
        "sdl3_ttf.dll": ["SDL3.dll", "libfreetype-6.dll", "KERNEL32.dll"],
        "libfreetype-6.dll": ["libpng16-16.dll", "zlib1.dll"],
        "libpng16-16.dll": ["zlib1.dll"],
        "zlib1.dll": ["KERNEL32.dll"],
    }

    def fake_resolver(self):
        def imports_of(path: Path) -> list[str]:
            return list(self.GRAPH.get(path.name.lower(), []))

        def is_system(name: str) -> bool:
            return name.lower() == "kernel32.dll"

        return imports_of, is_system

    def write_fake_dlls(self, bin_dir: Path) -> None:
        bin_dir.mkdir(parents=True)
        # Real file names: roots are looked up by their canonical case, and a
        # case-sensitive host (the Linux CI runner) must find them too.
        for name in ("SDL3.dll", "SDL3_ttf.dll", "libfreetype-6.dll", "libpng16-16.dll", "zlib1.dll"):
            (bin_dir / name).write_bytes(b"MZ\0\0synthetic-" + name.encode())

    def test_staging_copies_ttf_closure_and_licence_files(self) -> None:
        import stage_runtime_dlls

        with tempfile.TemporaryDirectory() as tmp:
            package_dir = Path(tmp) / "package"
            package_dir.mkdir()
            bin_dir = Path(tmp) / "toolchain-bin"
            self.write_fake_dlls(bin_dir)
            imports_of, is_system = self.fake_resolver()

            staged = stage_runtime_dlls.stage_runtime_dlls(
                package_dir,
                roots=["SDL3.dll", "SDL3_ttf.dll"],
                search_dirs=[bin_dir],
                env={},
                imports_of=imports_of,
                is_system=is_system,
            )

            staged_names = {name.lower() for name in staged}
            self.assertEqual(
                staged_names,
                {"sdl3.dll", "sdl3_ttf.dll", "libfreetype-6.dll", "libpng16-16.dll", "zlib1.dll"},
            )
            for name in staged:
                self.assertTrue((package_dir / name).is_file(), name)
            self.assertFalse((package_dir / "KERNEL32.dll").exists())

            notices = package_dir / "THIRD_PARTY_NOTICES"
            self.assertTrue(notices.is_dir())
            notice_text = "\n".join(
                p.name for p in notices.iterdir() if p.is_file()
            )
            for licence in ("SDL3_ttf", "FreeType", "libpng", "zlib"):
                self.assertIn(licence, notice_text)

    def test_missing_sdl3_ttf_fails_the_stage_closed(self) -> None:
        import stage_runtime_dlls

        with tempfile.TemporaryDirectory() as tmp:
            package_dir = Path(tmp) / "package"
            package_dir.mkdir()
            empty_bin = Path(tmp) / "toolchain-bin"
            empty_bin.mkdir()
            imports_of, is_system = self.fake_resolver()
            with self.assertRaises(stage_runtime_dlls.StageError) as ctx:
                stage_runtime_dlls.stage_runtime_dlls(
                    package_dir,
                    roots=["SDL3_ttf.dll"],
                    search_dirs=[empty_bin],
                    env={},
                    imports_of=imports_of,
                    is_system=is_system,
                )
            self.assertIn("SDL3_ttf.dll", str(ctx.exception))
            self.assertEqual(list(package_dir.iterdir()), [])

    def test_unresolved_closure_member_fails_closed(self) -> None:
        import stage_runtime_dlls

        with tempfile.TemporaryDirectory() as tmp:
            package_dir = Path(tmp) / "package"
            package_dir.mkdir()
            bin_dir = Path(tmp) / "toolchain-bin"
            self.write_fake_dlls(bin_dir)
            imports_of, is_system = self.fake_resolver()
            broken = dict(self.GRAPH)
            broken["libfreetype-6.dll"] = ["libghost.dll"]

            def broken_imports(path: Path) -> list[str]:
                return list(broken.get(path.name.lower(), []))

            with self.assertRaises(stage_runtime_dlls.StageError) as ctx:
                stage_runtime_dlls.stage_runtime_dlls(
                    package_dir,
                    roots=["SDL3_ttf.dll"],
                    search_dirs=[bin_dir],
                    env={},
                    imports_of=broken_imports,
                    is_system=is_system,
                )
            self.assertIn("libghost.dll", str(ctx.exception))

    @unittest.skipUnless(os.name == "nt", "the Windows staging route copies DLLs")
    def test_package_route_staging_step_covers_sdl3_ttf(self) -> None:
        """The build-package route delegates its DLL staging to the shared step."""
        from unittest import mock

        import nk_cli

        with tempfile.TemporaryDirectory() as tmp:
            provider = Path(tmp) / "ucrt64"
            (provider / "bin").mkdir(parents=True)
            for name in ("SDL3.dll", "libiconv-2.dll", "vulkan-1.dll"):
                (provider / "bin" / name).write_bytes(b"source-owned synthetic test payload")
            package_dir = Path(tmp) / "package"
            package_dir.mkdir()
            with patch.dict(os.environ, {
                "SDL3_DIR": str(provider), "SDL3_DLL": "", "VULKAN_SDK": str(provider),
            }), mock.patch.object(
                nk_cli._runtime_dlls, "stage_runtime_dlls"
            ) as stage:
                nk_cli._stage_runtime_assets(package_dir)
            stage.assert_called_once()
            self.assertEqual(stage.call_args.args[0], package_dir)
            self.assertEqual(stage.call_args.kwargs["roots"], ("SDL3_ttf.dll",))

    def test_package_without_the_font_closure_builds_and_names_the_fallback(self) -> None:
        """A toolchain without the SDL3_ttf closure still builds the package with its
        required runtimes: the missing font closure stays a warning, never fatal."""
        import contextlib
        import io
        from unittest import mock

        import nk_cli

        with tempfile.TemporaryDirectory(prefix="nk-ttf-package-") as temporary:
            root = Path(temporary)
            provider = root / "ucrt64"
            (provider / "bin").mkdir(parents=True)
            for name in ("SDL3.dll", "libiconv-2.dll", "vulkan-1.dll"):
                (provider / "bin" / name).write_bytes(b"source-owned synthetic test payload")
            package = root / "package"
            package.mkdir()
            stderr = io.StringIO()
            with patch.dict(os.environ, {
                "SDL3_DIR": str(provider), "SDL3_DLL": "", "VULKAN_SDK": str(provider),
            }), patch("nk_cli._windows_host", return_value=True), mock.patch.object(
                nk_cli._runtime_dlls, "stage_runtime_dlls",
                side_effect=nk_cli._runtime_dlls.StageError("SDL3_ttf.dll could not be resolved"),
            ), contextlib.redirect_stderr(stderr):
                nk_cli._stage_runtime_assets(package)
            self.assertTrue((package / "SDL3.dll").is_file())
            self.assertTrue((package / "vulkan-1.dll").is_file())
            self.assertIn("SDL3_ttf.dll could not be resolved", stderr.getvalue())
            self.assertIn("bitmap fallback", stderr.getvalue())


if __name__ == "__main__":
    unittest.main()
