# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025-2026 the psp-recomp authors

import json
from pathlib import Path
import subprocess
import tempfile
import unittest

from tools import publication_policy, public_export
from tools.build_public_export import (
    check_unresolved_legal_blockers,
    export_sanitized_public_tree,
    is_public_safe_export_tree,
    run_all_publication_gates,
    run_history_audit,
    run_publish_audit,
    run_sbom_verification,
)

# The same tests run in the source checkout and in a materialized public-safe
# candidate. Profile-excluded files are asserted by path/policy using synthetic
# conditions; publication-security coverage must not disappear behind skips.
_PUBLIC_SAFE_TREE = is_public_safe_export_tree()
_FRESH_CANDIDATE = subprocess.run(
    ["git", "rev-list", "--count", "--all"],
    capture_output=True,
    text=True,
    check=False,
).stdout.strip() == "1"


class TestPublicExport(unittest.TestCase):
    def test_in_place_metadata_is_idempotent_across_its_own_previous_bytes(self):
        policy = publication_policy.load_policy(Path("assets/public_source_profile.json"))
        common = [("README.md", b"source bytes\n")]
        first = public_export.build_document(
            policy,
            common + [(public_export.EXPORT_PATH, b"old generated bytes\n")],
            provenance_ledger=b"ledger bytes\n",
            manifest=b"manifest bytes\n",
        )
        first_bytes = json.dumps(first, indent=2, ensure_ascii=False).encode("utf-8") + b"\n"
        second = public_export.build_document(
            policy,
            common + [(public_export.EXPORT_PATH, first_bytes)],
            provenance_ledger=b"ledger bytes\n",
            manifest=b"manifest bytes\n",
        )
        self.assertEqual(first, second)
        self.assertNotIn("source_tree", first)

    def test_legal_blockers_fail_closed_without_profile(self):
        res = check_unresolved_legal_blockers(public_safe_profile=False)
        self.assertFalse(res.passed)
        self.assertIn("OPEN PUBLICATION BLOCKERS", res.detail)

    def test_legal_blockers_pass_with_public_safe_profile(self):
        res = check_unresolved_legal_blockers(public_safe_profile=True)
        self.assertTrue(res.passed)
        self.assertIn("PUBLIC-SAFE PROFILE ACTIVE", res.detail)

    def test_publish_audit_gate(self):
        res = run_publish_audit()
        self.assertTrue(res.passed, f"publish_audit gate failed: {res.detail}")

    def test_history_audit_gate_fails_closed_on_legacy_history(self):
        res = run_history_audit()
        if _PUBLIC_SAFE_TREE and _FRESH_CANDIDATE:
            self.assertTrue(res.passed, f"fresh public candidate history must be clean: {res.detail}")
        else:
            self.assertFalse(res.passed, "an inherited multi-commit history must fail closed")
            self.assertIn("SENSITIVE FINDINGS DETECTED", res.detail)

    def test_sbom_verification_gate(self):
        res = run_sbom_verification()
        self.assertTrue(res.passed, f"sbom_verification gate failed: {res.detail}")

    def test_run_all_publication_gates(self):
        results = run_all_publication_gates(public_safe_profile=True)
        self.assertEqual(len(results), 4)
        if _FRESH_CANDIDATE:
            for gate in results:
                self.assertTrue(gate.passed, f"Gate '{gate.name}' failed: {gate.detail}")
        else:
            self.assertFalse(results[2].passed, "inherited source history must remain visibly failed")
            self.assertFalse(results[2].blocking, "old history is non-blocking only because it is not exported")
            self.assertIn("not exported", results[2].name)

    def test_dry_run_export(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "export_repo"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True, dry_run=True)
            self.assertTrue(success)

    def test_public_safe_export_excludes_unreviewed_components(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "public_export"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True)
            self.assertTrue(success, "public-safe export should succeed at the tree level")
            # Core toolkit and required publication files are present.
            self.assertTrue((target_path / "src" / "rt" / "recomp.c").is_file())
            self.assertTrue((target_path / "LICENSE").is_file())
            self.assertTrue((target_path / "NOTICE.md").is_file())
            # Unresolved PGF/font and PGD/amctrl surfaces are excluded from the tree.
            for rel in (
                "font/jpn0.pgf",
                "font/kr0.pgf",
                "font/ltn0.pgf",
                "font/ltn8.pgf",
                "src/rt/pgf.c",
                "src/rt/pgf.h",
                "src/rt/pgd.c",
                "src/rt/pgd.h",
                "tools/pgd_decrypt.py",
                "tools/pgd_e2e_harness.c",
                "tools/test_pgd_c.py",
                "tools/test_pgd_decrypt.py",
            ):
                self.assertFalse((target_path / rel).exists(), f"{rel} must be excluded")
            # Provenance metadata records the profile, source commit, and exclusions.
            metadata_path = target_path / "PUBLIC_EXPORT.json"
            self.assertTrue(metadata_path.is_file())
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
            self.assertEqual(metadata["profile"], "public-safe-v1")
            self.assertEqual(
                metadata["excluded_file_count"],
                len(metadata.get("excluded_present_paths", [])),
            )
            self.assertGreater(len(metadata["excluded_paths"]), 0)
            self.assertIn("font/*.pgf", metadata["excluded_globs"])
            self.assertIn("src/rt/pgd.c", metadata["excluded_paths"])
            self.assertTrue(metadata.get("source_tree"))

    def test_public_safe_export_audits_in_public_scope_in_its_own_pre_commit(self):
        # The exported tree lacks the manifest-declared excluded components by
        # design; the export's own publication-safety pre-commit hook must run
        # in public scope so contributor commits do not fail on their absence.
        with tempfile.TemporaryDirectory() as tmpdir:
            target_path = Path(tmpdir) / "public_export"
            success = export_sanitized_public_tree(target_path, public_safe_profile=True)
            self.assertTrue(success, "public-safe export should succeed at the tree level")
            pre_commit_text = (target_path / ".pre-commit-config.yaml").read_text(encoding="utf-8")
            self.assertIn(
                "entry: python tools/publish_audit.py --tracked-only --public-scope",
                pre_commit_text,
            )
            self.assertNotIn(
                "entry: python tools/publish_audit.py --tracked-only\n",
                pre_commit_text.replace("--public-scope", ""),
            )

    def test_profile_excludes_unreviewed_components_without_materializing_them(self):
        from tools import public_candidate

        profile = public_candidate.load_profile(Path("assets/public_source_profile.json"))
        for rel in (
            "font/jpn0.pgf",
            "src/rt/pgf.c",
            "src/rt/pgd.c",
            "tools/pgd_decrypt.py",
        ):
            self.assertTrue(public_candidate.is_excluded(rel, profile), rel)


if __name__ == "__main__":
    unittest.main()
