# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025-2026 the psp-recomp authors

"""Regression tests for the path-gated CI classifier."""

from __future__ import annotations

import os
from pathlib import Path
import unittest
from unittest.mock import patch

try:
    import ci_paths as ci_paths_module
except ModuleNotFoundError:  # Running as ``python -m unittest tools.test_ci_paths``.
    import tools.ci_paths as ci_paths_module

classify = ci_paths_module.classify


class CiPathClassificationTests(unittest.TestCase):
    def test_tools_data_artefacts_do_not_force_the_full_matrix(self) -> None:
        """tools/import_audit_baseline.json is regenerated by every change to the
        HLE registrations. While it was unclassified it counted as an unknown
        path, which sets force_full and pulled in the dashboard gate on PRs that
        do not touch interface/ at all -- turning them red for reasons unrelated
        to their content."""
        result = classify(["src/rt/hle.c", "tools/import_audit_baseline.json"])
        self.assertEqual(result["run_dashboard"], "false")
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")

    def test_oracle_manifest_is_python_tooling_data(self) -> None:
        result = classify(["tools/psp_oracle/manifest.json"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_dashboard"], "false")

    def test_interface_paths_still_reach_the_dashboard_gate(self) -> None:
        """The narrowing above must not stop a real dashboard change from
        running the dashboard gate."""
        for path in ("interface/package.json", "interface/app/page.tsx"):
            with self.subTest(path=path):
                self.assertEqual(classify([path])["run_dashboard"], "true")

    def test_docs_only_keeps_expensive_jobs_off(self) -> None:
        result = classify(["docs/CI.md", "README.md"])
        self.assertEqual(result["docs_only"], "true")
        self.assertEqual(result["run_markdown"], "true")
        self.assertEqual(result["run_python"], "false")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_dashboard"], "false")
        self.assertEqual(result["run_windows"], "false")

    def test_dashboard_changes_only_run_dashboard(self) -> None:
        result = classify(["interface/src/app/page.tsx"])
        self.assertEqual(result["run_dashboard"], "true")
        self.assertEqual(result["run_python"], "false")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_windows"], "false")

    def test_native_changes_run_python_native_and_windows(self) -> None:
        result = classify(["src/rt/sched.c"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")
        self.assertEqual(result["run_dashboard"], "false")

    def test_python_only_does_not_force_native(self) -> None:
        result = classify(["tools/test_progress_tracker.py"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_windows"], "false")

    def test_codegen_tool_is_native_relevant(self) -> None:
        result = classify(["tools/codegen.py"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")

    def test_draft_pr_suppresses_substantive_jobs(self) -> None:
        result = classify(["src/rt/recomp.c"], draft=True)
        self.assertEqual(result["allow_substantive"], "false")
        self.assertEqual(result["run_native"], "true")

    def test_ordinary_main_push_keeps_only_smoke_jobs(self) -> None:
        with patch.dict(os.environ, {"GITHUB_REF": "refs/heads/main"}):
            result = classify(["src/rt/recomp.c"], event_name="push")
        self.assertEqual(result["run_main_smoke"], "true")
        self.assertEqual(result["allow_substantive"], "false")

    def test_workflow_changes_are_full_validation(self) -> None:
        result = classify([".github/workflows/ci.yml"])
        self.assertEqual(result["workflow_ci"], "true")
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_dashboard"], "true")

    def test_empty_or_manual_classification_is_conservative(self) -> None:
        result = classify([], event_name="workflow_dispatch")
        for key in (
            "run_python",
            "run_native",
            "run_windows",
            "run_dashboard",
            "run_markdown",
            "run_main_smoke",
            "allow_substantive",
        ):
            self.assertEqual(result[key], "true")

    def test_history_failure_is_conservative(self) -> None:
        result = classify(["<history-unavailable>"])
        for key in ("run_python", "run_native", "run_windows", "run_dashboard", "allow_substantive"):
            self.assertEqual(result[key], "true")

    def test_unknown_paths_fail_closed_to_full_validation(self) -> None:
        result = classify(["new-tool-input.dat"])
        for key in ("run_python", "run_native", "run_windows", "run_dashboard", "allow_substantive"):
            self.assertEqual(result[key], "true")


class CiPathAdversarialTests(unittest.TestCase):
    """Independent false-negative hunt, written against the classifier rather than with it.

    The failure mode that matters is a build-affecting change classified as
    docs/tooling and therefore skipping a native or Windows gate.  Every case
    here asserts the *expensive* direction.
    """

    NATIVE_RELEVANT = (
        "src/rt/hle.c",
        "src/rt/recomp.h",
        "src/ref/interp.cpp",
        "include/whatever.h",
        "Makefile",
        "GNUmakefile",
        "mk/toolchain.mk",
        "cmake/toolchain.cmake",
        "assets/vfpu/tables.bin",
        "assets/shaders/blit.frag",
        "hst_manager.ps1",
        "hst.ps1",
        "tools/title_codegen_plan.py",
        "tools/title_manifest.py",
        "tools/test_title_manifest.py",
        "assets/title_manifest.schema.json",
        "assets/titles/synthetic.json",
        "tools/codegen.py",
        "tools/prxload.py",
        "tools/imports.py",
        "tools/gen_microtest.py",
        "tools/verify_gates.py",
        "tools/hst_doctor.py",
        "tools/pspdev_lock.py",
    )

    def test_every_native_relevant_path_runs_native_and_windows(self) -> None:
        for path in self.NATIVE_RELEVANT:
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true", f"{path} must run native gates")
                self.assertEqual(result["run_windows"], "true", f"{path} must run the Windows gate")
                self.assertEqual(result["docs_only"], "false", f"{path} is not documentation")

    def test_deleted_native_source_still_runs_native_gates(self) -> None:
        """A deletion is a build-affecting change.

        Regression for the ``--diff-filter=ACMR`` defect: that filter dropped
        deletions, so removing a C source while touching a document classified
        as docs-only and skipped the native and Windows compile gates.
        """
        result = classify(["docs/GUIDE.md", "src/rt/audio.c"])
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")
        self.assertEqual(result["docs_only"], "false")

    def test_git_extraction_does_not_filter_out_deletions(self) -> None:
        """Guard the call itself, not just the pure classifier.

        ``--diff-filter=ACMR`` silently omits deleted paths.  Assert the source
        does not reintroduce a filter that can drop a change type.
        """
        source = (Path(__file__).resolve().parent / "ci_paths.py").read_text(encoding="utf-8")
        self.assertNotIn("--diff-filter=ACMR", source)
        for line in source.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            if "--diff-filter" in stripped:
                self.fail(f"unexpected diff-filter narrows the changed-file set: {stripped}")

    def test_renamed_native_source_runs_native_gates(self) -> None:
        result = classify(["src/rt/renamed.c"])
        self.assertEqual(result["run_native"], "true")

    def test_mixed_native_and_dashboard_runs_both(self) -> None:
        result = classify(["src/rt/hle.c", "interface/src/app/page.tsx"])
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")
        self.assertEqual(result["run_dashboard"], "true")

    def test_mixed_docs_and_native_is_not_docs_only(self) -> None:
        result = classify(["docs/CI.md", "Makefile"])
        self.assertEqual(result["docs_only"], "false")
        self.assertEqual(result["run_native"], "true")

    def test_dashboard_only_never_triggers_native(self) -> None:
        """The saving direction: assert it is real, so the gate is worth having."""
        result = classify(["interface/package.json", "interface/src/lib/x.ts"])
        self.assertEqual(result["run_dashboard"], "true")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_windows"], "false")

    def test_repository_metadata_fails_closed(self) -> None:
        for path in (".gitignore", ".gitattributes", "assets/release_manifest.json"):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true", f"{path} is unrecognised and must fail closed")

    def test_dependency_and_hook_metadata_is_recognised(self) -> None:
        """These are covered by the always-on hygiene job, so they need not be full runs.

        Asserted explicitly so a future change that makes them *skip* hygiene is
        caught rather than assumed.
        """
        for path in (".github/dependabot.yml", ".pre-commit-config.yaml"):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["docs_only"], "false")

    def test_workflow_and_classifier_changes_force_full_validation(self) -> None:
        for path in (".github/workflows/ci.yml", "tools/ci_paths.py", "tools/test_ci_paths.py"):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["workflow_ci"], "true")
                self.assertEqual(result["run_native"], "true")
                self.assertEqual(result["run_dashboard"], "true")

    def test_ready_for_review_runs_substantive_gates(self) -> None:
        result = classify(["src/rt/hle.c"], event_name="pull_request", draft=False)
        self.assertEqual(result["allow_substantive"], "true")
        self.assertEqual(result["run_native"], "true")

    def test_draft_keeps_gates_applicable_but_suppressed(self) -> None:
        """Draft suppression must not rewrite the classification itself.

        ``allow_substantive`` is the only thing that may go false; the path
        facts stay true so the ready transition needs no reclassification.
        """
        result = classify(["src/rt/hle.c"], draft=True)
        self.assertEqual(result["allow_substantive"], "false")
        self.assertEqual(result["run_native"], "true")

    def test_draft_unknown_path_stays_suppressed_but_fails_closed(self) -> None:
        result = classify(["new-tool-input.dat"], draft=True)
        self.assertEqual(result["allow_substantive"], "false")
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_dashboard"], "true")

    def test_workflow_change_on_main_push_still_allows_substantive(self) -> None:
        with patch.dict(os.environ, {"GITHUB_REF": "refs/heads/main"}):
            result = classify([".github/workflows/ci.yml"], event_name="push")
        self.assertEqual(result["allow_substantive"], "true")
        self.assertEqual(result["run_main_smoke"], "true")

    def test_non_main_push_is_not_treated_as_main_smoke(self) -> None:
        with patch.dict(os.environ, {"GITHUB_REF": "refs/heads/feature"}):
            result = classify(["src/rt/hle.c"], event_name="push")
        self.assertEqual(result["run_main_smoke"], "false")
        self.assertEqual(result["allow_substantive"], "true")

    def test_workflow_dispatch_ignores_paths_entirely(self) -> None:
        result = classify(["docs/CI.md"], event_name="workflow_dispatch")
        for key in (
            "run_python",
            "run_native",
            "run_windows",
            "run_dashboard",
            "run_markdown",
            "run_main_smoke",
            "allow_substantive",
        ):
            self.assertEqual(result[key], "true")

    def test_manual_dispatch_requests_the_complete_contract(self) -> None:
        result = classify([], event_name="workflow_dispatch")
        for key in (
            "run_python",
            "run_native",
            "run_windows",
            "run_dashboard",
            "run_markdown",
            "run_main_smoke",
            "allow_substantive",
        ):
            self.assertEqual(result[key], "true")

    def test_pull_request_does_not_request_main_smoke(self) -> None:
        self.assertEqual(classify(["src/rt/hle.c"], event_name="pull_request")["run_main_smoke"], "false")

    def test_git_extraction_retains_deleted_and_renamed_paths(self) -> None:
        status = "D\tsrc/rt/removed.c\nR100\tsrc/rt/old.c\tdocs/new.md\n"
        self.assertEqual(
            ci_paths_module._parse_changed_paths(status),
            ["src/rt/removed.c", "src/rt/old.c", "docs/new.md"],
        )

    def test_git_extraction_accepts_valid_one_path_statuses(self) -> None:
        status = "A\tsrc/a.c\nM\tsrc/m.c\nD\tsrc/d.c\nT\tsrc/t.c\nU\tsrc/u.c\n"
        self.assertEqual(
            ci_paths_module._parse_changed_paths(status),
            ["src/a.c", "src/m.c", "src/d.c", "src/t.c", "src/u.c"],
        )

    def test_git_extraction_accepts_valid_copy_records(self) -> None:
        status = "C075\tsrc/old.c\tdocs/new.md\n"
        self.assertEqual(
            ci_paths_module._parse_changed_paths(status),
            ["src/old.c", "docs/new.md"],
        )

    def test_git_extraction_accepts_valid_rename_copy_score_boundaries(self) -> None:
        for status in (
            "R000\tsrc/old.c\tdocs/new.md",
            "C000\tsrc/old.c\tdocs/new.md",
            "R075\tsrc/old.c\tdocs/new.md",
            "C075\tsrc/old.c\tdocs/new.md",
            "R100\tsrc/old.c\tdocs/new.md",
            "C100\tsrc/old.c\tdocs/new.md",
        ):
            with self.subTest(status=status):
                self.assertEqual(
                    ci_paths_module._parse_changed_paths(status),
                    ["src/old.c", "docs/new.md"],
                )

    def test_invalid_rename_copy_scores_fail_closed(self) -> None:
        for status in (
            "R\tsrc/old.c\tdocs/new.md",
            "C\tsrc/old.c\tdocs/new.md",
            "R101\tsrc/old.c\tdocs/new.md",
            "C999\tsrc/old.c\tdocs/new.md",
            "Rabc\tsrc/old.c\tdocs/new.md",
            "C-1\tsrc/old.c\tdocs/new.md",
        ):
            with self.subTest(status=status):
                self.assertEqual(
                    ci_paths_module._parse_changed_paths(status),
                    ["<history-unavailable>"],
                )

    def test_malformed_status_records_force_full_classification(self) -> None:
        malformed = (
            "R100\tdocs/foo.md",
            "C075\tsrc/foo.c",
            "M",
            "M\t",
            "garbage",
            "Q\tdocs/foo.md",
            "M\tdocs/foo.md\textra",
            "R100\tdocs/foo.md\tsrc/foo.c\textra",
        )
        for status in malformed:
            with self.subTest(status=status):
                self.assertEqual(ci_paths_module._parse_changed_paths(status), ["<history-unavailable>"])
                result = classify(ci_paths_module._parse_changed_paths(status))
                self.assertEqual(result["run_native"], "true")
                self.assertEqual(result["run_windows"], "true")

    def test_blank_lines_are_ignored_but_mixed_malformed_records_fail_closed(self) -> None:
        self.assertEqual(
            ci_paths_module._parse_changed_paths("\nA\tsrc/a.c\n\nM\tdocs/b.md\n"),
            ["src/a.c", "docs/b.md"],
        )
        self.assertEqual(
            ci_paths_module._parse_changed_paths("A\tsrc/a.c\nR100\tdocs/only.md\n"),
            ["<history-unavailable>"],
        )

    def test_hst_tests_use_their_logical_build_subject(self) -> None:
        for path in (
            "tools/test_hst_manager_manifest.py",
            "tools/test_hst_title_manifest.py",
            "tools/test_hst_doctor.py",
        ):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true")
                self.assertEqual(result["run_windows"], "true")

    def test_codegen_test_uses_its_logical_native_subject(self) -> None:
        result = classify(["tools/test_codegen.py"])
        self.assertEqual(result["run_native"], "true")
        self.assertEqual(result["run_windows"], "true")

    def test_c_harness_tests_use_their_logical_native_subject(self) -> None:
        for path in (
            "tools/test_dispatch_c.py",
            "tools/test_evf_c.py",
            "tools/test_guestmem_c.py",
            "tools/test_pgd_c.py",
            "tools/test_sdkver_c.py",
            "tools/test_vfs_c.py",
            "tools/test_native_driver_hardening.py",
            "tools/test_ref_run_elf_hardening.py",
            "tools/test_savedata_spans.py",
            "tools/test_sched_invariants.py",
        ):
            with self.subTest(path=path):
                result = classify([path])
                self.assertEqual(result["run_native"], "true")
                self.assertEqual(result["run_windows"], "true")

    def test_python_only_test_keeps_native_gates_off(self) -> None:
        result = classify(["tools/test_progress_tracker.py"])
        self.assertEqual(result["run_python"], "true")
        self.assertEqual(result["run_native"], "false")
        self.assertEqual(result["run_windows"], "false")

    def test_all_test_tools_follow_logical_subject_predicates(self) -> None:
        tools_root = Path(__file__).resolve().parent
        for test_path in sorted(tools_root.glob("test_*.py")):
            relative = test_path.relative_to(tools_root.parent).as_posix()
            logical = ci_paths_module._logical_tool_path(relative)
            self.assertIsNotNone(logical)
            assert logical is not None
            expected_native = any(
                predicate(logical)
                for predicate in (
                    ci_paths_module._is_workflow_ci,
                    ci_paths_module._is_title_manifest,
                    ci_paths_module._is_build_system,
                    ci_paths_module._is_native_tool,
                )
            )
            result = classify([relative])
            self.assertEqual(result["run_native"] == "true", expected_native, relative)
            self.assertEqual(result["run_windows"] == "true", expected_native, relative)

    @patch.object(ci_paths_module.subprocess, "run")
    def test_git_diff_requests_status_and_rename_information(self, run) -> None:
        run.return_value.stdout = "D\tsrc/rt/removed.c\nR100\tsrc/rt/old.c\tdocs/new.md\n"
        paths = ci_paths_module._changed_files_from_git(
            "pull_request",
            {"pull_request": {"base": {"sha": "base"}}},
        )
        self.assertEqual(paths, ["src/rt/removed.c", "src/rt/old.c", "docs/new.md"])
        args = run.call_args.args[0]
        self.assertIn("--name-status", args)
        self.assertIn("--find-renames", args)

    def test_backslash_and_dotslash_paths_normalise(self) -> None:
        """A Windows-style or ./-prefixed path must not fall through to unknown."""
        self.assertEqual(classify(["src\\rt\\hle.c"])["run_native"], "true")
        self.assertEqual(classify(["./docs/CI.md"])["docs_only"], "true")


if __name__ == "__main__":
    unittest.main()
