#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 the Nakagawa Recomp authors

"""Emit the build-local runtime title configuration consumed by ``src/rt/title_config.c``.

The compiled runtime carries no title identity of its own. This generator turns a
*validated* public title manifest's optional ``runtime_bindings`` block into a
deterministic build-local C header under ``build/<game>/``; with no manifest it emits
the generic configuration in which every optional binding is disabled.

It deliberately depends on the manifest alone: no guest executable, no analysis
product, and no generated retail translation unit is read, so a generic
``runtime-objects`` build never needs a retail input to compile.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import sys
import tempfile
from typing import Any

import title_manifest

#: Bumped only when the emitted macro contract changes. ``src/rt/title_config.c``
#: refuses to compile against a different value, so a stale generated header is a
#: build failure rather than a silently wrong runtime.
GENERATED_SCHEMA_VERSION = 1

#: Emitted field -> the C validity bit that gates it. Fields sharing a bit are a
#: configured-together group; the manifest validator already enforces the pairing.
FIELD_BITS: dict[str, str] = {
    "fallback_entry": "SR_TITLE_CFG_FALLBACK_ENTRY",
    "worker_thread_entry": "SR_TITLE_CFG_WORKER_ENTRY",
    "launcher_thread_entry": "SR_TITLE_CFG_LAUNCHER_ENTRY",
    "vblank_frame_counter_addr": "SR_TITLE_CFG_VBLANK_COUNTERS",
    "vblank_vsync_counter_addr": "SR_TITLE_CFG_VBLANK_COUNTERS",
}

GENERIC_SOURCE_ID = "none"


class TitleRuntimeConfigError(ValueError):
    """Fail-closed generation error."""


def bindings_from_manifest(manifest: dict[str, Any] | None) -> dict[str, Any]:
    """Return the normalized binding set for a manifest (or the generic empty set)."""
    if manifest is None:
        return {"source_id": GENERIC_SOURCE_ID, "bindings": {}}
    normalized = title_manifest.validate_manifest(manifest)
    block = dict(normalized.get("runtime_bindings") or {})
    block.pop("schema_version", None)
    unknown = sorted(set(block) - set(FIELD_BITS))
    if unknown:
        # Unreachable through the validator; a fail-closed guard against a future
        # manifest field silently reaching the runtime without a C binding.
        raise TitleRuntimeConfigError(
            "runtime binding(s) have no runtime representation: " + ", ".join(unknown)
        )
    return {"source_id": normalized["id"], "bindings": block}


def config_digest(config: dict[str, Any]) -> str:
    """Deterministic identity of the emitted configuration.

    The build binds this into the runtime profile hash, so changing a title binding
    invalidates every stale runtime object rather than relinking one silently.
    """
    payload = {
        "generated_schema_version": GENERATED_SCHEMA_VERSION,
        "source_id": config["source_id"],
        "bindings": config["bindings"],
    }
    rendered = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(rendered.encode("utf-8")).hexdigest()


def render_header(config: dict[str, Any]) -> str:
    bindings: dict[str, int] = config["bindings"]
    valid = sorted({FIELD_BITS[name] for name in bindings})
    valid_text = " | ".join(valid) if valid else "0u"
    source_id = config["source_id"]
    if '"' in source_id or "\\" in source_id:
        raise TitleRuntimeConfigError("title id is not representable as a C string literal")
    lines = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "/* Copyright (C) 2026 the Nakagawa Recomp authors */",
        "/* GENERATED by tools/title_runtime_config.py -- do not edit.",
        " * Derived from validated title configuration only; contains no analysis product",
        " * and no guest bytes. A build with no title configuration emits every optional",
        " * binding disabled. */",
        "#ifndef SR_TITLE_CONFIG_GENERATED_H",
        "#define SR_TITLE_CONFIG_GENERATED_H",
        "",
        f"#define SR_TITLE_CONFIG_SCHEMA_VERSION {GENERATED_SCHEMA_VERSION}",
        f'#define SR_TITLE_CONFIG_SOURCE_ID "{source_id}"',
        f'#define SR_TITLE_CONFIG_DIGEST "{config_digest(config)}"',
        f"#define SR_TITLE_CONFIG_VALID ({valid_text})",
        "",
    ]
    for name in FIELD_BITS:
        macro = "SR_TITLE_CONFIG_" + name.upper()
        value = bindings.get(name, 0)
        lines.append(f"#define {macro} 0x{value:08x}u")
    lines += ["", "#endif /* SR_TITLE_CONFIG_GENERATED_H */", ""]
    return "\n".join(lines)


def write_if_changed(path: Path, rendered: str) -> bool:
    """Write atomically, leaving an identical file (and its mtime) untouched."""
    if path.is_symlink():
        raise TitleRuntimeConfigError(f"{path}: refusing to replace a symbolic link")
    if path.is_file() and path.read_text(encoding="utf-8") == rendered:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(rendered)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_path, path)
    except Exception:
        temp_path.unlink(missing_ok=True)
        raise
    return True


def load_config(manifest_path: Path | None) -> dict[str, Any]:
    manifest = None
    if manifest_path is not None:
        manifest = title_manifest.load_manifest(manifest_path)
    return bindings_from_manifest(manifest)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        help="validated title manifest; omit for the generic no-title configuration",
    )
    parser.add_argument("--output", type=Path, help="generated header path")
    parser.add_argument(
        "--print-digest",
        action="store_true",
        help="print the configuration digest and exit (no header is written)",
    )
    args = parser.parse_args(argv)
    try:
        config = load_config(args.manifest)
        if args.print_digest:
            print(config_digest(config))
            return 0
        if args.output is None:
            parser.error("--output is required unless --print-digest is given")
        changed = write_if_changed(args.output, render_header(config))
        print(
            f"title runtime config: {config['source_id']} "
            f"({len(config['bindings'])} binding(s), {'written' if changed else 'unchanged'})"
        )
        return 0
    except (title_manifest.TitleManifestError, TitleRuntimeConfigError, OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
