#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 the Nakagawa Recomp authors

"""Deterministic C code generator for the native public title catalog.

Single source of truth: assets/titles/*.json filtered strictly by the canonical
publication policy (assets/public_source_profile.json).
Emits:
  src/core/generated/nk_title_catalog.h
  src/core/generated/nk_title_catalog.c

Guarantees:
  - Unknown, unclassified, or excluded manifests (such as hst-ucus98701.json)
    are NEVER included in the public catalog.
  - Generates an in-memory runtime overlay hook for local private testing.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import sys
from typing import Any, Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import publication_policy
import title_manifest

SYNTHETIC_DISC_ID_MAP = {
    "synthetic-allegrex-v1": "TEST00001",
    "synthetic-title2-v1": "TEST00002",
    "pspdev-phase5-v1": "TEST00005",
}


def _c_string_escape(value: str) -> str:
    """Escape a value for a C string literal.

    Backslashes must be escaped BEFORE quotes: escaping quotes first would
    then re-escape the backslash this function just introduced. The manifest
    schema permits both characters in display_name, so a name containing
    either previously emitted a broken or misinterpreted literal.
    """
    return value.replace(chr(92), chr(92) * 2).replace('"', chr(92) + '"')


def compute_manifest_digest(manifest_files: List[Path]) -> str:
    h = hashlib.sha256()
    for mf in sorted(manifest_files, key=lambda p: p.name):
        h.update(mf.name.encode("utf-8"))
        h.update(mf.read_bytes())
    return h.hexdigest()[:16]


def collect_public_manifests(
    manifest_dir: Path,
    policy: Optional[publication_policy.Policy] = None,
) -> Tuple[List[Path], List[Dict[str, Any]]]:
    """Collect ONLY public-eligible title manifests according to publication policy."""
    if policy is None:
        policy_path = ROOT / "assets" / "public_source_profile.json"
        policy = publication_policy.load_policy(policy_path)

    all_json = sorted(manifest_dir.glob("*.json"))
    public_files: List[Path] = []

    for mf in all_json:
        try:
            rel = mf.relative_to(ROOT).as_posix()
        except ValueError:
            rel = f"assets/titles/{mf.name}"

        res = policy.resolve(rel)
        if res.is_excluded:
            # Explicitly excluded by policy (e.g. retail titles)
            continue
        if res.disposition != publication_policy.INCLUDED:
            # Unclassified manifests fail closed
            continue
        public_files.append(mf)

    results: List[Dict[str, Any]] = []
    for mf in public_files:
        try:
            raw = title_manifest.load_manifest(mf)
            validated = title_manifest.validate_manifest(raw)
            results.append(validated)
        except Exception as exc:
            print(f"ERROR validating public manifest {mf}: {exc}", file=sys.stderr)
            raise

    # Sort deterministically by ID
    results.sort(key=lambda item: item["id"])
    return public_files, results


def generate_header(digest: str, titles: List[Dict[str, Any]]) -> str:
    lines = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "/* Copyright (C) 2026 the Nakagawa Recomp authors */",
        "/* AUTOGENERATED FILE - DO NOT EDIT DIRECTLY */",
        "/* Generated by tools/title_catalog_codegen.py from public assets/titles/ manifests */",
        "",
        "#ifndef NK_TITLE_CATALOG_H",
        "#define NK_TITLE_CATALOG_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "#define NK_TITLE_CATALOG_SCHEMA_VERSION 1",
        f'#define NK_TITLE_CATALOG_DIGEST "{digest}"',
        "",
        "typedef enum {",
        "    NK_TITLE_KIND_RETAIL = 0,",
        "    NK_TITLE_KIND_SYNTHETIC,",
        "    NK_TITLE_KIND_HOMEBREW",
        "} NkTitleKind;",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint32_t load_address;",
        "    bool required;",
        "} NkModuleDefinition;",
        "",
        "typedef struct {",
        "    const char *id;                     /* e.g. \"synthetic-allegrex-v1\" */",
        "    const char *display_name;",
        "    NkTitleKind kind;",
        "    const char *primary_disc_id;",
        "    const char * const *compatible_disc_ids; /* NULL-terminated array of alias disc IDs */",
        "    uint32_t executable_base;",
        "    uint32_t executable_entry;",
        "    const char *data_root;",
        "    const char *memory_stick_root;",
        "    const char *hle_profile;",
        "    const char *codegen_profile;",
        "    uint32_t expected_data_file_count;",
        "    bool requires_font_firmware;",
        "    bool requires_psmf;",
        "    const NkModuleDefinition *modules;",
        "    int module_count;",
        "} NkTitleEntry;",
        "",
        "/* Total public titles in static catalog */",
        "extern const int nk_title_catalog_count;",
        "extern const NkTitleEntry nk_title_catalog_entries[];",
        "",
        "/* Public lookup functions */",
        "const NkTitleEntry *nk_title_catalog_find_by_disc_id(const char *disc_id);",
        "const NkTitleEntry *nk_title_catalog_find_by_id(const char *title_id);",
        "",
        "/* Runtime private overlay registration (for local private acceptance testing) */",
        "void nk_title_catalog_register_overlay(const NkTitleEntry *overlay_entry);",
        "void nk_title_catalog_clear_overlay(void);",
        "const NkTitleEntry *nk_title_catalog_get_overlay(void);",
        "",
        "#endif /* NK_TITLE_CATALOG_H */",
        "",
    ]
    return "\n".join(lines)


def generate_source(digest: str, titles: List[Dict[str, Any]]) -> str:
    lines = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "/* Copyright (C) 2026 the Nakagawa Recomp authors */",
        "/* AUTOGENERATED FILE - DO NOT EDIT DIRECTLY */",
        "/* Generated by tools/title_catalog_codegen.py from public assets/titles/ manifests */",
        "",
        '#include "nk_title_catalog.h"',
        "#include <ctype.h>",
        "#include <string.h>",
        "",
        "#define NK_CATALOG_MAX_OVERLAYS 8",
        "static const NkTitleEntry *s_private_overlay_entries[NK_CATALOG_MAX_OVERLAYS];",
        "static int s_private_overlay_count = 0;",
        "",
        "void nk_title_catalog_register_overlay(const NkTitleEntry *overlay_entry) {",
        "    if (!overlay_entry) return;",
        "    for (int i = 0; i < s_private_overlay_count; i++) {",
        "        if (s_private_overlay_entries[i] == overlay_entry ||",
        "            (s_private_overlay_entries[i]->id && overlay_entry->id &&",
        "             strcmp(s_private_overlay_entries[i]->id, overlay_entry->id) == 0)) {",
        "            s_private_overlay_entries[i] = overlay_entry;",
        "            return;",
        "        }",
        "    }",
        "    if (s_private_overlay_count < NK_CATALOG_MAX_OVERLAYS) {",
        "        s_private_overlay_entries[s_private_overlay_count++] = overlay_entry;",
        "    }",
        "}",
        "",
        "void nk_title_catalog_clear_overlay(void) {",
        "    s_private_overlay_count = 0;",
        "}",
        "",
        "const NkTitleEntry *nk_title_catalog_get_overlay(void) {",
        "    return s_private_overlay_count > 0 ? s_private_overlay_entries[s_private_overlay_count - 1] : NULL;",
        "}",
        "",
    ]

    # Emit modules arrays
    for idx, t in enumerate(titles):
        modules = t.get("modules", [])
        if modules:
            lines.append(f"static const NkModuleDefinition s_modules_title_{idx}[] = {{")
            for m in modules:
                req_str = "true" if m.get("required") else "false"
                lines.append(f'    {{ "{m["name"]}", 0x{m["load_address"]:08x}U, {req_str} }},')
            lines.append("};")
            lines.append("")

    # Emit compatible disc ID arrays
    for idx, t in enumerate(titles):
        disc_info = t.get("disc", {})
        compat = disc_info.get("compatible_revisions", [])
        if compat:
            lines.append(f"static const char * const s_compat_discs_{idx}[] = {{")
            for cid in compat:
                lines.append(f'    "{cid}",')
            lines.append("    NULL")
            lines.append("};")
            lines.append("")

    # Emit main public catalog array
    lines.append(f"const int nk_title_catalog_count = {len(titles)};")
    lines.append("const NkTitleEntry nk_title_catalog_entries[] = {")

    for idx, t in enumerate(titles):
        t_id = t["id"]
        t_name = _c_string_escape(t["display_name"])
        kind = t["kind"]
        if kind == "retail":
            kind_enum = "NK_TITLE_KIND_RETAIL"
            disc_id = t["disc"]["id"]
        elif kind == "synthetic":
            kind_enum = "NK_TITLE_KIND_SYNTHETIC"
            disc_id = SYNTHETIC_DISC_ID_MAP.get(t_id, "TEST00000")
        else:
            kind_enum = "NK_TITLE_KIND_HOMEBREW"
            disc_id = ""

        exe_base = t["executable"]["base"]
        exe_entry = t["executable"]["entry"]
        data_root = t["filesystem"]["data_root"]
        ms_root = t["filesystem"]["memory_stick_root"]
        hle = t["hle_profile"]
        codegen = t.get("codegen_profile", "none")
        expected_files = t.get("runtime_bindings", {}).get("expected_data_file_count", 0)

        feats = t.get("feature_requirements", [])
        req_font = "true" if ("font-firmware" in feats or "font" in feats) else "false"
        req_psmf = "true" if ("psmf" in feats) else "false"

        num_mods = len(t.get("modules", []))
        mod_ref = f"s_modules_title_{idx}" if num_mods > 0 else "NULL"
        compat_ref = f"s_compat_discs_{idx}" if t.get("disc", {}).get("compatible_revisions") else "NULL"

        lines.append("    {")
        lines.append(f'        "{t_id}",')
        lines.append(f'        "{t_name}",')
        lines.append(f"        {kind_enum},")
        lines.append(f'        "{disc_id}",')
        lines.append(f"        {compat_ref},")
        lines.append(f"        0x{exe_base:08x}U,")
        lines.append(f"        0x{exe_entry:08x}U,")
        lines.append(f'        "{data_root}",')
        lines.append(f'        "{ms_root}",')
        lines.append(f'        "{hle}",')
        lines.append(f'        "{codegen}",')
        lines.append(f"        {expected_files}U,")
        lines.append(f"        {req_font},")
        lines.append(f"        {req_psmf},")
        lines.append(f"        {mod_ref},")
        lines.append(f"        {num_mods}")
        lines.append("    },")

    lines.append("};")
    lines.append("")

    # Emit helper normalize function
    lines.extend([
        "static void normalize_disc_id(const char *src, char *dst, size_t dst_size) {",
        "    size_t d = 0;",
        "    if (!src || !dst || dst_size == 0) return;",
        "    for (size_t s = 0; src[s] != '\\0' && d + 1 < dst_size; s++) {",
        "        char c = src[s];",
        "        if (c == '-' || c == '_' || c == ' ') continue;",
        "        dst[d++] = (char)toupper((unsigned char)c);",
        "    }",
        "    dst[d] = '\\0';",
        "}",
        "",
        "const NkTitleEntry *nk_title_catalog_find_by_disc_id(const char *disc_id) {",
        "    if (!disc_id || !*disc_id) return NULL;",
        "    char norm[32];",
        "    normalize_disc_id(disc_id, norm, sizeof(norm));",
        "    if (!norm[0]) return NULL;",
        "",
        "    /* 1. Check in-memory private overlays first (most recently registered first) */",
        "    for (int i = s_private_overlay_count - 1; i >= 0; i--) {",
        "        const NkTitleEntry *ov = s_private_overlay_entries[i];",
        "        if (!ov) continue;",
        "        if (ov->primary_disc_id) {",
        "            char ov_norm[32];",
        "            normalize_disc_id(ov->primary_disc_id, ov_norm, sizeof(ov_norm));",
        "            if (strcmp(norm, ov_norm) == 0) {",
        "                return ov;",
        "            }",
        "        }",
        "        if (ov->compatible_disc_ids) {",
        "            for (int c = 0; ov->compatible_disc_ids[c]; c++) {",
        "                char cp_norm[32];",
        "                normalize_disc_id(ov->compatible_disc_ids[c], cp_norm, sizeof(cp_norm));",
        "                if (strcmp(norm, cp_norm) == 0) {",
        "                    return ov;",
        "                }",
        "            }",
        "        }",
        "    }",
        "",
        "    /* 2. Check static public catalog */",
        "    for (int i = 0; i < nk_title_catalog_count; i++) {",
        "        const NkTitleEntry *e = &nk_title_catalog_entries[i];",
        "        if (e->primary_disc_id && e->primary_disc_id[0]) {",
        "            char entry_norm[32];",
        "            normalize_disc_id(e->primary_disc_id, entry_norm, sizeof(entry_norm));",
        "            if (strcmp(norm, entry_norm) == 0) {",
        "                return e;",
        "            }",
        "        }",
        "        if (e->compatible_disc_ids) {",
        "            for (int c = 0; e->compatible_disc_ids[c]; c++) {",
        "                char compat_norm[32];",
        "                normalize_disc_id(e->compatible_disc_ids[c], compat_norm, sizeof(compat_norm));",
        "                if (strcmp(norm, compat_norm) == 0) {",
        "                    return e;",
        "                }",
        "            }",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
        "const NkTitleEntry *nk_title_catalog_find_by_id(const char *title_id) {",
        "    if (!title_id || !*title_id) return NULL;",
        "    for (int i = s_private_overlay_count - 1; i >= 0; i--) {",
        "        const NkTitleEntry *ov = s_private_overlay_entries[i];",
        "        if (ov && ov->id && strcmp(title_id, ov->id) == 0) {",
        "            return ov;",
        "        }",
        "    }",
        "    for (int i = 0; i < nk_title_catalog_count; i++) {",
        "        if (strcmp(title_id, nk_title_catalog_entries[i].id) == 0) {",
        "            return &nk_title_catalog_entries[i];",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
    ])

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate native C catalog from public assets/titles/*.json")
    parser.add_argument("--manifest-dir", type=Path, default=ROOT / "assets" / "titles")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "src" / "core" / "generated")
    parser.add_argument("--verify", action="store_true", help="Check if existing output matches live public manifests")
    args = parser.parse_args()

    policy_path = ROOT / "assets" / "public_source_profile.json"
    policy = publication_policy.load_policy(policy_path)

    manifest_files, titles = collect_public_manifests(args.manifest_dir, policy=policy)
    if not manifest_files:
        print(f"ERROR: No public .json title manifests found in {args.manifest_dir}", file=sys.stderr)
        return 1

    digest = compute_manifest_digest(manifest_files)

    header_content = generate_header(digest, titles)
    source_content = generate_source(digest, titles)

    out_h = args.output_dir / "nk_title_catalog.h"
    out_c = args.output_dir / "nk_title_catalog.c"

    if args.verify:
        if not out_h.is_file() or not out_c.is_file():
            print("ERROR: Generated public catalog files do not exist.", file=sys.stderr)
            return 1
        curr_h = out_h.read_text(encoding="utf-8")
        curr_c = out_c.read_text(encoding="utf-8")
        if curr_h != header_content or curr_c != source_content:
            print("ERROR: Native public title catalog is out of date. Run tools/title_catalog_codegen.py.", file=sys.stderr)
            return 1
        print(f"OK: Native public title catalog is up to date (digest {digest}, {len(titles)} public titles).")
        return 0

    args.output_dir.mkdir(parents=True, exist_ok=True)
    out_h.write_text(header_content, encoding="utf-8")
    out_c.write_text(source_content, encoding="utf-8")
    print(f"Generated {out_h} and {out_c} (digest {digest}, {len(titles)} public titles).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
