#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 the Nakagawa Recomp authors

"""Generate the overlap-differential cases header for vfpu_interp_selftest.c.

Produces a header containing:
  - OVERLAP_DIFF_NCASES count
  - overlap_diff_cases[] table (instruction word + name)
  - overlap_diff_run_codegen() switch dispatcher

Every body is emitted by the production codegen path (tools/codegen.py
vfpu_effect), so the header stays in sync with the current emitter.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import codegen


def _bin_word(op6: int, sub: int, size: int, vd: int, vs: int, vt: int) -> int:
    lo, hi = (size - 1) & 1, (size - 1) >> 1
    return (
        ((op6 & 0x3F) << 26)
        | ((sub & 7) << 23)
        | ((vt & 0x7F) << 16)
        | ((vs & 0x7F) << 8)
        | (vd & 0x7F)
        | (lo << 7)
        | (hi << 15)
    )


def _matrix1_word(which: int, size: int, vd: int, vs: int) -> int:
    lo, hi = (size - 1) & 1, (size - 1) >> 1
    return (
        (0x3C << 26)
        | (28 << 21)
        | ((which & 0xF) << 16)
        | ((vs & 0x7F) << 8)
        | (vd & 0x7F)
        | (lo << 7)
        | (hi << 15)
    )


def build_cases() -> tuple[list[tuple[int, str, int]], int]:
    cases: list[tuple[int, str, int]] = []

    # vhdp.t (op 0x19 sub 4 size 3): destination overlaps sources
    cases.append((_bin_word(0x19, 4, 3, 0x20, 0x20, 0x00), "vhdp-t-partial-overlap", 5))

    # vhdp.t disjoint control
    cases.append((_bin_word(0x19, 4, 3, 0x10, 0x20, 0x00), "vhdp-t-disjoint", 5))

    # vhdp.t signed-zero corpus: keep the source vectors disjoint so the
    # first product can be -0. The explicit zero accumulator in the repaired
    # emitter then has an observable result under the host's IEEE add rules;
    # the historical chained expression does not.
    exotic_index = len(cases)
    cases.append((_bin_word(0x19, 4, 3, 0x08, 0x00, 0x04), "vhdp-t-signed-zero", 5))

    # vmscl.t (op 0x3C sub 4 size 3): scalar inside destination matrix
    cases.append((_bin_word(0x3C, 4, 3, 0x20, 0x20, 0x00), "vmscl-t-scalar-in-dest", 2))

    # vmscl.t disjoint control
    cases.append((_bin_word(0x3C, 4, 3, 0x10, 0x20, 0x00), "vmscl-t-disjoint", 2))

    # vmscl alias (Matrix1 which=1) with scalar inside destination
    cases.append((_matrix1_word(1, 3, 0x20, 0x20), "vmscl-alias-scalar-in-dest", 2))

    # vmscl alias disjoint control
    cases.append((_matrix1_word(1, 3, 0x10, 0x20), "vmscl-alias-disjoint", 2))

    # Verify every word decodes through the production emitter without fallback.
    for w, name, _ in cases:
        body, _, _ = codegen.vfpu_effect(0x08900000, w)
        if "sr_vfpu_interp" in body:
            raise AssertionError(f"overlap diff word 0x{w:08x} ({name}) falls back to sr_vfpu_interp")

    return cases, exotic_index


def write_header(out_path: str, cases: list[tuple[int, str, int]], exotic_index: int) -> None:
    out = ["/* Generated by tools/vfpu_overlap_diff_gen.py. Do not edit. */", ""]
    out.append("#ifndef NAKAGAWA_VFPU_OVERLAP_DIFF_H")
    out.append("#define NAKAGAWA_VFPU_OVERLAP_DIFF_H")
    out.append("")
    out.append(f"#define OVERLAP_DIFF_NCASES {len(cases)}")
    out.append(f"#define OVERLAP_DIFF_VHDP_EXOTIC_INDEX {exotic_index}")
    out.append("")
    out.append("static const struct { uint32_t w; const char *name; } overlap_diff_cases[OVERLAP_DIFF_NCASES] = {")
    for w, name, _ in cases:
        out.append(f'    {{0x{w:08x}u, "{name}"}},')
    out.append("};")
    out.append("")
    out.append("static void overlap_diff_run_codegen(CpuState *s, int idx) {")
    out.append("    switch (idx) {")
    for i, (w, name, _) in enumerate(cases):
        body, _, _ = codegen.vfpu_effect(0x08900000, w)
        out.append(f'    case {i}: /* {name} */ {body} break;')
    out.append("    default: break;")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("#endif /* NAKAGAWA_VFPU_OVERLAP_DIFF_H */")
    Path(out_path).write_text("\n".join(out) + "\n", encoding="ascii", newline="\n")
    sys.stderr.write(f"vfpu_overlap_diff_gen: {len(cases)} cases -> {out_path}\n")


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv
    if len(argv) < 2:
        sys.stderr.write("usage: vfpu_overlap_diff_gen.py <out.h>\n")
        return 2
    cases, exotic_index = build_cases()
    write_header(argv[1], cases, exotic_index)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
