#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025-2026 the psp-recomp authors
# Derived from sal063/PSP-recompilation-project (GPL-2.0-or-later)
# Modified by Nakagawa Recomp contributors, 2026-08-10.
# See NOTICE.md for upstream lineage and modification provenance.

"""VFPU differential-fuzz case generator.

Two operating modes:

  PUBLIC SYNTHETIC MODE (no private inputs required):
    vfpu_fuzz_gen.py --synthetic <out.h>
    Uses tools/vfpu_synth_gen.py to generate a deterministic set of VFPU
    instruction words from public encoding knowledge.  This is the mode used
    in CI and must not require the game ELF.

  PRIVATE GAME-OBSERVED MODE (local only, never committed):
    vfpu_fuzz_gen.py <elf> <out.h> [--base=HEX]
    Scans the private ELF's executable ranges for every DISTINCT VFPU compute
    instruction word (opcode families VFPU_COMPUTE_OPS) and generates cases
    for all of them.  The ELF and any generated corpus file must remain local
    and git-ignored.

In both modes the generator:
  1. Calls codegen.vfpu_effect(addr, word) for each candidate.
  2. SKIPS any word where vfpu_effect raises codegen.Unsupported (fallback path).
  3. ENFORCES the self-comparison invariant: a differential test must never
     silently compare sr_vfpu_interp against itself.  If the generated C for a
     case contains "sr_vfpu_interp", the case is classified as a FALLBACK and
     excluded.  A summary is printed at the end.

src/rt/vfpu_fuzz.c runs each case against sr_vfpu_interp on randomized states
and reports divergences.

SHARED-HELPER LIMITATION:
Both the codegen emitter path and sr_vfpu_interp share some implementation
components (sr_vread, sr_vwrite, prefix decode helpers, transcendental kernels).
Therefore zero divergence proves "emitter and interpreter agree", NOT "the
implementation matches PSP hardware".  See tools/vfpu_coverage_report.py.
"""

import sys

from analyze import Elf, exec_ranges, analyzer_span_from_env
import codegen


VFPU_COMPUTE_OPS = {0x18, 0x19, 0x1B, 0x34, 0x37, 0x3C}  # 0x37 = vpfx (STATE) + viim/vfim


def _check_no_interp_call(body: str) -> bool:
    """Return True if the generated body does NOT call sr_vfpu_interp.

    This enforces the self-comparison invariant: a case that falls back to
    sr_vfpu_interp on the codegen side would compare interp vs interp.
    """
    return "sr_vfpu_interp" not in body


def generate_cases(words: dict[int, int]) -> tuple[list[tuple[int, int, str]], int, int]:
    """Translate instruction words to codegen bodies.

    Args:
        words: mapping of {instruction_word: sample_address}

    Returns:
        (cases, n_unsupported, n_self_compare)
        cases: list of (word, addr, body) for successfully translated instructions
        n_unsupported: count of words skipped because codegen raised Unsupported
        n_self_compare: count of words skipped because generated body calls sr_vfpu_interp
    """
    cases: list[tuple[int, int, str]] = []
    n_unsupported = 0
    n_self_compare = 0

    for w, addr in sorted(words.items()):
        try:
            body, _, _ = codegen.vfpu_effect(addr, w)
        except codegen.Unsupported as e:
            sys.stderr.write(f"skip (Unsupported): 0x{w:08x} @0x{addr:08x}: {e}\n")
            n_unsupported += 1
            continue

        if not _check_no_interp_call(body):
            sys.stderr.write(
                f"skip (self-compare VIOLATION): 0x{w:08x} @0x{addr:08x}: "
                f"generated body calls sr_vfpu_interp -- excluded from differential test\n"
            )
            n_self_compare += 1
            continue

        cases.append((w, addr, body))

    return cases, n_unsupported, n_self_compare


def write_header(out_path: str, cases: list[tuple[int, int, str]]) -> None:
    out = ["/* Generated by tools/vfpu_fuzz_gen.py. Do not edit. */", ""]
    out.append(f"#define FUZZ_NCASES {len(cases)}")
    out.append("static const struct { uint32_t w, addr; } fuzz_cases[FUZZ_NCASES] = {")
    for w, addr, _ in cases:
        out.append(f"    {{0x{w:08x}u, 0x{addr:08x}u}},")
    out.append("};")
    out.append("")
    out.append("static void fuzz_run_codegen(CpuState *s, int idx) {")
    out.append("    switch (idx) {")
    for i, (w, addr, body) in enumerate(cases):
        out.append(f"    case {i}: /* 0x{w:08x} @0x{addr:08x} */ {body} break;")
    out.append("    default: break;")
    out.append("    }")
    out.append("}")
    out.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(out))


def main(argv: list[str]) -> int:
    args = [a for a in argv[1:] if not a.startswith("--")]
    opts = [a for a in argv[1:] if a.startswith("--")]

    synthetic = "--synthetic" in opts
    base = None
    for o in opts:
        if o.startswith("--base="):
            base = int(o.split("=", 1)[1], 16)

    if synthetic:
        # PUBLIC SYNTHETIC MODE
        if len(args) < 1:
            sys.stderr.write(
                "usage: vfpu_fuzz_gen.py --synthetic <out.h>\n"
                "       vfpu_fuzz_gen.py <elf> <out.h> [--base=HEX]\n"
            )
            return 2
        out_path = args[0]
        try:
            from vfpu_synth_gen import generate_synthetic_corpus
        except ImportError:
            sys.path.insert(0, str(__import__("pathlib").Path(__file__).parent))
            from vfpu_synth_gen import generate_synthetic_corpus  # noqa: F811

        corpus = generate_synthetic_corpus()
        # Assign synthetic addresses starting at 0x08900000 (typical MIPS text base)
        words = {w: 0x08900000 + 4 * i for i, w in enumerate(corpus)}
        mode_label = "SYNTHETIC"
    else:
        # PRIVATE GAME-OBSERVED MODE (requires local ELF — never committed)
        if len(args) < 2:
            sys.stderr.write(
                "usage: vfpu_fuzz_gen.py --synthetic <out.h>\n"
                "       vfpu_fuzz_gen.py <elf> <out.h> [--base=HEX]\n"
            )
            return 2

        elf_path = args[0]
        out_path = args[1]

        if elf_path.endswith(".txt"):
            # Legacy: load from a pre-extracted word list file (local only)
            words: dict[int, int] = {}
            with open(elf_path, "r", encoding="utf-8") as f:
                for i, line in enumerate(f):
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    w_str = line.split()[0]
                    w = int(w_str, 16) if "0x" in w_str.lower() else int(w_str, 10)
                    words[w] = 0x08900000 + 4 * i
        else:
            elf = Elf(elf_path, base=base)
            ranges = exec_ranges(elf, extra_spans=analyzer_span_from_env())
            words = {}
            for lo, hi in ranges:
                a = lo
                while a + 4 <= hi:
                    w = codegen.read32(elf, a)
                    a += 4
                    if w is None:
                        continue
                    if (w >> 26) in VFPU_COMPUTE_OPS and w not in words:
                        words[w] = a - 4
        mode_label = "GAME-OBSERVED (local only -- do not commit output)"

    cases, n_unsupported, n_self_compare = generate_cases(words)

    if n_self_compare > 0:
        sys.stderr.write(
            f"ERROR: {n_self_compare} self-compare violation(s) detected and excluded.\n"
            "These cases would compare sr_vfpu_interp against itself -- not differential.\n"
        )
        # Do not abort; just exclude the cases and report.

    write_header(out_path, cases)
    sys.stderr.write(
        f"vfpu_fuzz_gen [{mode_label}]: {len(cases)} cases "
        f"({n_unsupported} skipped-Unsupported, {n_self_compare} excluded-self-compare)\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
